// react-now-ui-dashboard/src/views/Components/Buttons.jsx
/*!

=========================================================
* Now UI Dashboard PRO React - v1.3.0
=========================================================

* Product Page: https://www.creative-tim.com/product/now-ui-dashboard-pro-react
* Copyright 2019 Creative Tim (https://www.creative-tim.com)

* Coded by Creative Tim

=========================================================

* The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

*/
import React from "react";
import {
  ButtonGroup,
  ButtonToolbar,
  Card,
  CardHeader,
  CardBody,
  CardTitle,
  Row,
  Col,
  Pagination,
  PaginationItem,
  PaginationLink,
  Button
} from "reactstrap";

// core components
import PanelHeader from "components/PanelHeader/PanelHeader.jsx";

class Buttons extends React.Component {
  render() {
    return (
      <>
        <PanelHeader size="sm" />
        <div className="content">
          <Card>
            <Row>
              <Col xs={12} md={6}>
                <CardHeader>
                  <CardTitle tag="h4">Pick your Color</CardTitle>
                </CardHeader>
                <CardBody>
                  <div className="btns-mr-5">
                    <Button>Default</Button>
                    <Button color="primary">Primary</Button>
                    <Button color="info">Info</Button>
                    <Button color="success">Success</Button>
                    <Button color="warning">Warning</Button>
                    <Button color="danger">Danger</Button>
                  </div>
                </CardBody>
              </Col>
              <Col xs={12} md={6}>
                <CardHeader>
                  <CardTitle tag="h4">Buttons with Label</CardTitle>
                </CardHeader>
                <CardBody>
                  <div className="btns-mr-5">
                    <Button>
                      <span className="btn-label">
                        <i className="now-ui-icons arrows-1_minimal-left" />
                      </span>
                      Left
                    </Button>
                    <Button color="primary">
                      Right
                      <span className="btn-label">
                        <i className="now-ui-icons arrows-1_minimal-right" />
                      </span>
                    </Button>
                    <Button color="info">
                      <span className="btn-label">
                        <i className="now-ui-icons travel_info" />
                      </span>
                      Info
                    </Button>
                    <Button color="success">
                      <span className="btn-label">
                        <i className="now-ui-icons ui-1_check" />
                      </span>
                      Success
                    </Button>
                    <Button color="warning">
                      <span className="btn-label">
                        <i className="now-ui-icons ui-2_time-alarm" />
                      </span>
                      Warning
                    </Button>
                    <Button color="danger">
                      <span className="btn-label">
                        <i className="now-ui-icons ui-1_simple-remove" />
                      </span>
                      Danger
                    </Button>
                  </div>
                </CardBody>
              </Col>
            </Row>
            <Row>
              <Col xs={12} md={6}>
                <CardHeader>
                  <CardTitle tag="h4">Pick your Size</CardTitle>
                </CardHeader>
                <CardBody>
                  <div className="btns-mr-5">
                    <Button color="primary" size="sm">
                      Small
                    </Button>
                    <Button color="primary">Normal</Button>
                    <Button color="primary" size="lg">
                      Large
                    </Button>
                  </div>
                </CardBody>
              </Col>
              <Col xs={12} md={6}>
                <CardHeader>
                  <CardTitle tag="h4">Pick your Style</CardTitle>
                </CardHeader>
                <CardBody>
                  <div className="btns-mr-5">
                    <Button color="primary">Default</Button>
                    <Button color="primary" className="btn-round">
                      Round
                    </Button>
                    <Button color="primary" className="btn-round">
                      <i className="now-ui-icons ui-2_favourite-28" /> with icon
                    </Button>
                    <Button color="primary" className="btn-round btn-icon">
                      <i className="now-ui-icons ui-2_favourite-28" />
                    </Button>
                    <Button color="primary" outline>
                      Simple
                    </Button>
                  </div>
                </CardBody>
              </Col>
            </Row>
            <Row>
              <Col md={6} xs={12}>
                <CardHeader>
                  <CardTitle tag="h4">Pagination</CardTitle>
                </CardHeader>
                <CardBody>
                  <Pagination>
                    <PaginationItem active>
                      <PaginationLink href="#">1</PaginationLink>
                    </PaginationItem>
                    <PaginationItem>
                      <PaginationLink href="#">2</PaginationLink>
                    </PaginationItem>
                    <PaginationItem>
                      <PaginationLink href="#">3</PaginationLink>
                    </PaginationItem>
                    <PaginationItem>
                      <PaginationLink href="#">4</PaginationLink>
                    </PaginationItem>
                    <PaginationItem>
                      <PaginationLink href="#">5</PaginationLink>
                    </PaginationItem>
                  </Pagination>
                  <Pagination>
                    <PaginationItem>
                      <PaginationLink href="#">
                        <span aria-hidden="true">
                          <i
                            className="fa fa-angle-double-left"
                            aria-hidden="true"
                          />
                        </span>
                      </PaginationLink>
                    </PaginationItem>
                    <PaginationItem>
                      <PaginationLink href="#">1</PaginationLink>
                    </PaginationItem>
                    <PaginationItem active>
                      <PaginationLink href="#">2</PaginationLink>
                    </PaginationItem>
                    <PaginationItem>
                      <PaginationLink href="#">3</PaginationLink>
                    </PaginationItem>
                    <PaginationItem>
                      <PaginationLink href="#">
                        <span aria-hidden="true">
                          <i
                            className="fa fa-angle-double-right"
                            aria-hidden="true"
                          />
                        </span>
                      </PaginationLink>
                    </PaginationItem>
                  </Pagination>
                </CardBody>
              </Col>
              <Col md={6} xs={12}>
                <CardHeader>
                  <CardTitle tag="h4">Button Group</CardTitle>
                </CardHeader>
                <CardBody>
                  <ButtonGroup>
                    <Button color="info">Left</Button>
                    <Button color="info">Middle</Button>
                    <Button color="info">Right</Button>
                  </ButtonGroup>
                  <br />
                  <br />
                  <ButtonToolbar>
                    <ButtonGroup>
                      <Button className="btn-round" color="info">
                        1
                      </Button>
                      <Button className="btn-round" color="info">
                        2
                      </Button>
                      <Button className="btn-round" color="info">
                        3
                      </Button>
                      <Button className="btn-round" color="info">
                        4
                      </Button>
                    </ButtonGroup>
                    <ButtonGroup>
                      <Button className="btn-round" color="info">
                        5
                      </Button>
                      <Button className="btn-round" color="info">
                        6
                      </Button>
                      <Button className="btn-round" color="info">
                        7
                      </Button>
                    </ButtonGroup>
                  </ButtonToolbar>
                </CardBody>
              </Col>
            </Row>
            <Row>
              <Col xs={12}>
                <CardHeader>
                  <CardTitle tag="h4">Social buttons</CardTitle>
                </CardHeader>
                <CardBody>
                  <Row>
                    <Col md="4" sm="5">
                      <p className="category">Default</p>
                      <Button color="twitter">
                        <i className="fab fa-twitter" /> Connect with Twitter
                      </Button>
                    </Col>
                    <Col md="1" sm="1">
                      <p className="category"> </p>
                      <Button className="btn-icon" color="twitter">
                        <i className="fab fa-twitter" />
                      </Button>
                    </Col>
                    <Col md="1" sm="1">
                      <p className="category"> </p>
                      <Button className="btn-icon btn-round" color="twitter">
                        <i className="fab fa-twitter" />
                      </Button>
                    </Col>
                    <Col md="1" sm="1">
                      <p className="category">Neutral</p>
                      <Button className="btn-icon btn-neutral" color="twitter">
                        <i className="fab fa-twitter" />
                      </Button>
                    </Col>
                    <Col md="3" sm="4">
                      <p className="category"> </p>
                      <Button className="btn-neutral" color="twitter">
                        <i className="fab fa-twitter" /> Connect with Twitter
                      </Button>
                    </Col>
                  </Row>
                  <Row>
                    <Col md="4" sm="5">
                      <Button color="facebook">
                        <i className="fab fa-facebook-square" /> Share · 2.2k
                      </Button>
                    </Col>
                    <Col md="1" sm="1">
                      <Button className="btn-icon" color="facebook">
                        <i className="fab fa-facebook-f" />
                      </Button>
                    </Col>
                    <Col md="1" sm="1">
                      <Button className="btn-icon btn-round" color="facebook">
                        <i className="fab fa-facebook-f" />
                      </Button>
                    </Col>
                    <Col md="1" sm="1">
                      <Button className="btn-icon btn-neutral" color="facebook">
                        <i className="fab fa-facebook-square" />
                      </Button>
                    </Col>
                    <Col md="3" sm="4">
                      <Button className="btn-neutral" color="facebook">
                        <i className="fab fa-facebook-square" /> Share · 2.2k
                      </Button>
                    </Col>
                  </Row>
                  <Row>
                    <Col md="4" sm="5">
                      <Button color="google">
                        <i className="fab fa-google-plus-g" /> Share on Google+
                      </Button>
                    </Col>
                    <Col md="1" sm="1">
                      <Button className="btn-icon" color="google">
                        <i className="fab fa-google-plus-g" />
                      </Button>
                    </Col>
                    <Col md="1" sm="1">
                      <Button className="btn-icon btn-round" color="google">
                        <i className="fab fa-google-plus-g" />
                      </Button>
                    </Col>
                    <Col md="1" sm="1">
                      <Button className="btn-icon btn-neutral" color="google">
                        <i className="fab fa-google-plus-g" />
                      </Button>
                    </Col>
                    <Col md="3" sm="4">
                      <Button className="btn-neutral" color="google">
                        <i className="fab fa-google-plus-g" /> Share on Google+
                      </Button>
                    </Col>
                  </Row>
                  <Row>
                    <Col md="4" sm="5">
                      <Button color="linkedin">
                        <i className="fab fa-linkedin" /> Connect with Linkedin
                      </Button>
                    </Col>
                    <Col md="1" sm="1">
                      <Button className="btn-icon" color="linkedin">
                        <i className="fab fa-linkedin" />
                      </Button>
                    </Col>
                    <Col md="1" sm="1">
                      <Button className="btn-icon btn-round" color="linkedin">
                        <i className="fab fa-linkedin" />
                      </Button>
                    </Col>
                    <Col md="1" sm="1">
                      <Button className="btn-icon btn-neutral" color="linkedin">
                        <i className="fab fa-linkedin" />
                      </Button>
                    </Col>
                    <Col md="3" sm="4">
                      <Button className="btn-neutral" color="linkedin">
                        <i className="fab fa-linkedin" /> Connect with Linkedin
                      </Button>
                    </Col>
                  </Row>
                  <Row>
                    <Col md="4" sm="5">
                      <Button color="pinterest">
                        <i className="fab fa-pinterest" /> Pint it · 212
                      </Button>
                    </Col>
                    <Col md="1" sm="1">
                      <Button className="btn-icon" color="pinterest">
                        <i className="fab fa-pinterest" />
                      </Button>
                    </Col>
                    <Col md="1" sm="1">
                      <Button className="btn-icon btn-round" color="pinterest">
                        <i className="fab fa-pinterest" />
                      </Button>
                    </Col>
                    <Col md="1" sm="1">
                      <Button
                        className="btn-icon btn-neutral"
                        color="pinterest"
                      >
                        <i className="fab fa-pinterest" />
                      </Button>
                    </Col>
                    <Col md="3" sm="4">
                      <Button className="btn-neutral" color="pinterest">
                        <i className="fab fa-pinterest" /> Pint it · 212
                      </Button>
                    </Col>
                  </Row>
                  <Row>
                    <Col md="4" sm="5">
                      <Button color="youtube">
                        <i className="fab fa-youtube" /> View on Youtube
                      </Button>
                    </Col>
                    <Col md="1" sm="1">
                      <Button className="btn-icon" color="youtube">
                        <i className="fab fa-youtube" />
                      </Button>
                    </Col>
                    <Col md="1" sm="1">
                      <Button className="btn-icon btn-round" color="youtube">
                        <i className="fab fa-youtube" />
                      </Button>
                    </Col>
                    <Col md="1" sm="1">
                      <Button className="btn-icon btn-neutral" color="youtube">
                        <i className="fab fa-youtube" />
                      </Button>
                    </Col>
                    <Col md="3" sm="4">
                      <Button className="btn-neutral" color="youtube">
                        <i className="fab fa-youtube" /> View on Youtube
                      </Button>
                    </Col>
                  </Row>
                  <Row>
                    <Col md="4" sm="5">
                      <Button color="tumblr">
                        <i className="fab fa-tumblr-square" /> Repost
                      </Button>
                    </Col>
                    <Col md="1" sm="1">
                      <Button className="btn-icon" color="tumblr">
                        <i className="fab fa-tumblr" />
                      </Button>
                    </Col>
                    <Col md="1" sm="1">
                      <Button className="btn-icon btn-round" color="tumblr">
                        <i className="fab fa-tumblr" />
                      </Button>
                    </Col>
                    <Col md="1" sm="1">
                      <Button className="btn-icon btn-neutral" color="tumblr">
                        <i className="fab fa-tumblr-square" />
                      </Button>
                    </Col>
                    <Col md="3" sm="4">
                      <Button className="btn-neutral" color="tumblr">
                        <i className="fab fa-tumblr-square" /> Repost
                      </Button>
                    </Col>
                  </Row>
                  <Row>
                    <Col md="4" sm="5">
                      <Button color="github">
                        <i className="fab fa-github" /> Connect with Github
                      </Button>
                    </Col>
                    <Col md="1" sm="1">
                      <Button className="btn-icon" color="github">
                        <i className="fab fa-github" />
                      </Button>
                    </Col>
                    <Col md="1" sm="1">
                      <Button className="btn-icon btn-round" color="github">
                        <i className="fab fa-github" />
                      </Button>
                    </Col>
                    <Col md="1" sm="1">
                      <Button className="btn-icon btn-neutral" color="github">
                        <i className="fab fa-github" />
                      </Button>
                    </Col>
                    <Col md="3" sm="4">
                      <Button className="btn-neutral" color="github">
                        <i className="fab fa-github" /> Connect with Github
                      </Button>
                    </Col>
                  </Row>
                  <Row>
                    <Col md="4" sm="5">
                      <Button color="behance">
                        <i className="fab fa-behance-square" /> Follow us
                      </Button>
                    </Col>
                    <Col md="1" sm="1">
                      <Button className="btn-icon" color="behance">
                        <i className="fab fa-behance" />
                      </Button>
                    </Col>
                    <Col md="1" sm="1">
                      <Button className="btn-icon btn-round" color="behance">
                        <i className="fab fa-behance" />
                      </Button>
                    </Col>
                    <Col md="1" sm="1">
                      <Button className="btn-icon btn-neutral" color="behance">
                        <i className="fab fa-behance" />
                      </Button>
                    </Col>
                    <Col md="3" sm="4">
                      <Button className="btn-neutral" color="behance">
                        <i className="fab fa-behance-square" /> Follow us
                      </Button>
                    </Col>
                  </Row>
                  <Row>
                    <Col md="4" sm="5">
                      <Button color="dribbble">
                        <i className="fab fa-dribbble" /> Find us on Dribble
                      </Button>
                    </Col>
                    <Col md="1" sm="1">
                      <Button className="btn-icon" color="dribbble">
                        <i className="fab fa-dribbble" />
                      </Button>
                    </Col>
                    <Col md="1" sm="1">
                      <Button className="btn-icon btn-round" color="dribbble">
                        <i className="fab fa-dribbble" />
                      </Button>
                    </Col>
                    <Col md="1" sm="1">
                      <Button className="btn-icon btn-neutral" color="dribbble">
                        <i className="fab fa-dribbble" />
                      </Button>
                    </Col>
                    <Col md="3" sm="4">
                      <Button className="btn-neutral" color="dribbble">
                        <i className="fab fa-dribbble" /> Find us on Dribble
                      </Button>
                    </Col>
                  </Row>
                  <Row>
                    <Col md="4" sm="5">
                      <Button color="reddit">
                        <i className="fab fa-reddit" /> Repost · 232
                      </Button>
                    </Col>
                    <Col md="1" sm="1">
                      <Button className="btn-icon" color="reddit">
                        <i className="fab fa-reddit" />
                      </Button>
                    </Col>
                    <Col md="1" sm="1">
                      <Button className="btn-icon btn-round" color="reddit">
                        <i className="fab fa-reddit" />
                      </Button>
                    </Col>
                    <Col md="1" sm="1">
                      <Button className="btn-icon btn-neutral" color="reddit">
                        <i className="fab fa-reddit" />
                      </Button>
                    </Col>
                    <Col md="3" sm="4">
                      <Button className="btn-neutral" color="reddit">
                        <i className="fab fa-reddit" /> Repost · 232
                      </Button>
                    </Col>
                  </Row>
                </CardBody>
              </Col>
            </Row>
          </Card>
        </div>
      </>
    );
  }
}

export default Buttons;

// vue-now-ui-dashboard-pro/src/pages/Dashboard/Components/Buttons.vue
<template>
  <div class="row">
    <div class="col-md-12">
      <div class="card">
        <div class="row">
          <div class="col-md-6">
            <div class="card-header">
              <h4 class="card-title">Pick your Color</h4>
            </div>
            <div class="card-body">
              <n-button>Default</n-button>
              <n-button type="primary">Primary</n-button>
              <n-button type="info">Info</n-button>
              <n-button type="success">Success</n-button>
              <n-button type="warning">Warning</n-button>
              <n-button type="danger">Danger</n-button>
            </div>
          </div>
          <div class="col-md-6">
            <div class="card-header">
              <h4 class="card-title">Buttons with Label</h4>
            </div>
            <div class="card-body">
              <n-button>
                <i slot="label" class="now-ui-icons arrows-1_minimal-left"></i>
                Left
              </n-button>

              <n-button>
                Right
                <i slot="labelRight" class="now-ui-icons arrows-1_minimal-right"></i>
              </n-button>

              <n-button type="info">
                <i slot="label" class="now-ui-icons travel_info"></i>
                Info
              </n-button>

              <n-button type="success">
                <i slot="label" class="now-ui-icons ui-1_check"></i>
                Success
              </n-button>

              <n-button type="warning">
                <i slot="label" class="now-ui-icons ui-2_time-alarm"></i>
                Warning
              </n-button>

              <n-button type="danger">
                <i slot="label" class="now-ui-icons ui-1_simple-remove"></i>
                Danger
              </n-button>
            </div>
          </div>


        </div>

        <div class="row">
          <div class="col-md-6">
            <div class="card-header">
              <h4 class="card-title">Pick your Size</h4>
            </div>
            <div class="card-body">
              <n-button type="primary" size="sm">Small</n-button>
              <n-button type="primary">Regular</n-button>
              <n-button type="primary" size="lg">Large</n-button>
            </div>
          </div>
          <div class="col-md-6">
            <div class="card-header">
              <h4 class="card-title">Pick your Style</h4>
            </div>
            <div class="card-body">
              <n-button type="primary">Default</n-button>
              <n-button type="primary" round>round</n-button>
              <n-button type="primary" round>
                <i slot="label" class="now-ui-icons ui-2_favourite-28"></i>
                with icon
              </n-button>
              <n-button type="primary" round icon>
                <i class="now-ui-icons ui-2_favourite-28"></i>
              </n-button>
              <n-button type="primary" simple>Simple</n-button>
            </div>

          </div>
        </div>


        <div class="row">
          <div class="col-md-6">
            <div class="card-header">
              <h4 class="card-title">Pagination</h4>
            </div>

            <div class="card-body">
              <n-pagination :page-count="10" v-model="defaultPagination"></n-pagination>
              <n-pagination :page-count="10" v-model="infoPagination"></n-pagination>
            </div>
          </div>

          <div class="col-md-6">
            <div class="card-header">
              <h4 class="card-title">Button Group</h4>
            </div>
            <div class="card-body">
              <div class="btn-group">
                <button type="button" class="btn btn-info btn-outline">Left</button>
                <button type="button" class="btn btn-info btn-outline">Middle</button>
                <button type="button" class="btn btn-info btn-outline">Right</button>
              </div>

              <br><br>
              <div class="btn-group">
                <button type="button" class="btn btn-info btn-outline">1</button>
                <button type="button" class="btn btn-info btn-outline">2</button>
                <button type="button" class="btn btn-info btn-outline">3</button>
                <button type="button" class="btn btn-info btn-outline">4</button>
              </div>
              <div class="btn-group">
                <button type="button" class="btn btn-info btn-round btn-outline">5</button>
                <button type="button" class="btn btn-info btn-round btn-outline">6</button>
                <button type="button" class="btn btn-info btn-round btn-outline">7</button>
              </div>
            </div>
          </div>

        </div>


        <div class="card-header">
          <h4 class="card-title">Social buttons</h4>
        </div>

        <div class="card-body">
          <div class="row">
            <div class="col-md-4 col-sm-5">
              <p class="category">
                Default
              </p>
              <n-button class="btn-twitter">
                <i class="fa fa-twitter"></i> Connect with Twitter
              </n-button>
              <br>
              <n-button class="btn-facebook">
                <i class="fa fa-facebook-square"></i> Share · 2.2k
              </n-button>
              <br>
              <n-button class="btn-google">
                <i class="fa fa-google-plus-square"></i> Share on Google+
              </n-button>
              <br>
              <n-button class="btn-linkedin">
                <i class="fa fa-linkedin-square"></i> Connect with Linkedin
              </n-button>
              <br>
              <n-button class="btn-pinterest">
                <i class="fa fa-pinterest"></i> Pint it · 212
              </n-button>
              <br>
              <n-button class="btn-youtube">
                <i class="fa fa-youtube-play"></i> View on Youtube
              </n-button>
              <br>
              <n-button class="btn-tumblr">
                <i class="fa fa-tumblr-square"></i> Repost
              </n-button>
              <br>
              <n-button class="btn-github">
                <i class="fa fa-github"></i> Connect with Github
              </n-button>
              <br>
              <n-button class="btn-behance">
                <i class="fa fa-behance-square"></i> Follow us
              </n-button>
              <br>
              <n-button class="btn-dribbble">
                <i class="fa fa-dribbble"></i> Find us on Dribbble
              </n-button>
              <br>
              <n-button class="btn-reddit">
                <i class="fa fa-reddit"></i> Repost · 232
              </n-button>
              <br>
              <n-button class="btn-stumbleupon">
                <i class="fa fa-stumbleupon"></i> View on StumbleUpon
              </n-button>
              <br>
            </div>

            <div class="col-md-1 col-sm-1">
              <p class="category">&nbsp;</p>
              <n-button class="btn-twitter" social icon>
                <i class="fa fa-twitter"></i>
              </n-button>
              <br>
              <n-button class="btn-facebook" social icon>
                <i class="fa fa-facebook"> </i>
              </n-button>
              <br>
              <n-button class="btn-google" social icon>
                <i class="fa fa-google-plus"> </i>
              </n-button>
              <br>
              <n-button class="btn-linkedin" social icon>
                <i class="fa fa-linkedin"></i>
              </n-button>
              <br>
              <n-button class="btn-pinterest" social icon>
                <i class="fa fa-pinterest"></i>
              </n-button>
              <br>
              <n-button class="btn-youtube" social icon>
                <i class="fa fa-youtube"> </i>
              </n-button>
              <br>
              <n-button class="btn-tumblr" social icon>
                <i class="fa fa-tumblr"> </i>
              </n-button>
              <br>
              <n-button class="btn-github" social icon>
                <i class="fa fa-github"></i>
              </n-button>
              <br>
              <n-button class="btn-behance" social icon>
                <i class="fa fa-behance"></i>
              </n-button>
              <br>
              <n-button class="btn-dribbble" social icon>
                <i class="fa fa-dribbble"></i>
              </n-button>
              <br>
              <n-button class="btn-reddit" social icon>
                <i class="fa fa-reddit"></i>
              </n-button>
              <br>
              <n-button class="btn-stumbleupon" social icon>
                <i class="fa fa-stumbleupon"></i>
              </n-button>
              <br>
            </div>
            <div class="col-md-1 col-sm-1">
              <p class="category">&nbsp;</p>
              <n-button class="btn-twitter" social icon round>
                <i class="fa fa-twitter"></i>
              </n-button>
              <br>
              <n-button class="btn-facebook" social icon round>
                <i class="fa fa-facebook"> </i>
              </n-button>
              <br>
              <n-button class="btn-google" social icon round>
                <i class="fa fa-google-plus"> </i>
              </n-button>
              <br>
              <n-button class="btn-linkedin" social icon round>
                <i class="fa fa-linkedin"></i>
              </n-button>
              <br>
              <n-button class="btn-pinterest" social icon round>
                <i class="fa fa-pinterest"></i>
              </n-button>
              <br>
              <n-button class="btn-youtube" social icon round>
                <i class="fa fa-youtube"> </i>
              </n-button>
              <br>
              <n-button class="btn-tumblr" social icon round>
                <i class="fa fa-tumblr"> </i>
              </n-button>
              <br>
              <n-button class="btn-github" social icon round>
                <i class="fa fa-github"></i>
              </n-button>
              <br>
              <n-button class="btn-behance" social icon round>
                <i class="fa fa-behance"></i>
              </n-button>
              <br>
              <n-button class="btn-dribbble" social icon round>
                <i class="fa fa-dribbble"></i>
              </n-button>
              <br>
              <n-button class="btn-reddit" social icon round>
                <i class="fa fa-reddit"></i>
              </n-button>
              <br>
              <n-button class="btn-stumbleupon" social icon round>
                <i class="fa fa-stumbleupon"></i>
              </n-button>
              <br>

            </div>
            <div class="col-md-1 col-sm-1">
              <p class="category">Neutral</p>
              <n-button class="btn-twitter" type="neutral" social>
                <i class="fa fa-twitter"></i>
              </n-button>
              <br>
              <n-button class="btn-facebook" type="neutral" social>
                <i class="fa fa-facebook"> </i>
              </n-button>
              <br>
              <n-button class="btn-google" type="neutral" social>
                <i class="fa fa-google-plus"> </i>
              </n-button>
              <br>
              <n-button class="btn-linkedin" type="neutral" social>
                <i class="fa fa-linkedin"></i>
              </n-button>
              <br>
              <n-button class="btn-pinterest" type="neutral" social>
                <i class="fa fa-pinterest"></i>
              </n-button>
              <br>
              <n-button class="btn-youtube" type="neutral" social>
                <i class="fa fa-youtube"> </i>
              </n-button>
              <br>
              <n-button class="btn-tumblr" type="neutral" social>
                <i class="fa fa-tumblr"> </i>
              </n-button>
              <br>
              <n-button class="btn-github" type="neutral" social>
                <i class="fa fa-github"></i>
              </n-button>
              <br>
              <n-button class="btn-behance" type="neutral" social>
                <i class="fa fa-behance"></i>
              </n-button>
              <br>
              <n-button class="btn-dribbble" type="neutral" social>
                <i class="fa fa-dribbble"></i>
              </n-button>
              <br>
              <n-button class="btn-reddit" type="neutral" social>
                <i class="fa fa-reddit"></i>
              </n-button>
              <br>
              <n-button class="btn-stumbleupon" type="neutral" social>
                <i class="fa fa-stumbleupon"></i>
              </n-button>
              <br>

            </div>
            <div class="col-md-3 col-sm-4">
              <p class="category">&nbsp;</p>
              <n-button class="btn-twitter" type="neutral">
                <i class="fa fa-twitter"></i> Connect with Twitter
              </n-button>
              <br>
              <n-button class="btn-facebook" type="neutral">
                <i class="fa fa-facebook-square"></i> Share · 2.2k
              </n-button>
              <br>
              <n-button class="btn-google" type="neutral">
                <i class="fa fa-google-plus-square"></i> Share on Google+
              </n-button>
              <br>
              <n-button class="btn-linkedin" type="neutral">
                <i class="fa fa-linkedin-square"></i> Connect with Linkedin
              </n-button>
              <br>
              <n-button class="btn-pinterest" type="neutral">
                <i class="fa fa-pinterest"></i> Pint it · 212
              </n-button>
              <br>
              <n-button class="btn-youtube" type="neutral">
                <i class="fa fa-youtube-play"></i> View on Youtube
              </n-button>
              <br>
              <n-button class="btn-tumblr" type="neutral">
                <i class="fa fa-tumblr-square"></i> Repost
              </n-button>
              <br>
              <n-button class="btn-github" type="neutral">
                <i class="fa fa-github"></i> Connect with Github
              </n-button>
              <br>
              <n-button class="btn-behance" type="neutral">
                <i class="fa fa-behance-square"></i> Follow us
              </n-button>
              <br>
              <n-button class="btn-dribbble" type="neutral">
                <i class="fa fa-dribbble"></i> Find us on Dribbble
              </n-button>
              <br>
              <n-button class="btn-reddit" type="neutral">
                <i class="fa fa-reddit"></i> Repost · 232
              </n-button>
              <br>
              <n-button class="btn-stumbleupon" type="neutral">
                <i class="fa fa-stumbleupon"></i> View on StumbleUpon
              </n-button>
              <br>

            </div>
          </div>
        </div>

      </div>
    </div>
  </div>
</template>
<script>
import { Pagination } from 'src/components';

export default {
  components: {
    [Pagination.name]: Pagination
  },
  data() {
    return {
      defaultPagination: 1,
      infoPagination: 3
    };
  }
};
</script>
<style>
</style>
