// now-ui-dashboard-pro-angular-v1/src/app/components/image-upload/image-upload.component.ts
import { Component, OnInit, Input, ViewChild, ElementRef } from "@angular/core";

@Component({
  selector: "app-image-upload",
  templateUrl: "./image-upload.component.html",
  styleUrls: ["./image-upload.component.scss"]
})
export class ImageUploadComponent implements OnInit {
  @Input() isRound: boolean = false;
  @Input() image: string;
  state: any = {};
  @ViewChild("input") input: ElementRef;
  constructor() {
    this.handleImageChange = this.handleImageChange.bind(this);
    this.handleSubmit = this.handleSubmit.bind(this);
    this.handleClick = this.handleClick.bind(this);
    this.handleRemove = this.handleRemove.bind(this);
  }

  ngOnInit() {
    this.state = {
      file: null,
      imagePreviewUrl:
        this.image !== undefined
          ? this.image
          : this.isRound
          ? "assets/img/placeholder.jpg"
          : "assets/img/image_placeholder.jpg"
    };
  }
  ngAfterViewInit() {
    this.input.nativeElement.children[2].onchange = this.handleImageChange;
  }
  handleImageChange(e) {
    e.preventDefault();
    let reader = new FileReader();
    let file = e.target.files[0];
    reader.onloadend = () => {
      this.state.file = file;
      this.state.imagePreviewUrl = reader.result;
      // this.state.imagePreviewUrl1 = reader.result;
    };
    reader.readAsDataURL(file);
  }
  handleSubmit(e) {
    e.preventDefault();
    // this.state.file is the file/image uploaded
    // in this function you can save the image (this.state.file) on form submit
    // you have to call it yourself
  }
  handleClick() {
    this.input.nativeElement.children[2].click();
  }
  handleRemove() {
    this.state.file = null;
    this.state.imagePreviewUrl =
      this.image !== undefined
        ? this.image
        : this.isRound
        ? "assets/img/placeholder.jpg"
        : "assets/img/image_placeholder.jpg";
  }
}

<div class="fileinput text-center" #input>
  <div [ngClass]="{ 'img-circle': isRound }" class="thumbnail img-raised">
    <img src="{{ state.imagePreviewUrl }}" alt="..." />
  </div>
  <div>
    <button
      class="btn btn-raised btn-round btn-default btn-file"
      (click)="handleClick()"
      *ngIf="!this.state.file"
    >
      Select image
    </button>
    <button
      class="btn btn-raised btn-round btn-default btn-file"
      (click)="handleClick()"
      *ngIf="this.state.file"
    >
      Change
    </button>
    <button
      class="btn btn-danger btn-round fileinput-exists"
      (click)="handleRemove()"
      *ngIf="this.state.file"
    >
      <i class="now-ui-icons ui-1_simple-remove"></i> Remove
    </button>
  </div>
  <input type="file" />
</div>

// react-now-ui-dashboard/src/components/CustomUpload/ImageUpload.jsx
/*!

=========================================================
* Now UI Dashboard PRO React - v1.3.0
=========================================================

* Product Page: https://www.creative-tim.com/product/now-ui-dashboard-pro-react
* Copyright 2019 Creative Tim (https://www.creative-tim.com)

* Coded by Creative Tim

=========================================================

* The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

*/
import React from "react";
// used for making the prop types of this component
import PropTypes from "prop-types";

// reactstrap components
import { Button } from "reactstrap";

// core components
import defaultImage from "assets/img/image_placeholder.jpg";
import defaultAvatar from "assets/img/placeholder.jpg";

class ImageUpload extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      file: null,
      imagePreviewUrl: this.props.avatar ? defaultAvatar : defaultImage
    };
    this.fileInput = React.createRef();
  }
  handleImageChange = e => {
    e.preventDefault();
    let reader = new FileReader();
    let file = e.target.files[0];
    reader.onloadend = () => {
      this.setState({
        file: file,
        imagePreviewUrl: reader.result
      });
    };
    reader.readAsDataURL(file);
  };
  handleSubmit = e => {
    e.preventDefault();
    // this.state.file is the file/image uploaded
    // in this function you can save the image (this.state.file) on form submit
    // you have to call it yourself
  };
  handleClick = () => {
    this.fileInput.current.click();
  };
  handleRemove = () => {
    this.setState({
      file: null,
      imagePreviewUrl: this.props.avatar ? defaultAvatar : defaultImage
    });
    this.fileInput.current.value = null;
  };
  render() {
    return (
      <div className="fileinput text-center">
        <input
          type="file"
          onChange={this.handleImageChange}
          ref={this.fileInput}
        />
        <div className={"thumbnail" + (this.props.avatar ? " img-circle" : "")}>
          <img src={this.state.imagePreviewUrl} alt="..." />
        </div>
        <div>
          {this.state.file === null ? (
            <Button className="btn-round" onClick={() => this.handleClick()}>
              {this.props.avatar ? "Add Photo" : "Select image"}
            </Button>
          ) : (
            <span>
              <Button className="btn-round" onClick={() => this.handleClick()}>
                Change
              </Button>
              {this.props.avatar ? <br /> : null}
              <Button
                color="danger"
                className="btn-round"
                onClick={() => this.handleRemove()}
              >
                <i className="fa fa-times" /> Remove
              </Button>
            </span>
          )}
        </div>
      </div>
    );
  }
}

ImageUpload.propTypes = {
  avatar: PropTypes.bool
};

export default ImageUpload;
