// black-dashboard-pro-react-v1/src/views/forms/ExtendedForms.jsx
/*!

=========================================================
* Black Dashboard PRO React - v1.0.0
=========================================================

* Product Page: https://www.creative-tim.com/product/black-dashboard-pro-react
* Copyright 2019 Creative Tim (https://www.creative-tim.com)

* Coded by Creative Tim

=========================================================

* The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

*/
import React from "react";
// react plugin used to create datetimepicker
import ReactDatetime from "react-datetime";
// react plugin that creates an input with badges
import TagsInput from "react-tagsinput";
// react plugin used to create DropdownMenu for selecting items
import Select from "react-select";
// react plugin used to create switch buttons
import Switch from "react-bootstrap-switch";
// plugin that creates slider
import Slider from "nouislider";

// reactstrap components
import {
  Card,
  CardHeader,
  CardBody,
  CardTitle,
  DropdownToggle,
  DropdownMenu,
  DropdownItem,
  UncontrolledDropdown,
  FormGroup,
  Progress,
  Row,
  Col
} from "reactstrap";

// core components
import ImageUpload from "components/CustomUpload/ImageUpload.jsx";

class ExtendedForms extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      singleSelect: null,
      multipleSelect: null,
      tagsinput: ["Amsterdam", "Washington", "Sydney", "Beijing"]
    };
  }
  componentDidMount() {
    var slider1 = this.refs.slider1;
    var slider2 = this.refs.slider2;
    Slider.create(slider1, {
      start: [40],
      connect: [true, false],
      step: 1,
      range: { min: 0, max: 100 }
    });
    Slider.create(slider2, {
      start: [20, 60],
      connect: [false, true, false],
      step: 1,
      range: { min: 0, max: 100 }
    });
  }
  handleTagsinput = tagsinput => {
    this.setState({ tagsinput });
  };
  render() {
    return (
      <>
        <div className="content">
          <Row>
            <Col md="4">
              <Card>
                <CardHeader>
                  <CardTitle tag="h4">Date-Time-Picker</CardTitle>
                </CardHeader>
                <CardBody>
                  <FormGroup>
                    <ReactDatetime
                      inputProps={{
                        className: "form-control",
                        placeholder: "Datetime Picker Here"
                      }}
                    />
                  </FormGroup>
                </CardBody>
              </Card>
            </Col>
            <Col md="4">
              <Card>
                <CardHeader>
                  <CardTitle tag="h4">Date Picker</CardTitle>
                </CardHeader>
                <CardBody>
                  <FormGroup>
                    <ReactDatetime
                      inputProps={{
                        className: "form-control",
                        placeholder: "Date Picker Here"
                      }}
                      timeFormat={false}
                    />
                  </FormGroup>
                </CardBody>
              </Card>
            </Col>
            <Col md="4">
              <Card>
                <CardHeader>
                  <CardTitle tag="h4">Time Picker</CardTitle>
                </CardHeader>
                <CardBody>
                  <FormGroup>
                    <ReactDatetime
                      dateFormat={false}
                      inputProps={{
                        className: "form-control",
                        placeholder: "Time Picker Here"
                      }}
                    />
                  </FormGroup>
                </CardBody>
              </Card>
            </Col>
          </Row>
          <Row>
            <Col md="12">
              <Card>
                <CardBody>
                  <Row>
                    <Col className="mb-4" md="6">
                      <CardTitle tag="h4">Toggle Buttons</CardTitle>
                      <Row className="mb-3">
                        <Col md="4">
                          <p className="category">Default</p>
                          <Switch offColor="" onColor="" />{" "}
                          <Switch defaultValue={false} offColor="" onColor="" />
                        </Col>
                        <Col md="4">
                          <p className="category">Plain</p>
                          <Switch
                            offColor=""
                            offText=""
                            onColor=""
                            onText=""
                          />{" "}
                          <Switch
                            defaultValue={false}
                            offColor=""
                            offText=""
                            onColor=""
                            onText=""
                          />
                        </Col>
                        <Col md="4">
                          <p className="category">With Icons</p>
                          <Switch
                            offColor=""
                            offText={
                              <i className="tim-icons icon-simple-remove" />
                            }
                            onColor=""
                            onText={<i className="tim-icons icon-check-2" />}
                          />{" "}
                          <Switch
                            defaultValue={false}
                            offColor=""
                            offText={
                              <i className="tim-icons icon-simple-remove" />
                            }
                            onColor=""
                            onText={<i className="tim-icons icon-check-2" />}
                          />
                        </Col>
                      </Row>
                    </Col>
                    <Col className="mb-4" md="6">
                      <CardTitle tag="h4">Customisable Select</CardTitle>
                      <Row>
                        <Col lg="5" md="6" sm="3">
                          <Select
                            className="react-select info"
                            classNamePrefix="react-select"
                            name="singleSelect"
                            value={this.state.singleSelect}
                            onChange={value =>
                              this.setState({ singleSelect: value })
                            }
                            options={[
                              {
                                value: "",
                                label: "Single Option",
                                isDisabled: true
                              },
                              { value: "2", label: "Foobar" },
                              { value: "3", label: "Is great" }
                            ]}
                            placeholder="Single Select"
                          />
                        </Col>
                        <Col lg="5" md="6" sm="3">
                          <Select
                            className="react-select info"
                            classNamePrefix="react-select"
                            placeholder="Choose City"
                            name="multipleSelect"
                            closeMenuOnSelect={false}
                            isMulti
                            value={this.state.multipleSelect}
                            onChange={value =>
                              this.setState({ multipleSelect: value })
                            }
                            options={[
                              {
                                value: "",
                                label: " Multiple Options",
                                isDisabled: true
                              },
                              { value: "2", label: "Paris " },
                              { value: "3", label: "Bucharest" },
                              { value: "4", label: "Rome" },
                              { value: "5", label: "New York" },
                              { value: "6", label: "Miami " },
                              { value: "7", label: "Piatra Neamt" },
                              { value: "8", label: "Paris " },
                              { value: "9", label: "Bucharest" },
                              { value: "10", label: "Rome" },
                              { value: "11", label: "New York" },
                              { value: "12", label: "Miami " },
                              { value: "13", label: "Piatra Neamt" },
                              { value: "14", label: "Paris " },
                              { value: "15", label: "Bucharest" },
                              { value: "16", label: "Rome" },
                              { value: "17", label: "New York" },
                              { value: "18", label: "Miami " },
                              { value: "19", label: "Piatra Neamt" }
                            ]}
                          />
                        </Col>
                      </Row>
                    </Col>
                  </Row>
                  <Row>
                    <Col className="mb-4" md="6">
                      <CardTitle tag="h4">Tags</CardTitle>
                      <TagsInput
                        onChange={this.handleTagsinput}
                        tagProps={{ className: "react-tagsinput-tag danger" }}
                        value={this.state.tagsinput}
                      />
                    </Col>
                    <Col md="6">
                      <CardTitle tag="h4">Dropdown &amp; Dropup</CardTitle>
                      <Row>
                        <Col lg="4" md="6" sm="3">
                          <UncontrolledDropdown>
                            <DropdownToggle
                              aria-expanded={false}
                              aria-haspopup={true}
                              caret
                              className="btn-block"
                              color="primary"
                              data-toggle="dropdown"
                              id="dropdownMenuButton"
                              type="button"
                            >
                              Dropdown
                            </DropdownToggle>
                            <DropdownMenu aria-labelledby="dropdownMenuButton">
                              <DropdownItem header>
                                Dropdown header
                              </DropdownItem>
                              <DropdownItem
                                href="#pablo"
                                onClick={e => e.preventDefault()}
                              >
                                Action
                              </DropdownItem>
                              <DropdownItem
                                href="#pablo"
                                onClick={e => e.preventDefault()}
                              >
                                Another action
                              </DropdownItem>
                              <DropdownItem
                                href="#pablo"
                                onClick={e => e.preventDefault()}
                              >
                                Something else here
                              </DropdownItem>
                            </DropdownMenu>
                          </UncontrolledDropdown>
                        </Col>
                        <Col lg="4" md="6" sm="3">
                          <UncontrolledDropdown direction="up">
                            <DropdownToggle
                              caret
                              className="btn-block"
                              color="primary"
                              data-toggle="dropdown"
                              type="button"
                            >
                              Dropup
                            </DropdownToggle>
                            <DropdownMenu>
                              <DropdownItem header>
                                Dropdown header
                              </DropdownItem>
                              <DropdownItem
                                href="#pablo"
                                onClick={e => e.preventDefault()}
                              >
                                Action
                              </DropdownItem>
                              <DropdownItem
                                href="#pablo"
                                onClick={e => e.preventDefault()}
                              >
                                Another action
                              </DropdownItem>
                              <DropdownItem
                                href="#pablo"
                                onClick={e => e.preventDefault()}
                              >
                                Something else here
                              </DropdownItem>
                            </DropdownMenu>
                          </UncontrolledDropdown>
                        </Col>
                      </Row>
                    </Col>
                  </Row>
                  <Row>
                    <Col className="mb-4" md="6">
                      <CardTitle tag="h4">Progress Bars</CardTitle>
                      <div className="progress-container">
                        <span className="progress-badge">Default</span>
                        <Progress max="100" value="25">
                          <span className="progress-value">25%</span>
                        </Progress>
                      </div>
                      <div className="progress-container progress-primary">
                        <span className="progress-badge">Primary</span>
                        <Progress max="100" value="60">
                          <span className="progress-value">60%</span>
                        </Progress>
                      </div>
                    </Col>
                    <Col md="6">
                      <CardTitle className="mt-3" tag="h4">
                        Sliders
                      </CardTitle>
                      <div className="slider" ref="slider1" />
                      <br />
                      <div
                        className="slider slider-primary mb-3"
                        ref="slider2"
                      />
                    </Col>
                  </Row>
                  <Row>
                    <Col md="4" sm="4">
                      <CardTitle tag="h4">Regular Image</CardTitle>
                      <ImageUpload
                        addBtnColor="default"
                        changeBtnColor="default"
                      />
                    </Col>
                    <Col md="3" sm="4">
                      <CardTitle tag="h4">Avatar</CardTitle>
                      <ImageUpload
                        avatar
                        addBtnColor="default"
                        changeBtnColor="default"
                      />
                    </Col>
                  </Row>
                </CardBody>
              </Card>
              {/* end card */}
            </Col>
          </Row>
        </div>
      </>
    );
  }
}

export default ExtendedForms;

// paper-dashboard-pro-angular-v1/src/app/forms/extendedforms/extendedforms.component.ts
import { Component, OnInit } from '@angular/core';

declare var require: any
declare var $:any;

@Component({
    moduleId: module.id,
    selector: 'extendedforms-cmp',
    templateUrl: 'extendedforms.component.html'
})

export class ExtendedFormsComponent implements OnInit{
    state_default: boolean = true;
    state_plain: boolean = true;
    state_with_icons: boolean = true;
    tagItems = ['Amsterdam', 'Washington', 'Sydney', 'Beijing'];
    model: Date;
    model2: Date;
    ngOnInit() {
      this.model = new Date();
      this.model2 = new Date();
        //  Activate the tooltips
        $('[rel="tooltip"]').tooltip();

        var tagClass = $('.tagsinput').data('color');

        if ($(".tagsinput").length != 0) {
          $('.tagsinput').tagsinput();
        }

        $('.bootstrap-tagsinput').addClass('' + tagClass + '-badge');

        //  Init Bootstrap Select Picker
        if ($(".selectpicker").length != 0) {
          $(".selectpicker").selectpicker({
            iconBase: "nc-icon",
            tickIcon: "nc-check-2"
          });
        }

        if ($(".datetimepicker").length != 0) {
          $('.datetimepicker').datetimepicker({
            icons: {
              time: "fa fa-clock-o",
              date: "fa fa-calendar",
              up: "fa fa-chevron-up",
              down: "fa fa-chevron-down",
              previous: 'fa fa-chevron-left',
              next: 'fa fa-chevron-right',
              today: 'fa fa-screenshot',
              clear: 'fa fa-trash',
              close: 'fa fa-remove'
            },
            debug: true
          });
        }

        if ($(".datepicker").length != 0) {
          $('.datepicker').datetimepicker({
            format: 'MM/DD/YYYY',
            icons: {
              time: "fa fa-clock-o",
              date: "fa fa-calendar",
              up: "fa fa-chevron-up",
              down: "fa fa-chevron-down",
              previous: 'fa fa-chevron-left',
              next: 'fa fa-chevron-right',
              today: 'fa fa-screenshot',
              clear: 'fa fa-trash',
              close: 'fa fa-remove'
            },
            debug: true
          });
        }

        if ($(".timepicker").length != 0) {
          $('.timepicker').datetimepicker({
            //          format: 'H:mm',    // use this format if you want the 24hours timepicker
            format: 'h:mm A', //use this format if you want the 12hours timpiecker with AM/PM toggle
            icons: {
              time: "fa fa-clock-o",
              date: "fa fa-calendar",
              up: "fa fa-chevron-up",
              down: "fa fa-chevron-down",
              previous: 'fa fa-chevron-left',
              next: 'fa fa-chevron-right',
              today: 'fa fa-screenshot',
              clear: 'fa fa-trash',
              close: 'fa fa-remove'
            },
            debug: true
          });
        }

        var noUiSlider = require('nouislider');
        var sliderRegular = document.getElementById('sliderRegular');

        noUiSlider.create(sliderRegular, {
            start: 40,
            connect: [true,false],
            range: {
                min: 0,
                max: 100
            }
        });

        var sliderDouble = document.getElementById('sliderDouble');

        noUiSlider.create(sliderDouble, {
            start: [ 20, 60 ],
            connect: true,
            range: {
                min:  0,
                max:  100
            }
        });
    }
}

<div class="main-content">
  <div class="row">
    <div class="col-md-4">
      <div class="card ">
        <div class="card-header ">
          <h5 class="card-title">Datetimepicker</h5>
        </div>
        <div class="card-body ">
          <div class="form-group">
            <input class="form-control" placeholder="{{model2}}"
                   name="dp1" ngbDatepicker #d1="ngbDatepicker" (click)="d1.toggle()">
          </div>
        </div>
      </div>
    </div>
    <div class="col-md-4">
      <div class="card ">
        <div class="card-header ">
          <h5 class="card-title">Date Picker</h5>
        </div>
        <div class="card-body ">
          <div class="form-group">
              <input class="form-control" placeholder="{{model}}"
                     name="dp" ngbDatepicker #d="ngbDatepicker" (click)="d.toggle()">
            <!-- <input type="text" class="form-control datepicker" value="10/05/2018"> -->
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <div class="card">
        <div class="card-body">
          <div class="row">
            <div class="col-md-6">
              <h4 class="card-title">Toggle Buttons</h4>
              <div class="row">
                <div class="col-md-4">
                    <p class="category">Default</p>
                    <bSwitch
                        [switch-on-color]="'primary'"
                        [switch-off-color]="'primary'">
                    </bSwitch>
                    <bSwitch
                        [switch-on-color]="'primary'"
                        [switch-off-color]="'primary'"
                        [(ngModel)]="state_default">
                    </bSwitch>
                </div>

                <div class="col-md-4">
                    <p class="category">Plain</p>
                    <bSwitch
                        [switch-on-color]="'primary'"
                        [switch-off-color]="'primary'"
                        [switch-off-text]="' '"
                        [switch-on-text]="' '">
                    </bSwitch>
                    <bSwitch
                        [switch-on-color]="'primary'"
                        [switch-off-color]="'primary'"
                        [switch-off-text]="' '"
                        [switch-on-text]="' '"
                        [(ngModel)]="state_plain">
                    </bSwitch>
                </div>


                <div class="col-md-4">
                    <p class="category">With Icons</p>
                    <bSwitch
                        [switch-on-color]="'primary'"
                        [switch-off-color]="'primary'"
                        [switch-off-text]="'&#x2715;'"
                        [switch-on-text]="'&#x2714;'">
                    </bSwitch>
                    <bSwitch
                        [switch-on-color]="'primary'"
                        [switch-off-color]="'primary'"
                        [switch-off-text]="'&#x2715;'"
                        [switch-on-text]="'&#x2714;'"
                        [(ngModel)]="state_with_icons">
                    </bSwitch>
                </div>
              </div>
            </div>
            <div class="col-md-6">
              <h4 class="card-title">Customisable Select</h4>
              <div class="row">
                <div class="col-lg-5 col-md-6 col-sm-3">
                  <select class="selectpicker" data-size="7" data-style="btn btn-primary btn-round" title="Single Select">
                    <option disabled selected>Single Option</option>
                    <option value="2">Foobar</option>
                    <option value="3">Is great</option>
                  </select>
                </div>
                <div class="col-lg-5 col-md-6 col-sm-3">
                  <select class="selectpicker" data-style="btn btn-info btn-round" multiple title="Choose City" data-size="7">
                    <option disabled> Multiple Options</option>
                    <option value="2">Paris </option>
                    <option value="3">Bucharest</option>
                    <option value="4">Rome</option>
                    <option value="5">New York</option>
                    <option value="6">Miami </option>
                    <option value="7">Piatra Neamt</option>
                    <option value="8">Paris </option>
                    <option value="9">Bucharest</option>
                    <option value="10">Rome</option>
                    <option value="11">New York</option>
                    <option value="12">Miami </option>
                    <option value="13">Piatra Neamt</option>
                    <option value="14">Paris </option>
                    <option value="15">Bucharest</option>
                    <option value="16">Rome</option>
                    <option value="17">New York</option>
                    <option value="18">Miami </option>
                    <option value="19">Piatra Neamt</option>
                  </select>
                </div>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-md-6">
              <h4 class="card-title">Tags</h4>
              <tag-input [(ngModel)]='tagItems' theme='regular-theme'></tag-input>
            </div>
            <div class="col-md-6">
              <h4 class="card-title">Dropdown & Dropup</h4>
              <div class="row">
                <div class="col-lg-6 col-md-6 col-sm-3">
                  <div class="dropdown">
                    <button class="dropdown-toggle btn btn-primary btn-round btn-block" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      Dropdown
                    </button>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
                      <div class="dropdown-header">Dropdown header</div>
                      <a class="dropdown-item" href="javascript:void(0)">Action</a>
                      <a class="dropdown-item" href="javascript:void(0)">Another action</a>
                      <a class="dropdown-item" href="javascript:void(0)">Something else</a>
                    </div>
                  </div>
                </div>
                <div class="col-lg-6 col-md-6 col-sm-3">
                  <div class="dropup">
                    <button type="button" class="dropdown-toggle btn btn-primary btn-round btn-block" data-toggle="dropdown">
                      Dropup
                    </button>
                    <div class="dropdown-menu">
                      <div class="dropdown-header">Dropdown header</div>
                      <a class="dropdown-item" href="javascript:void(0)">Action</a>
                      <a class="dropdown-item" href="javascript:void(0)">Another action</a>
                      <a class="dropdown-item" href="javascript:void(0)">Something else here</a>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-md-6">
              <h4 class="card-title">Progress Bars</h4>
              <div class="progress">
                <div class="progress-bar" role="progressbar" style="width: 25%" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
              </div>
              <br/>
              <div class="progress">
                <div class="progress-bar progress-bar-danger" role="progressbar" style="width: 100%" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100"></div>
              </div>
              <br/>
              <div class="progress">
                <div class="progress-bar progress-bar-success" role="progressbar" style="width: 15%" aria-valuenow="15" aria-valuemin="0" aria-valuemax="100"></div>
                <div class="progress-bar progress-bar-warning" role="progressbar" style="width: 30%" aria-valuenow="30" aria-valuemin="0" aria-valuemax="100"></div>
                <div class="progress-bar progress-bar-info" role="progressbar" style="width: 20%" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100"></div>
              </div>
            </div>
            <div class="col-md-6">
              <h4 class="card-title">Sliders</h4>
              <div id="sliderRegular" class="slider slider-success"></div>
              <br>
              <div id="sliderDouble" class="slider slider-primary"></div>
            </div>
          </div>
          <div class="row">
            <div class="col-md-4 col-sm-4">
              <h4 class="card-title">Regular Image</h4>
              <div class="fileinput fileinput-new text-center" data-provides="fileinput">
                <div class="fileinput-new thumbnail">
                  <img src="./assets/img/image_placeholder.jpg" alt="...">
                </div>
                <div class="fileinput-preview fileinput-exists thumbnail"></div>
                <div>
                  <span class="btn btn-rose btn-round btn-file">
                    <span class="fileinput-new">Select image</span>
                    <span class="fileinput-exists">Change</span>
                    <input type="file" name="..." />
                  </span>
                  <a href="javascript:void(0)" class="btn btn-danger btn-round fileinput-exists" data-dismiss="fileinput"><i class="fa fa-times"></i> Remove</a>
                </div>
              </div>
            </div>
            <div class="col-md-3 col-sm-4">
              <h4 class="card-title">Avatar</h4>
              <div class="fileinput fileinput-new text-center" data-provides="fileinput">
                <div class="fileinput-new thumbnail img-circle">
                  <img src="./assets/img/placeholder.jpg" alt="...">
                </div>
                <div class="fileinput-preview fileinput-exists thumbnail img-circle"></div>
                <div>
                  <span class="btn btn-round btn-rose btn-file">
                    <span class="fileinput-new">Add Photo</span>
                    <span class="fileinput-exists">Change</span>
                    <input type="file" name="..." />
                  </span>
                  <br />
                  <a href="javascript:void(0)" class="btn btn-danger btn-round fileinput-exists" data-dismiss="fileinput"><i class="fa fa-times"></i> Remove</a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- end card -->
    </div>
  </div>
</div>
