// react-light-bootstrap-dashboard/src/views/Components/Buttons.jsx
/*!

=========================================================
* Light Bootstrap Dashboard PRO React - v1.2.0
=========================================================

* Product Page: https://www.creative-tim.com/product/light-bootstrap-dashboard-pro-react
* Copyright 2019 Creative Tim (https://www.creative-tim.com)

* Coded by Creative Tim

=========================================================

* The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

*/
import React, { Component } from "react";
import { ButtonGroup, Pagination, Grid, Row, Col } from "react-bootstrap";

import Button from "components/CustomButton/CustomButton.jsx";

class Buttons extends Component {
  render() {
    return (
      <div className="main-content buttons-with-margin">
        <Grid fluid>
          <Row>
            <Col md={12}>
              <div className="card">
                <Row>
                  <Col md={6}>
                    <div className="header">
                      <h4 className="title">Colors</h4>
                    </div>
                    <div className="content">
                      <Button bsStyle="default" fill wd>
                        Default
                      </Button>
                      <Button bsStyle="primary" fill wd>
                        Primary
                      </Button>
                      <Button bsStyle="info" fill wd>
                        Info
                      </Button>
                      <Button bsStyle="success" fill wd>
                        Success
                      </Button>
                      <Button bsStyle="warning" fill wd>
                        Warning
                      </Button>
                      <Button bsStyle="danger" fill wd>
                        Danger
                      </Button>
                    </div>
                  </Col>
                  <Col md={6}>
                    <div className="header">
                      <h4 className="title">Styles</h4>
                    </div>
                    <div className="content">
                      <Button wd>Default</Button>
                      <Button fill wd>
                        Fill
                      </Button>
                      <Button fill round wd>
                        Fill + Round
                      </Button>
                      <Button round wd>
                        Round
                      </Button>
                      <Button simple wd>
                        Simple
                      </Button>
                    </div>
                  </Col>
                </Row>
                <Row>
                  <Col md={6}>
                    <div className="header">
                      <h4 className="title">Buttons with Label</h4>
                    </div>
                    <div className="content">
                      <Button bsStyle="success" wd>
                        <span className="btn-label">
                          <i className="fa fa-check" />
                        </span>
                        Success
                      </Button>
                      <Button wd bsStyle="danger">
                        <span className="btn-label">
                          <i className="fa fa-times" />
                        </span>
                        Danger
                      </Button>
                      <Button wd bsStyle="info">
                        <span className="btn-label">
                          <i className="fa fa-exclamation" />
                        </span>
                        Info
                      </Button>
                      <Button wd bsStyle="warning">
                        <span className="btn-label">
                          <i className="fa fa-warning" />
                        </span>
                        Warning
                      </Button>
                      <Button wd bsStyle="default">
                        <span className="btn-label">
                          <i className="fa fa-arrow-left" />
                        </span>
                        Left
                      </Button>
                      <Button wd bsStyle="default">
                        Right
                        <span className="btn-label btn-label-right">
                          <i className="fa fa-arrow-right" />
                        </span>
                      </Button>
                    </div>
                  </Col>
                  <Col md={6}>
                    <div className="header">
                      <h4 className="title">Sizes</h4>
                    </div>
                    <div className="content">
                      <Button bsSize="lg" fill>
                        Large
                      </Button>
                      <Button fill>Default</Button>
                      <Button bsSize="sm" fill>
                        Small
                      </Button>
                      <Button bsSize="xs" fill>
                        X-Small
                      </Button>
                      <br />
                      <Button bsSize="lg" round fill>
                        Large
                      </Button>
                      <Button round fill>
                        Default
                      </Button>
                      <Button bsSize="sm" round fill>
                        Small
                      </Button>
                      <Button bsSize="xs" round fill>
                        X-Small
                      </Button>
                    </div>
                  </Col>
                </Row>
                <Row>
                  <Col md={6}>
                    <div className="header">
                      <h4 className="title">Button Group</h4>
                    </div>
                    <div className="content">
                      <ButtonGroup>
                        <Button bsStyle="default">Left</Button>
                        <Button bsStyle="default">Middle</Button>
                        <Button bsStyle="default">Right</Button>
                      </ButtonGroup>
                      <br />
                      <br />
                      <ButtonGroup>
                        <Button bsStyle="default">1</Button>
                        <Button bsStyle="default">2</Button>
                        <Button bsStyle="default">3</Button>
                        <Button bsStyle="default">4</Button>
                      </ButtonGroup>
                      <ButtonGroup>
                        <Button bsStyle="default">5</Button>
                        <Button bsStyle="default">6</Button>
                        <Button bsStyle="default">7</Button>
                      </ButtonGroup>
                      <ButtonGroup>
                        <Button bsStyle="default">8</Button>
                      </ButtonGroup>
                    </div>
                  </Col>
                  <Col md={6}>
                    <div className="header">
                      <h4 className="title">Pagination</h4>
                    </div>
                    <div className="content">
                      <Pagination>
                        <Pagination.First />
                        <Pagination.Item>{1}</Pagination.Item>
                        <Pagination.Item>{2}</Pagination.Item>
                        <Pagination.Item active>{3}</Pagination.Item>
                        <Pagination.Item>{4}</Pagination.Item>
                        <Pagination.Item>{5}</Pagination.Item>
                        <Pagination.Last />
                      </Pagination>
                      <Pagination className="pagination-no-border">
                        <Pagination.First />
                        <Pagination.Item>{1}</Pagination.Item>
                        <Pagination.Item>{2}</Pagination.Item>
                        <Pagination.Item active>{3}</Pagination.Item>
                        <Pagination.Item>{4}</Pagination.Item>
                        <Pagination.Item>{5}</Pagination.Item>
                        <Pagination.Last />
                      </Pagination>
                    </div>
                  </Col>
                </Row>
                <div className="header">
                  <h4 className="title">Social buttons</h4>
                </div>
                <div className="content">
                  <Row>
                    <Col md={3} className="social-buttons-demo">
                      <h4 className="title">
                        <small> Filled </small>
                      </h4>
                      <Button fill twitter>
                        <i className="fa fa-twitter" /> Tweet
                      </Button>
                      <br />
                      <Button fill facebook>
                        <i className="fa fa-facebook-square" /> Share
                      </Button>
                      <br />
                      <Button fill google>
                        <i className="fa fa-google-plus-square" /> Share on
                        Google+
                      </Button>
                      <br />
                      <Button fill linkedin>
                        <i className="fa fa-linkedin-square" /> Connect with
                        Linkedin
                      </Button>
                      <br />
                      <Button fill pinterest>
                        <i className="fa fa-pinterest" /> Pint it
                      </Button>
                      <br />
                      <Button fill youtube>
                        <i className="fa fa-youtube-play" /> View on Youtube
                      </Button>
                      <br />
                      <Button fill tumblr>
                        <i className="fa fa-tumblr-square" /> Repost
                      </Button>
                      <br />
                      <Button fill github>
                        <i className="fa fa-github" /> Connect with Github
                      </Button>
                      <br />
                      <Button fill behance>
                        <i className="fa fa-behance-square" /> Follow us
                      </Button>
                      <br />
                      <Button fill dribbble>
                        <i className="fa fa-dribbble" /> Find us on Dribbble
                      </Button>
                      <br />
                      <Button fill reddit>
                        <i className="fa fa-reddit" /> Repost
                      </Button>
                      <br />
                      <Button fill stumbleupon>
                        <i className="fa fa-stumbleupon" /> View on StumbleUpon
                      </Button>
                      <br />
                    </Col>
                    <Col md={1} className="social-buttons-demo">
                      <h4 className="title">
                        <small>Light</small>
                      </h4>
                      <Button round twitter>
                        <i className="fa fa-twitter" />
                      </Button>
                      <br />
                      <Button round facebook>
                        <i className="fa fa-facebook"> </i>
                      </Button>
                      <br />
                      <Button round google>
                        <i className="fa fa-google-plus"> </i>
                      </Button>
                      <br />
                      <Button round linkedin>
                        <i className="fa fa-linkedin" />
                      </Button>
                      <br />
                      <Button round pinterest>
                        <i className="fa fa-pinterest" />
                      </Button>
                      <br />
                      <Button round youtube>
                        <i className="fa fa-youtube"> </i>
                      </Button>
                      <br />
                      <Button round tumblr>
                        <i className="fa fa-tumblr"> </i>
                      </Button>
                      <br />
                      <Button round github>
                        <i className="fa fa-github" />
                      </Button>
                      <br />
                      <Button round behance>
                        <i className="fa fa-behance" />
                      </Button>
                      <br />
                      <Button round dribbble>
                        <i className="fa fa-dribbble" />
                      </Button>
                      <br />
                      <Button round reddit>
                        <i className="fa fa-reddit" />
                      </Button>
                      <br />
                      <Button round stumbleupon>
                        <i className="fa fa-stumbleupon" />
                      </Button>
                      <br />
                    </Col>
                    <Col md={1} className="social-buttons-demo">
                      <h4 className="title">
                        <small>Simple</small>
                      </h4>
                      <Button simple twitter>
                        <i className="fa fa-twitter" />
                      </Button>
                      <br />
                      <Button simple facebook>
                        <i className="fa fa-facebook-square"> </i>
                      </Button>
                      <br />
                      <Button simple google>
                        <i className="fa fa-google-plus-square"> </i>
                      </Button>
                      <br />
                      <Button simple linkedin>
                        <i className="fa fa-linkedin-square" />
                      </Button>
                      <br />
                      <Button simple pinterest>
                        <i className="fa fa-pinterest" />
                      </Button>
                      <br />
                      <Button simple youtube>
                        <i className="fa fa-youtube"> </i>
                      </Button>
                      <br />
                      <Button simple tumblr>
                        <i className="fa fa-tumblr-square"> </i>
                      </Button>
                      <br />
                      <Button simple github>
                        <i className="fa fa-github" />
                      </Button>
                      <br />
                      <Button simple behance>
                        <i className="fa fa-behance" />
                      </Button>
                      <br />
                      <Button simple dribbble>
                        <i className="fa fa-dribbble" />
                      </Button>
                      <br />
                      <Button simple reddit>
                        <i className="fa fa-reddit" />
                      </Button>
                      <br />
                      <Button simple stumbleupon>
                        <i className="fa fa-stumbleupon" />
                      </Button>
                      <br />
                    </Col>
                    <Col md={3} className="social-buttons-demo">
                      <h4 className="title">
                        <small>With Text</small>
                      </h4>
                      <Button simple twitter>
                        <i className="fa fa-twitter" /> Tweet
                      </Button>
                      <br />
                      <Button simple facebook>
                        <i className="fa fa-facebook-square" /> Share
                      </Button>
                      <br />
                      <Button simple google>
                        <i className="fa fa-google-plus-square" /> Share on
                        Google+
                      </Button>
                      <br />
                      <Button simple linkedin>
                        <i className="fa fa-linkedin-square" /> Connect with
                        Linkedin
                      </Button>
                      <br />
                      <Button simple pinterest>
                        <i className="fa fa-pinterest" /> Pint it
                      </Button>
                      <br />
                      <Button simple youtube>
                        <i className="fa fa-youtube-play" /> View on Youtube
                      </Button>
                      <br />
                      <Button simple tumblr>
                        <i className="fa fa-tumblr-square" /> Repost
                      </Button>
                      <br />
                      <Button simple github>
                        <i className="fa fa-github" /> Connect with Github
                      </Button>
                      <br />
                      <Button simple behance>
                        <i className="fa fa-behance-square" /> Follow us
                      </Button>
                      <br />
                      <Button simple dribbble>
                        <i className="fa fa-dribbble" /> Find us on Dribbble
                      </Button>
                      <br />
                      <Button simple reddit>
                        <i className="fa fa-reddit" /> Repost
                      </Button>
                      <br />
                      <Button simple stumbleupon>
                        <i className="fa fa-stumbleupon" /> View on StumbleUpon
                      </Button>
                      <br />
                    </Col>
                  </Row>
                </div>
              </div>
            </Col>
          </Row>
        </Grid>
      </div>
    );
  }
}

export default Buttons;

// vue-light-bootstrap-dashboard-pro/src/pages/Dashboard/Components/Buttons.vue
<template>
  <div class="row">
    <div class="col-md-12">
      <div class="card">
        <div class="row">
          <div class="col-md-6">
            <div class="card-header">
              <h4 class="card-title">Colors</h4>
            </div>
            <div class="card-body">
              <l-button type="default" wide>Default</l-button>&nbsp;
              <l-button type="primary" wide>Primary</l-button>&nbsp;
              <l-button type="info" wide>Info</l-button>&nbsp;
              <l-button type="success" wide>Success</l-button>&nbsp;
              <l-button type="warning" wide>Warning</l-button>&nbsp;
              <l-button type="danger" wide>Danger</l-button>&nbsp;
            </div>
          </div>
          <div class="col-md-6">
            <div class="card-header">
              <h4 class="card-title">Styles</h4>
            </div>
            <div class="card-body">
              <l-button wide>Default</l-button>&nbsp;
              <l-button wide outline>Outline</l-button>&nbsp;
              <l-button wide round>Fill + Round</l-button>&nbsp;
              <l-button wide outline round>Outline + Round</l-button>&nbsp;
              <l-button wide simple link>Simple</l-button>&nbsp;
            </div>

          </div>
        </div>

        <div class="row">
          <div class="col-md-6">
            <div class="card-header">
              <h4 class="card-title">Buttons with Label</h4>
            </div>
            <div class="card-body">
              <l-button wide type="success" outline>
                <span class="btn-label">
                    <i class="fa fa-check"></i>
                </span>
                Success
              </l-button>&nbsp;

              <l-button type="danger" wide outline>
                <span class="btn-label">
                    <i class="fa fa-times"></i>
                </span>
                Danger
              </l-button>&nbsp;

              <l-button type="info" outline wide>
                <span class="btn-label">
                    <i class="fa fa-exclamation"></i>
                </span>
                Info
              </l-button>&nbsp;

              <l-button type="warning" wide outline>
                <span class="btn-label">
                    <i class="fa fa-warning"></i>
                </span>
                Warning
              </l-button>&nbsp;

              <l-button type="default" wide outline>
                <span class="btn-label">
                    <i class="fa fa-arrow-left"></i>
                </span>
                Left
              </l-button>&nbsp;

              <l-button type="default" wide default outline>
                Right
                <span class="btn-label btn-label-right">
                    <i class="fa fa-arrow-right"></i>
                </span>
              </l-button>&nbsp;
            </div>
          </div>

          <div class="col-md-6">
            <div class="card-header">
              <h4 class="card-title">Sizes</h4>
            </div>
            <div class="card-body">
              <l-button size="lg">Large</l-button>&nbsp;
              <l-button>Default</l-button>&nbsp;
              <l-button size="sm">Small</l-button>&nbsp;
              <br>
              <l-button round size="lg">Large</l-button>&nbsp;
              <l-button round>Default</l-button>&nbsp;
              <l-button round size="sm">Small</l-button>&nbsp;
            </div>
          </div>
        </div>


        <div class="row">
          <div class="col-md-6">
            <div class="card-header">
              <h4 class="card-title">Button Group</h4>
            </div>
            <div class="card-body">
              <div class="btn-group">
                <button type="button" class="btn btn-default btn-outline">Left</button>
                <button type="button" class="btn btn-default btn-outline">Middle</button>
                <button type="button" class="btn btn-default btn-outline">Right</button>
              </div>&nbsp;

              <br><br>
              <div class="btn-group">
                <button type="button" class="btn btn-default btn-outline">1</button>
                <button type="button" class="btn btn-default btn-outline">2</button>
                <button type="button" class="btn btn-default btn-outline">3</button>
                <button type="button" class="btn btn-default btn-outline">4</button>
              </div>&nbsp;
              <div class="btn-group">
                <button type="button" class="btn btn-default btn-outline">5</button>
                <button type="button" class="btn btn-default btn-outline">6</button>
                <button type="button" class="btn btn-default btn-outline">7</button>
              </div>&nbsp;
              <div class="btn-group">
                <button type="button" class="btn btn-default btn-outline">8</button>
              </div>
            </div>
          </div>
          <div class="col-md-6">
            <div class="card-header">
              <h4 class="card-title">Pagination</h4>
            </div>

            <div class="card-body">
              <l-pagination :page-count="10" v-model="defaultPagination"></l-pagination>
              <l-pagination class="pagination-no-border" :page-count="10" v-model="infoPagination"></l-pagination>
            </div>
          </div>
        </div>


        <div class="card-header">
          <h4 class="card-title">Social buttons</h4>
        </div>

        <div class="card-body">
          <div class="row">
            <div class="col-md-4 social-buttons-demo">
              <h4 class="title">
                <small> Filled </small>
              </h4>
              <button class="btn btn-social  btn-twitter">
                <i class="fa fa-twitter"></i> Connect with Twitter
              </button>
              <br>
              <button class="btn btn-social  btn-facebook">
                <i class="fa fa-facebook-square"></i> Share · 2.2k
              </button>
              <br>
              <button class="btn btn-social  btn-google">
                <i class="fa fa-google-plus-square"></i> Share on Google+
              </button>
              <br>
              <button class="btn btn-social  btn-linkedin">
                <i class="fa fa-linkedin-square"></i> Connect with Linkedin
              </button>
              <br>
              <button class="btn btn-social  btn-pinterest">
                <i class="fa fa-pinterest"></i> Pint it · 212
              </button>
              <br>
              <button class="btn btn-social  btn-youtube">
                <i class="fa fa-youtube-play"></i> View on Youtube
              </button>
              <br>
              <button class="btn btn-social  btn-tumblr">
                <i class="fa fa-tumblr-square"></i> Repost
              </button>
              <br>
              <button class="btn btn-social  btn-github">
                <i class="fa fa-github"></i> Connect with Github
              </button>
              <br>
              <button class="btn btn-social  btn-behance">
                <i class="fa fa-behance-square"></i> Follow us
              </button>
              <br>
              <button class="btn btn-social  btn-dribbble">
                <i class="fa fa-dribbble"></i> Find us on Dribbble
              </button>
              <br>
              <button class="btn btn-social  btn-reddit">
                <i class="fa fa-reddit"></i> Repost · 232
              </button>
              <br>
              <button class="btn btn-social  btn-stumbleupon">
                <i class="fa fa-stumbleupon"></i> View on StumbleUpon
              </button>
              <br>
            </div>

            <div class="col-md-2 social-buttons-demo">
              <h4 class="title">
                <small>Light</small>
              </h4>
              <button class="btn btn-social btn-round btn-twitter btn-outline">
                <i class="fa fa-twitter"></i>
              </button>
              <br>
              <button class="btn btn-social btn-round btn-facebook btn-outline">
                <i class="fa fa-facebook"> </i>
              </button>
              <br>
              <button class="btn btn-social btn-round btn-google btn-outline">
                <i class="fa fa-google-plus"> </i>
              </button>
              <br>
              <button class="btn btn-social btn-round btn-linkedin btn-outline">
                <i class="fa fa-linkedin"></i>
              </button>
              <br>
              <button class="btn btn-social btn-round btn-pinterest btn-outline">
                <i class="fa fa-pinterest"></i>
              </button>
              <br>
              <button class="btn btn-social btn-round btn-youtube btn-outline">
                <i class="fa fa-youtube"> </i>
              </button>
              <br>
              <button class="btn btn-social btn-round btn-tumblr btn-outline">
                <i class="fa fa-tumblr"> </i>
              </button>
              <br>
              <button class="btn btn-social btn-round btn-github btn-outline">
                <i class="fa fa-github"></i>
              </button>
              <br>
              <button class="btn btn-social btn-round btn-behance btn-outline">
                <i class="fa fa-behance"></i>
              </button>
              <br>
              <button class="btn btn-social btn-round btn-dribbble btn-outline">
                <i class="fa fa-dribbble"></i>
              </button>
              <br>
              <button class="btn btn-social btn-round btn-reddit btn-outline">
                <i class="fa fa-reddit"></i>
              </button>
              <br>
              <button class="btn btn-social btn-round btn-stumbleupon btn-outline">
                <i class="fa fa-stumbleupon"></i>
              </button>
              <br>
            </div>
            <div class="col-md-2 social-buttons-demo">
              <h4 class="title">
                <small>Simple</small>
              </h4>
              <button class="btn btn-social btn-link btn-twitter">
                <i class="fa fa-twitter"></i>
              </button>
              <br>
              <button class="btn btn-social btn-link btn-facebook">
                <i class="fa fa-facebook-square"> </i>
              </button>
              <br>
              <button class="btn btn-social btn-link btn-google">
                <i class="fa fa-google-plus-square"> </i>
              </button>
              <br>
              <button class="btn btn-social btn-link btn-linkedin">
                <i class="fa fa-linkedin-square"></i>
              </button>
              <br>
              <button class="btn btn-social btn-link btn-pinterest">
                <i class="fa fa-pinterest"></i>
              </button>
              <br>
              <button class="btn btn-social btn-link btn-youtube">
                <i class="fa fa-youtube"> </i>
              </button>
              <br>
              <button class="btn btn-social btn-link btn-tumblr">
                <i class="fa fa-tumblr-square"> </i>
              </button>
              <br>
              <button class="btn btn-social btn-link btn-github">
                <i class="fa fa-github"></i>
              </button>
              <br>
              <button class="btn btn-social btn-link btn-behance">
                <i class="fa fa-behance"></i>
              </button>
              <br>
              <button class="btn btn-social btn-link btn-dribbble">
                <i class="fa fa-dribbble"></i>
              </button>
              <br>
              <button class="btn btn-social btn-link btn-reddit">
                <i class="fa fa-reddit"></i>
              </button>
              <br>
              <button class="btn btn-social btn-link btn-stumbleupon">
                <i class="fa fa-stumbleupon"></i>
              </button>
              <br>
            </div>
            <div class="col-md-4 social-buttons-demo">
              <h4 class="title">
                <small>With Text</small>
              </h4>
              <button class="btn btn-social btn-link btn-twitter">
                <i class="fa fa-twitter"></i> Connect with Twitter
              </button>
              <br>
              <button class="btn btn-social btn-link btn-facebook">
                <i class="fa fa-facebook-square"></i> Share · 2.2k
              </button>
              <br>
              <button class="btn btn-social btn-link btn-google">
                <i class="fa fa-google-plus-square"></i> Share on Google+
              </button>
              <br>
              <button class="btn btn-social btn-link btn-linkedin">
                <i class="fa fa-linkedin-square"></i> Connect with Linkedin
              </button>
              <br>
              <button class="btn btn-social btn-link btn-pinterest">
                <i class="fa fa-pinterest"></i> Pint it · 212
              </button>
              <br>
              <button class="btn btn-social btn-link btn-youtube">
                <i class="fa fa-youtube-play"></i> View on Youtube
              </button>
              <br>
              <button class="btn btn-social btn-link btn-tumblr">
                <i class="fa fa-tumblr-square"></i> Repost
              </button>
              <br>
              <button class="btn btn-social btn-link btn-github">
                <i class="fa fa-github"></i> Connect with Github
              </button>
              <br>
              <button class="btn btn-social btn-link btn-behance">
                <i class="fa fa-behance-square"></i> Follow us
              </button>
              <br>
              <button class="btn btn-social btn-link btn-dribbble">
                <i class="fa fa-dribbble"></i> Find us on Dribbble
              </button>
              <br>
              <button class="btn btn-social btn-link btn-reddit">
                <i class="fa fa-reddit"></i> Repost · 232
              </button>
              <br>
              <button class="btn btn-social btn-link btn-stumbleupon">
                <i class="fa fa-stumbleupon"></i> View on StumbleUpon
              </button>
              <br>
            </div>
          </div>
        </div>

      </div>
    </div>
  </div>
</template>
<script>
  import LPagination from 'src/components/Pagination.vue'

  export default {
    components: {
      LPagination
    },
    data () {
      return {
        defaultPagination: 3,
        infoPagination: 5
      }
    }
  }
</script>
<style>

</style>
