// vue-material-kit/src/views/examples/Pricing.vue
<template>
  <div class="wrapper">
    <parallax
      class="page-header header-filter header-small"
      parallax-active="true"
      :style="headerStyle"
    >
      <div class="container">
        <div class="md-layout">
          <div
            class="md-layout-item md-size-66 md-small-size-100 mx-auto text-center"
          >
            <h1 class="title">
              Let's get started
            </h1>
            <h4>
              To get started, you will need to choose a plan for your needs. You
              can opt in for the monthly of annual options and go with one fo
              the three listed below.
            </h4>
          </div>
        </div>
      </div>
    </parallax>
    <div class="main main-raised">
      <div class="section section-pricing-2">
        <div class="container">
          <div class="md-layout">
            <div
              class="md-layout-item md-size-66 md-small-size-100 mx-auto text-center"
            >
              <tabs
                pills-align="center"
                :tab-active="1"
                :tab-name="['Monthly', 'Yearly']"
                plain
                color-button="success"
              >
                <!-- here you can add your content for tab-content -->
                <template slot="tab-pane-1" />
                <template slot="tab-pane-2" />
              </tabs>
            </div>
          </div>
          <div class="md-layout">
            <div
              class="md-layout-item md-layout-item md-size-33 md-small-size-100"
            >
              <pricing-card card-plain>
                <template slot="cardContent">
                  <h6 class="card-category text-info">
                    Free
                  </h6>
                  <h1 class="card-title">
                    <small>$</small>0
                    <small>/mo</small>
                  </h1>
                  <ul>
                    <li><b>1</b> Project</li>
                    <li><b>5</b> Team Members</li>
                    <li><b>55</b> Personal Contacts</li>
                    <li><b>5.000</b> Messages</li>
                  </ul>

                  <md-button
                    href="javascript:void(0)"
                    class="md-success md-round"
                  >
                    Get Started
                  </md-button>
                </template>
              </pricing-card>
            </div>
            <div class="md-layout-item md-size-33 md-small-size-100">
              <pricing-card card-bg="success">
                <template slot="cardContent">
                  <h6 class="card-category">
                    Premium
                  </h6>
                  <h1 class="card-title">
                    <small>$</small>89
                    <small>/mo</small>
                  </h1>
                  <ul>
                    <li><b>500</b> Project</li>
                    <li><b>50</b> Team Members</li>
                    <li><b>125</b> Personal Contacts</li>
                    <li><b>15.000</b> Messages</li>
                  </ul>

                  <md-button
                    href="javascript:void(0)"
                    class="md-white md-round"
                  >
                    Get Started
                  </md-button>
                </template>
              </pricing-card>
            </div>
            <div class="md-layout-item md-size-33 md-small-size-100">
              <pricing-card card-plain>
                <template slot="cardContent">
                  <h6 class="card-category text-info">
                    Platinium
                  </h6>
                  <h1 class="card-title">
                    <small>$</small>199
                    <small>/mo</small>
                  </h1>
                  <ul>
                    <li><b>1000</b> Project</li>
                    <li><b>100</b> Team Members</li>
                    <li><b>550</b> Personal Contacts</li>
                    <li><b>50.000</b> Messages</li>
                  </ul>

                  <md-button
                    href="javascript:void(0)"
                    class="md-success md-round"
                  >
                    Get Started
                  </md-button>
                </template>
              </pricing-card>
            </div>
          </div>
        </div>
      </div>
      <div class="section pt-0 pb-0">
        <div class="container">
          <hr>
        </div>
      </div>
      <div class="section section-features-2">
        <div class="container">
          <div class="text-center">
            <h3 class="title">
              Frequently Asked Questions
            </h3>
          </div>
          <div class="md-layout">
            <div class="md-layout-item md-size-33 md-small-size-100 ml-auto">
              <info-areas
                info-horizontal
                icon-color="info"
                icon="card_membership"
              >
                <h4
                  slot="title"
                  class="info-title"
                >
                  Can I cancel my subscription?
                </h4>
                <div
                  slot="content"
                  class="description"
                >
                  <p>
                    Yes, you can cancel and perform other actions on your
                    subscriptions via the My Account page.
                  </p>
                </div>
              </info-areas>
            </div>
            <div class="md-layout-item md-size-33 md-small-size-100 mr-auto">
              <info-areas
                info-horizontal
                icon-color="success"
                icon="card_giftcard"
              >
                <h4
                  slot="title"
                  class="info-title"
                >
                  s there any discount for an annual subscription?
                </h4>
                <div
                  slot="content"
                  class="description"
                >
                  <p>
                    Yes, we offer a 40% discount if you choose annual
                    subscription for any plan.
                  </p>
                </div>
              </info-areas>
            </div>
          </div>
          <div class="md-layout">
            <div class="md-layout-item md-size-33 md-small-size-100 ml-auto">
              <info-areas
                info-horizontal
                icon-color="success"
                icon="attach_money"
              >
                <h4
                  slot="title"
                  class="info-title"
                >
                  Which payment methods do you take?
                </h4>
                <div
                  slot="content"
                  class="description"
                >
                  <p>
                    WooCommerce comes bundled with PayPal (for accepting credit
                    card and PayPal account payments), BACS, and cash on
                    delivery for accepting payments.
                  </p>
                </div>
              </info-areas>
            </div>
            <div class="md-layout-item md-size-33 md-small-size-100 mr-auto">
              <info-areas
                info-horizontal
                icon-color="rose"
                icon="question_answer"
              >
                <h4
                  slot="title"
                  class="info-title"
                >
                  Any other questions we can answer?
                </h4>
                <div
                  slot="content"
                  class="description"
                >
                  <p>We are happy to help you. Contact us.</p>
                </div>
              </info-areas>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import { Tabs, PricingCard, InfoAreas } from "@/components";
import Mixins from "@/plugins/basicMixins";

export default {
  components: {
    Tabs,
    PricingCard,
    InfoAreas
  },
  mixins: [Mixins.HeaderImage],
  data() {
    return {
      image: require("@/assets/img/examples/bg-pricing.jpg")
    };
  }
};
</script>

<style lang="scss"></style>

// angular-now-ui-kit/src/app/examples/pricing/pricing.component.ts
import { Component, OnInit } from '@angular/core';
import * as Rellax from 'rellax';

@Component({
  selector: 'app-pricing',
  templateUrl: './pricing.component.html',
  styleUrls: ['./pricing.component.scss']
})
export class PricingComponent implements OnInit {
  data : Date = new Date();
  focus;
  focus1;
  focus2;

  constructor() { }

  ngOnInit() {
    var rellaxHeader = new Rellax('.rellax-header');

    var body = document.getElementsByTagName('body')[0];
    body.classList.add('pricing');
    var navbar = document.getElementsByTagName('nav')[0];
    navbar.classList.add('navbar-transparent');
  }
  ngOnDestroy(){
    var body = document.getElementsByTagName('body')[0];
    body.classList.remove('pricing');
    var navbar = document.getElementsByTagName('nav')[0];
    navbar.classList.remove('navbar-transparent');
  }

}

<div class="wrapper">
    <div class="page-header page-header-small">
        <div class="page-header-image rellax-header" data-rellax-speed="-8" style="background-image: url('assets/img/bg37.jpg') ;">
        </div>
        <div class="content-center">
            <div class="row">
                <div class="col-md-8 ml-auto mr-auto">
                    <h1 class="title">Let's get started</h1>
                </div>
            </div>
        </div>
    </div>
    <div class="main">
        <div class="pricing-4">
            <div class="container">
                <div class="row">
                    <div class="col-md-6 ml-auto mr-auto text-center">
                        <h4 class="description">To get started, you will need to choose a plan for your needs. You have Free Unlimited Updates and Premium Support on each package.</h4>
                        <div class="section-space"></div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4">
                        <div class="card card-pricing card-plain">
                            <div class="card-body">
                                <h6 class="category">Starter</h6>
                                <div class="icon icon-info">
                                    <i class="now-ui-icons business_briefcase-24"></i>
                                </div>
                                <h3 class="card-title">
                                    <small>$</small>10</h3>
                                <ul>
                                    <li>1000 MB</li>
                                    <li>3 email</li>
                                    <li>5 Databases</li>
                                </ul>
                                <a href="#pablo" class="btn btn-info btn-round">
                                    Get it Now
                                </a>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="card card-pricing" data-background-color="black">
                            <div class="card-body">
                                <h6 class="category">Professional</h6>
                                <div class="icon icon-success">
                                    <i class="now-ui-icons tech_headphones"></i>
                                </div>
                                <h3 class="card-title">
                                    <small>$</small>40</h3>
                                <ul>
                                    <li>Unlimited MB</li>
                                    <li>Unlimited emails</li>
                                    <li>Full Support</li>
                                </ul>
                                <a href="#pablo" class="btn btn-neutral disabled btn-round">
                                    Current Plan
                                </a>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="card card-pricing card-plain">
                            <div class="card-body">
                                <h6 class="category">Basic</h6>
                                <div class="icon icon-danger">
                                    <i class="now-ui-icons design_palette"></i>
                                </div>
                                <h3 class="card-title">
                                    <small>$</small>20</h3>
                                <ul>
                                    <li>1000 MB</li>
                                    <li>3 email</li>
                                    <li>No Support</li>
                                </ul>
                                <a href="#pablo" class="btn btn-danger btn-round">
                                    Upgrade Plan
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="section section-frequently">
            <div class="container">
                <div class="text-center">
                    <h3 class="title">Frequently Asked Questions</h3>
                </div>
                <div class="row">
                    <div class="col-md-4 ml-auto mr-auto">
                        <div class="info info-horizontal">
                            <div class="icon icon-info">
                                <i class="now-ui-icons shopping_credit-card"></i>
                            </div>
                            <div class="description">
                                <h4 class="info-title">Can I cancel my subscription?</h4>
                                <p>Yes, you can cancel and perform other actions on your subscriptions via the My Account page. </p>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="info info-horizontal">
                            <div class="icon icon-success">
                                <i class="now-ui-icons shopping_box"></i>
                            </div>
                            <div class="description">
                                <h4 class="info-title">Is there any discount for an annual subscription?</h4>
                                <p>Yes, we offer a 40% discount if you choose annual subscription for any plan.</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4 ml-auto mr-auto">
                        <div class="info info-horizontal">
                            <div class="icon icon-success">
                                <i class="now-ui-icons business_money-coins"></i>
                            </div>
                            <div class="description">
                                <h4 class="info-title">Which payment methods do you take?</h4>
                                <p>WooCommerce comes bundled with PayPal (for accepting credit card and PayPal account). </p>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="info info-horizontal">
                            <div class="icon icon-primary">
                                <i class="now-ui-icons business_bulb-63"></i>
                            </div>
                            <div class="description">
                                <h4 class="info-title">Any other questions we can answer?</h4>
                                <p>We are happy to help you. Contact us.</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="contactus-1 section-image" style="background-image: url('assets/img/bg27.jpg')">
            <div class="container">
                <div class="row">
                    <div class="col-md-5 ml-auto mr-auto">
                        <h2 class="title">Get in Touch</h2>
                        <h4 class="description">You need more information? Check what other persons are saying about our product. They are very happy with their purchase.</h4>
                        <div class="info info-horizontal">
                            <div class="icon icon-primary">
                                <i class="now-ui-icons location_pin"></i>
                            </div>
                            <div class="description">
                                <h4 class="info-title">Find us at the office</h4>
                                <p class="description"> Bld Mihail Kogalniceanu, nr. 8,
                                    <br> 7652 Bucharest,
                                    <br> Romania
                                </p>
                            </div>
                        </div>
                        <div class="info info-horizontal">
                            <div class="icon icon-primary">
                                <i class="now-ui-icons tech_mobile"></i>
                            </div>
                            <div class="description">
                                <h4 class="info-title">Give us a ring</h4>
                                <p class="description"> Michael Jordan
                                    <br> +40 762 321 762
                                    <br> Mon - Fri, 8:00-22:00
                                </p>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-5 ml-auto mr-auto">
                        <div class="card card-contact card-raised">
                            <form role="form" id="contact-form" method="post">
                                <div class="card-header text-center">
                                    <h4 class="card-title">Contact Us</h4>
                                </div>
                                <div class="card-body">
                                    <div class="row">
                                        <div class="col-md-6 pr-2">
                                            <label>First name</label>
                                            <div class="input-group" [ngClass]="{'input-group-focus':focus===true}">
                                              <div class="input-group-prepend">
                                                  <span class="input-group-text">  <i class="now-ui-icons users_circle-08"></i></span>
                                              </div>
                                                <input type="text" class="form-control" placeholder="First Name..." (focus)="focus=true" (blur)="focus=false">
                                            </div>
                                        </div>
                                        <div class="col-md-6 pl-2">
                                            <div class="form-group">
                                                <label>Last name</label>
                                                <div class="input-group" [ngClass]="{'input-group-focus':focus1===true}">
                                                  <div class="input-group-prepend">
                                                      <span class="input-group-text"> <i class="now-ui-icons text_caps-small"></i></span>
                                                  </div>
                                                    <input type="text" placeholder="Last Name..." class="form-control" (focus)="focus1=true" (blur)="focus1=false">
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label>Email address</label>
                                        <div class="input-group" [ngClass]="{'input-group-focus':focus2===true}">
                                          <div class="input-group-prepend">
                                              <span class="input-group-text"> <i class="now-ui-icons ui-1_email-85"></i></span>
                                          </div>
                                            <input type="email" placeholder="Email Here..." class="form-control" (focus)="focus2=true" (blur)="focus2=false">
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label>Your message</label>
                                        <textarea name="message" class="form-control" id="message" rows="6"></textarea>
                                    </div>
                                    <div class="row">
                                        <div class="col-md-6">
                                          <div class="form-check">
                                              <label class="form-check-label">
                                                  <input class="form-check-input" type="checkbox">
                                                  <span class="form-check-sign"></span>
                                                  I'm not a robot
                                              </label>
                                          </div>
                                        </div>
                                        <div class="col-md-6">
                                            <button type="submit" class="btn btn-primary btn-round pull-right">Send Message</button>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <footer class="footer ">
        <div class="container">
            <nav>
                <ul>
                    <li>
                        <a href="https://www.creative-tim.com">
                            Creative Tim
                        </a>
                    </li>
                    <li>
                        <a href="https://www.creative-tim.com/about-us">
                            About Us
                        </a>
                    </li>
                    <li>
                        <a href="http://blog.creative-tim.com">
                            Blog
                        </a>
                    </li>
                    <li>
                        <a href="https://www.creative-tim.com/license">
                            License
                        </a>
                    </li>
                </ul>
            </nav>
            <div class="copyright">
                &copy;
              {{data | date: 'yyyy'}}, Designed by
                <a href="https://www.invisionapp.com" target="_blank">Invision</a>. Coded by
                <a href="https://www.creative-tim.com" target="_blank">Creative Tim</a>.
            </div>
        </div>
    </footer>
</div>
