// vue-black-dashboard/src/pages/Components/Buttons.vue
<template>
  <div class="row">
    <div class="col-md-12">
      <div class="card">
        <div class="row">
          <div class="col-md-6">
            <div class="card-header">
              <h4 class="card-title">Pick your Color</h4>
            </div>
            <div class="card-body">
              <base-button>Default</base-button>&nbsp;
              <base-button type="primary">Primary</base-button>
              <base-button type="info">Info</base-button>&nbsp; <br />
              <base-button type="success" class="animation-on-hover"
                >Success</base-button
              >&nbsp; <base-button type="warning">Warning</base-button>&nbsp;
              <base-button type="danger">Danger</base-button>&nbsp;
            </div>
          </div>
          <div class="col-md-6">
            <div class="card-header">
              <h4 class="card-title">Buttons with Label</h4>
            </div>
            <div class="card-body">
              <base-button>
                <i class="tim-icons icon-minimal-left"></i> Left
              </base-button>
              &nbsp;

              <base-button>
                Right <i class="tim-icons icon-minimal-right"></i>
              </base-button>
              &nbsp;

              <base-button type="info">
                <i class="tim-icons icon-alert-circle-exc"></i> Info
              </base-button>
              <br />
              <base-button type="success">
                <i class="tim-icons icon-check-2"></i> Success
              </base-button>
              &nbsp;

              <base-button type="warning">
                <i class="tim-icons icon-time-alarm"></i> Warning
              </base-button>
              &nbsp;

              <base-button type="danger">
                <i class="tim-icons icon-simple-remove"></i> Danger
              </base-button>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-md-6">
            <div class="card-header">
              <h4 class="card-title">Pick your Size</h4>
            </div>
            <div class="card-body">
              <base-button type="primary" size="sm">Small</base-button>
              <base-button type="primary">Regular</base-button>
              <base-button type="primary" size="lg">Large</base-button>
            </div>
          </div>
          <div class="col-md-6">
            <div class="card-header">
              <h4 class="card-title">Pick your Style</h4>
            </div>
            <div class="card-body">
              <base-button type="primary">Default</base-button>
              <base-button type="primary" round>round</base-button>
              <base-button type="primary" round>
                <i slot="label" class="tim-icons icon-heart-2"></i> with icon
              </base-button>
              <base-button type="primary" round icon>
                <i class="tim-icons icon-heart-2"></i>
              </base-button>
              <base-button type="primary" simple>Simple</base-button>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-md-6">
            <div class="card-header">
              <h4 class="card-title">Pagination</h4>
            </div>

            <div class="card-body">
              <base-pagination
                type="warning"
                :page-count="10"
                :show-arrows="false"
                v-model="defaultPagination"
              />

              <base-pagination
                :page-count="10"
                :pages-to-display="3"
                v-model="infoPagination"
              />
            </div>
          </div>

          <div class="col-md-6">
            <div class="card-header">
              <h4 class="card-title">Button Group</h4>
            </div>
            <div class="card-body">
              <div class="btn-group">
                <button type="button" class="btn btn-info btn-outline">
                  Left
                </button>
                <button type="button" class="btn btn-info btn-outline">
                  Middle
                </button>
                <button type="button" class="btn btn-info btn-outline">
                  Right
                </button>
              </div>

              <br /><br />
              <div class="btn-group">
                <button type="button" class="btn btn-info btn-outline">
                  1
                </button>
                <button type="button" class="btn btn-info btn-outline">
                  2
                </button>
                <button type="button" class="btn btn-info btn-outline">
                  3
                </button>
                <button type="button" class="btn btn-info btn-outline">
                  4
                </button>
              </div>
              <div class="btn-group">
                <button
                  type="button"
                  class="btn btn-info btn-round btn-outline"
                >
                  5
                </button>
                <button
                  type="button"
                  class="btn btn-info btn-round btn-outline"
                >
                  6
                </button>
                <button
                  type="button"
                  class="btn btn-info btn-round btn-outline"
                >
                  7
                </button>
              </div>
            </div>
          </div>
        </div>

        <div class="card-header">
          <h4 class="card-title">Social buttons</h4>
        </div>

        <div class="card-body">
          <div class="row">
            <div class="col-md-4 col-sm-5">
              <p class="category">Default</p>
              <button class="btn btn-twitter">
                <i class="fab fa-twitter"></i> Connect with Twitter
              </button>
            </div>
            <div class="col-md-1 col-sm-1">
              <p class="category">&nbsp;</p>
              <button class="btn btn-icon btn-twitter">
                <i class="fab fa-twitter"></i>
              </button>
            </div>
            <div class="col-md-1 col-sm-1">
              <p class="category">&nbsp;</p>
              <button class="btn btn-icon btn-round btn-twitter">
                <i class="fab fa-twitter"></i>
              </button>
            </div>
            <div class="col-md-1 col-sm-1">
              <p class="category">Neutral</p>
              <button class="btn btn-icon btn-simple btn-twitter">
                <i class="fab fa-twitter"></i>
              </button>
            </div>
            <div class="col-md-3 col-sm-4">
              <p class="category">&nbsp;</p>
              <button class="btn btn-simple btn-twitter">
                <i class="fab fa-twitter"></i> Connect with Twitter
              </button>
            </div>
          </div>
          <div class="row">
            <div class="col-md-4 col-sm-5">
              <button class="btn btn-facebook">
                <i class="fab fa-facebook-square"></i> Share · 2.2k
              </button>
            </div>
            <div class="col-md-1 col-sm-1">
              <button class="btn btn-icon btn-facebook">
                <i class="fab fa-facebook-f"> </i>
              </button>
            </div>
            <div class="col-md-1 col-sm-1">
              <button class="btn btn-icon btn-round btn-facebook">
                <i class="fab fa-facebook-f"> </i>
              </button>
            </div>
            <div class="col-md-1 col-sm-1">
              <button class="btn btn-icon btn-simple btn-facebook">
                <i class="fab fa-facebook-square"> </i>
              </button>
            </div>
            <div class="col-md-3 col-sm-4">
              <button class="btn btn-simple btn-facebook">
                <i class="fab fa-facebook-square"></i> Share · 2.2k
              </button>
            </div>
          </div>
          <div class="row">
            <div class="col-md-4 col-sm-5">
              <button class="btn btn-google">
                <i class="fab fa-google-plus-g"></i> Share on Google+
              </button>
            </div>
            <div class="col-md-1 col-sm-1">
              <button class="btn btn-icon  btn-google">
                <i class="fab fa-google-plus-g"> </i>
              </button>
            </div>
            <div class="col-md-1 col-sm-1">
              <button class="btn btn-icon btn-round btn-google">
                <i class="fab fa-google-plus-g"> </i>
              </button>
            </div>
            <div class="col-md-1 col-sm-1">
              <button class="btn btn-icon btn-simple btn-google">
                <i class="fab fa-google-plus-g"> </i>
              </button>
            </div>
            <div class="col-md-3 col-sm-4">
              <button class="btn btn-simple btn-google">
                <i class="fab fa-google-plus-g"></i> Share on Google+
              </button>
            </div>
          </div>
          <div class="row">
            <div class="col-md-4 col-sm-5">
              <button class="btn btn-linkedin">
                <i class="fab fa-linkedin"></i> Connect with Linkedin
              </button>
            </div>
            <div class="col-md-1 col-sm-1">
              <button class="btn btn-icon  btn-linkedin">
                <i class="fab fa-linkedin"></i>
              </button>
            </div>
            <div class="col-md-1 col-sm-1">
              <button class="btn btn-icon btn-round btn-linkedin">
                <i class="fab fa-linkedin"></i>
              </button>
            </div>
            <div class="col-md-1 col-sm-1">
              <button class="btn btn-icon btn-simple btn-linkedin">
                <i class="fab fa-linkedin"></i>
              </button>
            </div>
            <div class="col-md-3 col-sm-4">
              <button class="btn btn-simple btn-linkedin">
                <i class="fab fa-linkedin"></i> Connect with Linkedin
              </button>
            </div>
          </div>
          <div class="row">
            <div class="col-md-4 col-sm-5">
              <button class="btn btn-pinterest">
                <i class="fab fa-pinterest"></i> Pint it · 212
              </button>
            </div>
            <div class="col-md-1 col-sm-1">
              <button class="btn btn-icon btn-pinterest">
                <i class="fab fa-pinterest"></i>
              </button>
            </div>
            <div class="col-md-1 col-sm-1">
              <button class="btn btn-icon btn-round btn-pinterest">
                <i class="fab fa-pinterest"></i>
              </button>
            </div>
            <div class="col-md-1 col-sm-1">
              <button class="btn btn-icon btn-simple btn-pinterest">
                <i class="fab fa-pinterest"></i>
              </button>
            </div>
            <div class="col-md-3 col-sm-4">
              <button class="btn btn-simple btn-pinterest">
                <i class="fab fa-pinterest"></i> Pint it · 212
              </button>
            </div>
          </div>
          <div class="row">
            <div class="col-md-4 col-sm-5">
              <button class="btn btn-youtube">
                <i class="fab fa-youtube"></i> View on Youtube
              </button>
            </div>
            <div class="col-md-1 col-sm-1">
              <button class="btn btn-icon btn-youtube">
                <i class="fab fa-youtube"> </i>
              </button>
            </div>
            <div class="col-md-1 col-sm-1">
              <button class="btn btn-icon btn-round btn-youtube">
                <i class="fab fa-youtube"> </i>
              </button>
            </div>
            <div class="col-md-1 col-sm-1">
              <button class="btn btn-icon btn-simple btn-youtube">
                <i class="fab fa-youtube"> </i>
              </button>
            </div>
            <div class="col-md-3 col-sm-4">
              <button class="btn btn-simple btn-youtube">
                <i class="fab fa-youtube"></i> View on Youtube
              </button>
            </div>
          </div>
          <div class="row">
            <div class="col-md-4 col-sm-5">
              <button class="btn btn-tumblr">
                <i class="fab fa-tumblr-square"></i> Repost
              </button>
            </div>
            <div class="col-md-1 col-sm-1">
              <button class="btn btn-icon  btn-tumblr">
                <i class="fab fa-tumblr"> </i>
              </button>
            </div>
            <div class="col-md-1 col-sm-1">
              <button class="btn btn-icon btn-round btn-tumblr">
                <i class="fab fa-tumblr"> </i>
              </button>
            </div>
            <div class="col-md-1 col-sm-1">
              <button class="btn btn-icon btn-simple btn-tumblr">
                <i class="fab fa-tumblr-square"> </i>
              </button>
            </div>
            <div class="col-md-3 col-sm-4">
              <button class="btn btn-simple btn-tumblr">
                <i class="fab fa-tumblr-square"></i> Repost
              </button>
            </div>
          </div>
          <div class="row">
            <div class="col-md-4 col-sm-5">
              <button class="btn btn-github">
                <i class="fab fa-github"></i> Connect with Github
              </button>
            </div>
            <div class="col-md-1 col-sm-1">
              <button class="btn btn-icon  btn-github">
                <i class="fab fa-github"></i>
              </button>
            </div>
            <div class="col-md-1 col-sm-1">
              <button class="btn btn-icon btn-round btn-github">
                <i class="fab fa-github"></i>
              </button>
            </div>
            <div class="col-md-1 col-sm-1">
              <button class="btn btn-icon btn-simple btn-github">
                <i class="fab fa-github"></i>
              </button>
            </div>
            <div class="col-md-3 col-sm-4">
              <button class="btn btn-simple btn-github">
                <i class="fab fa-github"></i> Connect with Github
              </button>
            </div>
          </div>
          <div class="row">
            <div class="col-md-4 col-sm-5">
              <button class="btn btn-behance">
                <i class="fab fa-behance-square"></i> Follow us
              </button>
            </div>
            <div class="col-md-1 col-sm-1">
              <button class="btn btn-icon  btn-behance">
                <i class="fab fa-behance"></i>
              </button>
            </div>
            <div class="col-md-1 col-sm-1">
              <button class="btn btn-icon btn-round btn-behance">
                <i class="fab fa-behance"></i>
              </button>
            </div>
            <div class="col-md-1 col-sm-1">
              <button class="btn btn-icon btn-simple btn-behance">
                <i class="fab fa-behance"></i>
              </button>
            </div>
            <div class="col-md-3 col-sm-4">
              <button class="btn btn-simple btn-behance">
                <i class="fab fa-behance-square"></i> Follow us
              </button>
            </div>
          </div>
          <div class="row">
            <div class="col-md-4 col-sm-5">
              <button class="btn btn-dribbble">
                <i class="fab fa-dribbble"></i> Find us on Dribble
              </button>
            </div>
            <div class="col-md-1 col-sm-1">
              <button class="btn btn-icon  btn-dribbble">
                <i class="fab fa-dribbble"></i>
              </button>
            </div>
            <div class="col-md-1 col-sm-1">
              <button class="btn btn-icon btn-round btn-dribbble">
                <i class="fab fa-dribbble"></i>
              </button>
            </div>
            <div class="col-md-1 col-sm-1">
              <button class="btn btn-icon btn-simple btn-dribbble">
                <i class="fab fa-dribbble"></i>
              </button>
            </div>
            <div class="col-md-3 col-sm-4">
              <button class="btn btn-simple btn-dribbble">
                <i class="fab fa-dribbble"></i> Find us on Dribble
              </button>
            </div>
          </div>
          <div class="row">
            <div class="col-md-4 col-sm-5">
              <button class="btn btn-reddit">
                <i class="fab fa-reddit"></i> Repost · 232
              </button>
            </div>
            <div class="col-md-1 col-sm-1">
              <button class="btn btn-icon  btn-reddit">
                <i class="fab fa-reddit"></i>
              </button>
            </div>
            <div class="col-md-1 col-sm-1">
              <button class="btn btn-icon btn-round btn-reddit">
                <i class="fab fa-reddit"></i>
              </button>
            </div>
            <div class="col-md-1 col-sm-1">
              <button class="btn btn-icon btn-simple btn-reddit">
                <i class="fab fa-reddit"></i>
              </button>
            </div>
            <div class="col-md-3 col-sm-4">
              <button class="btn btn-simple btn-reddit">
                <i class="fab fa-reddit"></i> Repost · 232
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>
<script>
import { BasePagination } from 'src/components';

export default {
  components: {
    BasePagination
  },
  data() {
    return {
      defaultPagination: 1,
      infoPagination: 3
    };
  }
};
</script>
<style></style>

// paper-dashboard-pro-react-v1/src/views/components/Buttons.jsx
/*!

=========================================================
* Paper Dashboard PRO React - v1.1.0
=========================================================

* Product Page: https://www.creative-tim.com/product/paper-dashboard-pro-react
* Copyright 2019 Creative Tim (https://www.creative-tim.com)

* Coded by Creative Tim

=========================================================

* The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

*/
import React from "react";

// reactstrap components
import {
  Button,
  ButtonGroup,
  Card,
  CardHeader,
  CardBody,
  CardTitle,
  Pagination,
  PaginationItem,
  PaginationLink,
  Row,
  Col
} from "reactstrap";

class Buttons extends React.Component {
  render() {
    return (
      <>
        <div className="content">
          <Card>
            <Row>
              <Col md="6">
                <CardHeader>
                  <CardTitle tag="h4">Pick your Color</CardTitle>
                </CardHeader>
                <CardBody>
                  <Button color="default">Default</Button>
                  <Button color="primary">Primary</Button>
                  <Button color="info">Info</Button>
                  <Button color="success">Success</Button>
                  <Button color="warning">Warning</Button>
                  <Button color="danger">Danger</Button>
                </CardBody>
              </Col>
              <Col md="6">
                <CardHeader>
                  <CardTitle tag="h4">Buttons with Label</CardTitle>
                </CardHeader>
                <CardBody>
                  <Button color="info">
                    <span className="btn-label">
                      <i className="nc-icon nc-settings-gear-65" />
                    </span>
                    Info
                  </Button>
                  <Button color="success">
                    <span className="btn-label">
                      <i className="nc-icon nc-check-2" />
                    </span>
                    Success
                  </Button>
                  <Button color="warning">
                    <i className="nc-icon nc-zoom-split" />
                    Warning
                  </Button>
                  <Button color="danger">
                    <i className="nc-icon nc-simple-remove" />
                    Danger
                  </Button>
                  <Button color="default">
                    <span className="btn-label">
                      <i className="nc-icon nc-minimal-left" />
                    </span>
                    Left
                  </Button>
                  <Button color="default">
                    Right{" "}
                    <span className="btn-label btn-label-right">
                      <i className="nc-icon nc-minimal-right" />
                    </span>
                  </Button>
                </CardBody>
              </Col>
            </Row>
            <Row>
              <Col md="6">
                <CardHeader>
                  <CardTitle tag="h4">Pick your Size</CardTitle>
                </CardHeader>
                <CardBody>
                  <Button color="primary" size="sm">
                    Small
                  </Button>
                  <Button color="primary">Regular</Button>
                  <Button color="primary" size="lg">
                    Large
                  </Button>
                </CardBody>
              </Col>
              <Col md="6">
                <CardHeader>
                  <CardTitle tag="h4">Pick your Style</CardTitle>
                </CardHeader>
                <CardBody>
                  <Button color="primary">Default</Button>
                  <Button className="btn-round" color="primary">
                    round
                  </Button>
                  <Button className="btn-round btn-icon" color="primary">
                    <i className="fa fa-heart" />
                  </Button>
                  <Button className="btn-round" color="primary" outline>
                    <i className="fa fa-heart" />
                    with icon
                  </Button>
                  <Button className="btn-link" color="primary">
                    link
                  </Button>
                </CardBody>
              </Col>
            </Row>
            <Row>
              <Col md="6">
                <CardHeader>
                  <CardTitle tag="h4">Pagination</CardTitle>
                </CardHeader>
                <CardBody>
                  <nav aria-label="Page navigation example">
                    <Pagination
                      className="pagination pagination-primary"
                      listClassName="pagination-primary"
                    >
                      <PaginationItem className="active">
                        <PaginationLink
                          href="#pablo"
                          onClick={e => e.preventDefault()}
                        >
                          1
                        </PaginationLink>
                      </PaginationItem>
                      <PaginationItem>
                        <PaginationLink
                          href="#pablo"
                          onClick={e => e.preventDefault()}
                        >
                          2
                        </PaginationLink>
                      </PaginationItem>
                      <PaginationItem>
                        <PaginationLink
                          href="#pablo"
                          onClick={e => e.preventDefault()}
                        >
                          3
                        </PaginationLink>
                      </PaginationItem>
                      <PaginationItem>
                        <PaginationLink
                          href="#pablo"
                          onClick={e => e.preventDefault()}
                        >
                          4
                        </PaginationLink>
                      </PaginationItem>
                      <PaginationItem>
                        <PaginationLink
                          href="#pablo"
                          onClick={e => e.preventDefault()}
                        >
                          5
                        </PaginationLink>
                      </PaginationItem>
                    </Pagination>
                    <Pagination>
                      <PaginationItem>
                        <PaginationLink
                          aria-label="Previous"
                          href="#pablo"
                          onClick={e => e.preventDefault()}
                        >
                          <span aria-hidden={true}>
                            <i
                              aria-hidden={true}
                              className="fa fa-angle-double-left"
                            />
                          </span>
                        </PaginationLink>
                      </PaginationItem>
                      <PaginationItem>
                        <PaginationLink
                          href="#pablo"
                          onClick={e => e.preventDefault()}
                        >
                          1
                        </PaginationLink>
                      </PaginationItem>
                      <PaginationItem className="active">
                        <PaginationLink
                          href="#pablo"
                          onClick={e => e.preventDefault()}
                        >
                          2
                        </PaginationLink>
                      </PaginationItem>
                      <PaginationItem>
                        <PaginationLink
                          href="#pablo"
                          onClick={e => e.preventDefault()}
                        >
                          3
                        </PaginationLink>
                      </PaginationItem>
                      <PaginationItem>
                        <PaginationLink
                          aria-label="Next"
                          href="#pablo"
                          onClick={e => e.preventDefault()}
                        >
                          <span aria-hidden={true}>
                            <i
                              aria-hidden={true}
                              className="fa fa-angle-double-right"
                            />
                          </span>
                        </PaginationLink>
                      </PaginationItem>
                    </Pagination>
                  </nav>
                </CardBody>
              </Col>
              <Col md="6">
                <CardHeader>
                  <CardTitle tag="h4">Button Group</CardTitle>
                </CardHeader>
                <CardBody>
                  <ButtonGroup>
                    <Button
                      className="btn-round"
                      color="info"
                      outline
                      type="button"
                    >
                      Left
                    </Button>
                    <Button
                      className="btn-round"
                      color="info"
                      outline
                      type="button"
                    >
                      Middle
                    </Button>
                    <Button
                      className="btn-round"
                      color="info"
                      outline
                      type="button"
                    >
                      Right
                    </Button>
                  </ButtonGroup>
                  <br />
                  <br />
                  <ButtonGroup data-toggle="buttons">
                    <Button
                      className="btn-round"
                      color="info"
                      outline
                      type="button"
                    >
                      1
                    </Button>
                    <Button
                      className="btn-round"
                      color="info"
                      outline
                      type="button"
                    >
                      2
                    </Button>
                    <Button
                      className="btn-round"
                      color="info"
                      outline
                      type="button"
                    >
                      3
                    </Button>
                    <Button
                      className="btn-round"
                      color="info"
                      outline
                      type="button"
                    >
                      4
                    </Button>
                  </ButtonGroup>
                  <ButtonGroup>
                    <Button
                      className="btn-round"
                      color="info"
                      outline
                      type="button"
                    >
                      5
                    </Button>
                    <Button
                      className="btn-round"
                      color="info"
                      outline
                      type="button"
                    >
                      6
                    </Button>
                    <Button
                      className="btn-round"
                      color="info"
                      outline
                      type="button"
                    >
                      7
                    </Button>
                  </ButtonGroup>
                </CardBody>
              </Col>
            </Row>
            <Row>
              <Col sm="12">
                <CardHeader>
                  <CardTitle tag="h4">Social buttons</CardTitle>
                </CardHeader>
                <CardBody>
                  <Row>
                    <Col md="4" sm="5">
                      <p className="category">Default</p>
                      <Button color="twitter">
                        <i className="fa fa-twitter" />
                        Connect with Twitter
                      </Button>
                    </Col>
                    <Col md="1" sm="1" xs="3">
                      <p className="category"> </p>
                      <Button className="btn-icon" color="twitter">
                        <i className="fa fa-twitter" />
                      </Button>
                    </Col>
                    <Col md="1" sm="1" xs="3">
                      <p className="category"> </p>
                      <Button className="btn-icon btn-round" color="twitter">
                        <i className="fa fa-twitter" />
                      </Button>
                    </Col>
                    <Col md="1" sm="1" xs="3">
                      <p className="category">Neutral</p>
                      <Button className="btn-icon btn-neutral" color="twitter">
                        <i className="fa fa-twitter" />
                      </Button>
                    </Col>
                    <Col md="3" sm="4">
                      <p className="category"> </p>
                      <Button className="btn-neutral" color="twitter">
                        <i className="fa fa-twitter" />
                        Connect with Twitter
                      </Button>
                    </Col>
                  </Row>
                  <Row>
                    <Col md="4" sm="5">
                      <Button color="facebook">
                        <i className="fa fa-facebook-square" />
                        Share · 2.2k
                      </Button>
                    </Col>
                    <Col md="1" sm="1" xs="3">
                      <Button className="btn-icon" color="facebook">
                        <i className="fa fa-facebook-f" />
                      </Button>
                    </Col>
                    <Col md="1" sm="1" xs="3">
                      <Button className="btn-icon btn-round" color="facebook">
                        <i className="fa fa-facebook-f" />
                      </Button>
                    </Col>
                    <Col md="1" sm="1" xs="3">
                      <Button className="btn-icon btn-neutral" color="facebook">
                        <i className="fa fa-facebook-square" />
                      </Button>
                    </Col>
                    <Col md="3" sm="4">
                      <Button className="btn-neutral" color="facebook">
                        <i className="fa fa-facebook-square" />
                        Share · 2.2k
                      </Button>
                    </Col>
                  </Row>
                  <Row>
                    <Col md="4" sm="5">
                      <Button color="google">
                        <i className="fa fa-google-plus" />
                        Share on Google+
                      </Button>
                    </Col>
                    <Col md="1" sm="1" xs="3">
                      <Button className="btn-icon" color="google">
                        <i className="fa fa-google-plus" />
                      </Button>
                    </Col>
                    <Col md="1" sm="1" xs="3">
                      <Button className="btn-icon btn-round" color="google">
                        <i className="fa fa-google-plus" />
                      </Button>
                    </Col>
                    <Col md="1" sm="1" xs="3">
                      <Button className="btn-icon btn-neutral" color="google">
                        <i className="fa fa-google-plus" />
                      </Button>
                    </Col>
                    <Col md="3" sm="4">
                      <Button className="btn-neutral" color="google">
                        <i className="fa fa-google-plus" />
                        Share on Google+
                      </Button>
                    </Col>
                  </Row>
                  <Row>
                    <Col md="4" sm="5">
                      <Button color="linkedin">
                        <i className="fa fa-linkedin" />
                        Connect with Linkedin
                      </Button>
                    </Col>
                    <Col md="1" sm="1" xs="3">
                      <Button className="btn-icon" color="linkedin">
                        <i className="fa fa-linkedin" />
                      </Button>
                    </Col>
                    <Col md="1" sm="1" xs="3">
                      <Button className="btn-icon btn-round" color="linkedin">
                        <i className="fa fa-linkedin" />
                      </Button>
                    </Col>
                    <Col md="1" sm="1" xs="3">
                      <Button className="btn-icon btn-neutral" color="linkedin">
                        <i className="fa fa-linkedin" />
                      </Button>
                    </Col>
                    <Col md="3" sm="4">
                      <Button className="btn-neutral" color="linkedin">
                        <i className="fa fa-linkedin" />
                        Connect with Linkedin
                      </Button>
                    </Col>
                  </Row>
                  <Row>
                    <Col md="4" sm="5">
                      <Button color="pinterest">
                        <i className="fa fa-pinterest" />
                        Pint it · 212
                      </Button>
                    </Col>
                    <Col md="1" sm="1" xs="3">
                      <Button className="btn-icon" color="pinterest">
                        <i className="fa fa-pinterest" />
                      </Button>
                    </Col>
                    <Col md="1" sm="1" xs="3">
                      <Button className="btn-icon btn-round" color="pinterest">
                        <i className="fa fa-pinterest" />
                      </Button>
                    </Col>
                    <Col md="1" sm="1" xs="3">
                      <Button
                        className="btn-icon btn-neutral"
                        color="pinterest"
                      >
                        <i className="fa fa-pinterest" />
                      </Button>
                    </Col>
                    <Col md="3" sm="4">
                      <Button className="btn-neutral" color="pinterest">
                        <i className="fa fa-pinterest" />
                        Pint it · 212
                      </Button>
                    </Col>
                  </Row>
                  <Row>
                    <Col md="4" sm="5">
                      <Button color="youtube">
                        <i className="fa fa-youtube" />
                        View on Youtube
                      </Button>
                    </Col>
                    <Col md="1" sm="1" xs="3">
                      <Button className="btn-icon" color="youtube">
                        <i className="fa fa-youtube" />
                      </Button>
                    </Col>
                    <Col md="1" sm="1" xs="3">
                      <Button className="btn-icon btn-round" color="youtube">
                        <i className="fa fa-youtube" />
                      </Button>
                    </Col>
                    <Col md="1" sm="1" xs="3">
                      <Button className="btn-icon btn-neutral" color="youtube">
                        <i className="fa fa-youtube" />
                      </Button>
                    </Col>
                    <Col md="3" sm="4">
                      <Button className="btn-neutral" color="youtube">
                        <i className="fa fa-youtube" />
                        View on Youtube
                      </Button>
                    </Col>
                  </Row>
                  <Row>
                    <Col md="4" sm="5">
                      <Button color="tumblr">
                        <i className="fa fa-tumblr-square" />
                        Repost
                      </Button>
                    </Col>
                    <Col md="1" sm="1" xs="3">
                      <Button className="btn-icon" color="tumblr">
                        <i className="fa fa-tumblr" />
                      </Button>
                    </Col>
                    <Col md="1" sm="1" xs="3">
                      <Button className="btn-icon btn-round" color="tumblr">
                        <i className="fa fa-tumblr" />
                      </Button>
                    </Col>
                    <Col md="1" sm="1" xs="3">
                      <Button className="btn-icon btn-neutral" color="tumblr">
                        <i className="fa fa-tumblr-square" />
                      </Button>
                    </Col>
                    <Col md="3" sm="4">
                      <Button className="btn-neutral" color="tumblr">
                        <i className="fa fa-tumblr-square" />
                        Repost
                      </Button>
                    </Col>
                  </Row>
                  <Row>
                    <Col md="4" sm="5">
                      <Button color="github">
                        <i className="fa fa-github" />
                        Connect with Github
                      </Button>
                    </Col>
                    <Col md="1" sm="1" xs="3">
                      <Button className="btn-icon" color="github">
                        <i className="fa fa-github" />
                      </Button>
                    </Col>
                    <Col md="1" sm="1" xs="3">
                      <Button className="btn-icon btn-round" color="github">
                        <i className="fa fa-github" />
                      </Button>
                    </Col>
                    <Col md="1" sm="1" xs="3">
                      <Button className="btn-icon btn-neutral" color="github">
                        <i className="fa fa-github" />
                      </Button>
                    </Col>
                    <Col md="3" sm="4">
                      <Button className="btn-neutral" color="github">
                        <i className="fa fa-github" />
                        Connect with Github
                      </Button>
                    </Col>
                  </Row>
                  <Row>
                    <Col md="4" sm="5">
                      <Button color="behance">
                        <i className="fa fa-behance-square" />
                        Follow us
                      </Button>
                    </Col>
                    <Col md="1" sm="1" xs="3">
                      <Button className="btn-icon" color="behance">
                        <i className="fa fa-behance" />
                      </Button>
                    </Col>
                    <Col md="1" sm="1" xs="3">
                      <Button className="btn-icon btn-round" color="behance">
                        <i className="fa fa-behance" />
                      </Button>
                    </Col>
                    <Col md="1" sm="1" xs="3">
                      <Button className="btn-icon btn-neutral" color="behance">
                        <i className="fa fa-behance" />
                      </Button>
                    </Col>
                    <Col md="3" sm="4">
                      <Button className="btn-neutral" color="behance">
                        <i className="fa fa-behance-square" />
                        Follow us
                      </Button>
                    </Col>
                  </Row>
                  <Row>
                    <Col md="4" sm="5">
                      <Button color="dribbble">
                        <i className="fa fa-dribbble" />
                        Find us on Dribble
                      </Button>
                    </Col>
                    <Col md="1" sm="1" xs="3">
                      <Button className="btn-icon" color="dribbble">
                        <i className="fa fa-dribbble" />
                      </Button>
                    </Col>
                    <Col md="1" sm="1" xs="3">
                      <Button className="btn-icon btn-round" color="dribbble">
                        <i className="fa fa-dribbble" />
                      </Button>
                    </Col>
                    <Col md="1" sm="1" xs="3">
                      <Button className="btn-icon btn-neutral" color="dribbble">
                        <i className="fa fa-dribbble" />
                      </Button>
                    </Col>
                    <Col md="3" sm="4">
                      <Button className="btn-neutral" color="dribbble">
                        <i className="fa fa-dribbble" />
                        Find us on Dribble
                      </Button>
                    </Col>
                  </Row>
                  <Row>
                    <Col md="4" sm="5">
                      <Button color="reddit">
                        <i className="fa fa-reddit" />
                        Repost · 232
                      </Button>
                    </Col>
                    <Col md="1" sm="1" xs="3">
                      <Button className="btn-icon" color="reddit">
                        <i className="fa fa-reddit" />
                      </Button>
                    </Col>
                    <Col md="1" sm="1" xs="3">
                      <Button className="btn-icon btn-round" color="reddit">
                        <i className="fa fa-reddit" />
                      </Button>
                    </Col>
                    <Col md="1" sm="1" xs="3">
                      <Button className="btn-icon btn-neutral" color="reddit">
                        <i className="fa fa-reddit" />
                      </Button>
                    </Col>
                    <Col md="3" sm="4">
                      <Button className="btn-neutral" color="reddit">
                        <i className="fa fa-reddit" />
                        Repost · 232
                      </Button>
                    </Col>
                  </Row>
                </CardBody>
              </Col>
            </Row>
          </Card>
        </div>
      </>
    );
  }
}

export default Buttons;
