// nuxt-paper-dashboard/src/components/Dashboard/Views/Charts.vue
<template>
  <div class="row">
    <div class="col-md-6">
      <div class="card">
        <div class="card-header">
          <h4 class="card-title">24 Hours Performance</h4>
          <p class="category">Line Chart</p>
        </div>
        <div class="card-content">
          <div id="chartPerformance" class="ct-chart"></div>
        </div>
      </div>
    </div>

    <div class="col-md-6">
      <div class="card">
        <div class="card-header">
          <h4 class="card-title">NASDAQ: AAPL</h4>
          <p class="category">Line Chart with Points</p>
        </div>
        <div class="card-content">
          <div id="chartStock" class="ct-chart"></div>
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <div class="card">
        <div class="card-header">
          <h4 class="card-title">Views</h4>
          <p class="category">Bar Chart</p>
        </div>
        <div class="card-content">
          <div id="chartViews" class="ct-chart"></div>
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <div class="card">
        <div class="card-header">
          <h4 class="card-title">Activity</h4>
          <p class="category">Multiple Bars Chart</p>
        </div>
        <div class="card-content">
          <div id="chartActivity" class="ct-chart"></div>
        </div>
      </div>
    </div>
  </div>
</template>
<script>
  export default {
    data () {
      return {
        $Chartist: null
      }
    },
    methods: {
      initPerformanceChart () {
        const dataPerformance = {
          labels: ['6pm', '9pm', '11pm', '2am', '4am', '8am', '2pm', '5pm', '8pm', '11pm', '4am'],
          series: [
            [1, 6, 8, 7, 4, 7, 8, 12, 16, 17, 14, 13]
          ]
        }

        const optionsPerformance = {
          showPoint: false,
          lineSmooth: true,
          axisX: {
            showGrid: false,
            showLabel: true
          },
          axisY: {
            offset: 40

          },
          low: 0,
          high: 16,
          height: '250px'
        }

        this.$Chartist.Line('#chartPerformance', dataPerformance, optionsPerformance)
      },
      initActivityChart () {
        const data = {
          labels: ['Jan', 'Feb', 'Mar', 'Apr', 'Mai', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
          series: [
            [542, 443, 320, 780, 553, 453, 326, 434, 568, 610, 756, 895],
            [412, 243, 280, 580, 453, 353, 300, 364, 368, 410, 636, 695]
          ]
        }

        const options = {
          seriesBarDistance: 10,
          axisX: {
            showGrid: false
          },
          height: '250px'
        }

        const responsiveOptions = [
          ['screen and (max-width: 640px)', {
            seriesBarDistance: 5,
            axisX: {
              labelInterpolationFnc (value) {
                return value[0]
              }
            }
          }]
        ]

        this.$Chartist.Bar('#chartActivity', data, options, responsiveOptions)
      },
      initStockChart () {
        const dataStock = {
          labels: ['\'07', '\'08', '\'09', '\'10', '\'11', '\'12', '\'13', '\'14', '\'15'],
          series: [
            [22.20, 34.90, 42.28, 51.93, 62.21, 80.23, 62.21, 82.12, 102.50, 107.23]
          ]
        }
        const optionsStock = {
          lineSmooth: false,
          axisY: {
            offset: 40,
            labelInterpolationFnc (value) {
              return `$${value}`
            }

          },
          low: 10,
          height: '250px',
          high: 110,
          classNames: {
            point: 'ct-point ct-green',
            line: 'ct-line ct-green'
          }
        }
        this.$Chartist.Line('#chartStock', dataStock, optionsStock)
      },
      initViewsChart () {
        const dataViews = {
          labels: ['Jan', 'Feb', 'Mar', 'Apr', 'Mai', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
          series: [
            [542, 443, 320, 780, 553, 453, 326, 434, 568, 610, 756, 895]
          ]
        }
        const optionsViews = {
          seriesBarDistance: 10,
          classNames: {
            bar: 'ct-bar'
          },
          axisX: {
            showGrid: false
          },
          height: '250px'
        }
        const responsiveOptionsViews = [
          ['screen and (max-width: 640px)', {
            seriesBarDistance: 5,
            axisX: {
              labelInterpolationFnc (value) {
                return value[0]
              }
            }
          }]
        ]
        this.$Chartist.Bar('#chartViews', dataViews, optionsViews, responsiveOptionsViews)
      },
      initCharts () {
        this.initPerformanceChart()
        this.initStockChart()
        this.initViewsChart()
        this.initActivityChart()
      }
    },
    async mounted () {
      const Chartist = await import('chartist')
      this.$Chartist = Chartist
      this.initCharts()
    }
  }
</script>
<style>
</style>

// angular-light-bootstrap-dashboard/src/app/charts/charts.component.ts
import { Component, OnInit } from '@angular/core';
import { LegendItem, ChartType } from '../lbd/lbd-chart/lbd-chart.component';
import * as Chartist from 'chartist';

declare var $:any;

@Component({
    moduleId: module.id,
    selector: 'charts-cmp',
    templateUrl: './charts.component.html'
})

export class ChartsComponent implements OnInit{
    public dataChartType: ChartType;
    public dataChartData: any;
    public dataChartOptions: any;

    public data2ChartType: ChartType;
    public data2ChartData: any;
    public data2ChartOptions: any;

    public emailChartType: ChartType;
    public emailChartData: any;
    public emailChartLegendItems: LegendItem[];

    public hoursChartType: ChartType;
    public hoursChartData: any;
    public hoursChartOptions: any;
    public hoursChartResponsive: any[];
    public hoursChartLegendItems: LegendItem[];

    public viewsChartType: ChartType;
    public viewsChartData: any;
    public viewsChartOptions: any;
    public viewsChartResponsive: any[];

    public activityChartType: ChartType;
    public activityChartData: any;
    public activityChartOptions: any;
    public activityChartResponsive: any[];

    ngOnInit(){
        this.emailChartType = ChartType.Pie;
        this.emailChartData = {
          labels: ['62%', '32%', '6%'],
          series: [62, 32, 6]
        };
        this.emailChartLegendItems = [
          { title: 'Apple', imageClass: 'fa fa-circle text-info' },
          { title: 'Samsung', imageClass: 'fa fa-circle text-danger' },
          { title: 'Windows Phone', imageClass: 'fa fa-circle text-warning' }
        ];

        this.dataChartType = ChartType.Line;
        this.dataChartData = {
            labels: ['6pm','9pm','11pm', '2am', '4am', '8am', '2pm', '5pm', '8pm', '11pm', '4am'],
            series: [
              [1, 6, 8, 7, 4, 7, 8, 12, 16, 17, 14, 13]
            ]
        };
        this.dataChartOptions = {
            showPoint: false,
            lineSmooth: true,
            height: "260px",
            axisX: {
                showGrid: false,
                showLabel: true
            },
            axisY: {
                offset: 40,
            },
            low: 0,
            high: 16
        };

        this.data2ChartType = ChartType.Line;
        this.data2ChartData = {
            labels: ['\'07','\'08','\'09', '\'10', '\'11', '\'12', '\'13', '\'14', '\'15'],
            series: [
                [22.20, 34.90, 42.28, 51.93, 62.21, 80.23, 62.21, 82.12, 102.50, 107.23]
            ]
        };
        this.data2ChartOptions = {
            lineSmooth: false,
            height: "260px",
            axisY: {
            offset: 40,
            labelInterpolationFnc: function(value) {
                return '$' + value;
              }

            },
            low: 10,
            high: 110,
            classNames: {
              point: 'ct-point ct-green',
              line: 'ct-line ct-green'
            }
        };

        this.hoursChartType = ChartType.Line;
        this.hoursChartData = {
            labels: ['\'06','\'07','\'08','\'09', '\'10', '\'11', '\'12', '\'13', '\'14','\'15'],
            series: [
              [287, 385, 490, 554, 586, 698, 695, 752, 788, 846, 944],
              [67, 152, 143,  287, 335, 435, 437, 539, 542, 544, 647],
              [23, 113, 67, 190, 239, 307, 308, 439, 410, 410, 509]
            ]
        };
        this.hoursChartOptions = {
          low: 0,
          high: 1000,
          showArea: false,
          height: '245px',
          axisX: {
            showGrid: true,
          },
          lineSmooth: Chartist.Interpolation.simple({
            divisor: 3
          }),
          showLine: true,
          showPoint: true,
        };
        this.hoursChartResponsive = [
          ['screen and (max-width: 640px)', {
            axisX: {
              labelInterpolationFnc: function (value) {
                return value[0];
              }
            }
          }]
        ];
        this.hoursChartLegendItems = [
          { title: 'Open', imageClass: 'fa fa-circle text-info' },
          { title: 'Click', imageClass: 'fa fa-circle text-danger' },
          { title: 'Click Second Time', imageClass: 'fa fa-circle text-warning' }
        ];

        this.viewsChartType = ChartType.Bar;
        this.viewsChartData = {
            labels: ['Jan', 'Feb', 'Mar', 'Apr', 'Mai', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
            series: [
                [542, 443, 320, 780, 553, 453, 326, 434, 568, 610, 756, 895]
            ]
        };
        this.viewsChartOptions = {
            seriesBarDistance: 10,
            classNames: {
                bar: 'ct-bar ct-azure'
            },
            axisX: {
                showGrid: false
            }
        };
        this.viewsChartResponsive = [
            ['screen and (max-width: 640px)', {
                seriesBarDistance: 5,
                axisX: {
                    labelInterpolationFnc: function (value) {
                        return value[0];
                    }
                }
            }]
        ];

        this.activityChartType = ChartType.Bar;
        this.activityChartData = {
            labels: ['Jan', 'Feb', 'Mar', 'Apr', 'Mai', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
            series: [
              [542, 443, 320, 780, 553, 453, 326, 434, 568, 610, 756, 895],
              [412, 243, 280, 580, 453, 353, 300, 364, 368, 410, 636, 695]
            ]
        };
        this.activityChartOptions = {
            seriesBarDistance: 10,
            axisX: {
                showGrid: false
            },
            height: "245px"
        };
        this.activityChartResponsive = [
            ['screen and (max-width: 640px)', {
              seriesBarDistance: 5,
              axisX: {
                labelInterpolationFnc: function (value) {
                  return value[0];
                }
              }
            }]
        ];
    }
}

<div class="main-content">
    <div class="container-fluid">

        <div class="row">
            <div class="col-md-6">
                <lbd-chart
                  [title]="'24 Hours Performance'"
                  [subtitle]="'Line Chart'"
                  [chartType]="dataChartType"
                  [chartData]="dataChartData"
                  [chartOptions]="dataChartOptions"
                  [withHr]="false">
                </lbd-chart>
            </div>

            <div class="col-md-6">
                <div class="card">
                    <lbd-chart
                      [title]="'NASDAQ: AAPL'"
                      [subtitle]="'Line Chart with Points'"
                      [chartType]="data2ChartType"
                      [chartData]="data2ChartData"
                      [chartOptions]="data2ChartOptions"
                      [withHr]="false">
                    </lbd-chart>
                </div>
            </div>

        </div>
        <div class="row">
            <div class="col-md-6">
                <div class="card">
                    <lbd-chart
                      [title]="'Users Behavior'"
                      [subtitle]="'Multiple Lines Charts'"
                      [chartType]="hoursChartType"
                      [chartData]="hoursChartData"
                      [chartOptions]="hoursChartOptions"
                      [chartResponsive]="hoursChartResponsive"
                      [legendItems]="hoursChartLegendItems"
                      [withHr]="false">
                    </lbd-chart>
                </div>
            </div>

            <div class="col-md-6">
                <div class="card">
                    <lbd-chart
                      [title]="'Public Preferences'"
                      [subtitle]="'Pie Chart'"
                      [chartType]="emailChartType"
                      [chartData]="emailChartData"
                      [legendItems]="emailChartLegendItems"
                      [withHr]="false">
                    </lbd-chart>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <div class="card">
                    <lbd-chart
                      [title]="'Views'"
                      [subtitle]="'Bar Chart'"
                      [chartType]="viewsChartType"
                      [chartData]="viewsChartData"
                      [chartOptions]="viewsChartOptions"
                      [chartResponsive]="viewsChartResponsive"
                      [withHr]="false">
                    </lbd-chart>
                </div>
            </div>

            <div class="col-md-6">
                <div class="card">
                    <lbd-chart
                      [title]="'Activity'"
                      [subtitle]="'Multiple Bars Chart'"
                      [chartType]="activityChartType"
                      [chartData]="activityChartData"
                      [chartOptions]="activityChartOptions"
                      [chartResponsive]="activityChartResponsive"
                      [withHr]="false">
                    </lbd-chart>
                </div>
            </div>
        </div>

    </div>
</div>
