// paper-dashboard-pro-react-v1/src/views/forms/ExtendedForms.jsx
/*!

=========================================================
* Paper Dashboard PRO React - v1.1.0
=========================================================

* Product Page: https://www.creative-tim.com/product/paper-dashboard-pro-react
* Copyright 2019 Creative Tim (https://www.creative-tim.com)

* Coded by Creative Tim

=========================================================

* The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

*/
import React from "react";
// react plugin used to create datetimepicker
import ReactDatetime from "react-datetime";
// react plugin that creates an input with badges
import TagsInput from "react-tagsinput";
// react plugin used to create DropdownMenu for selecting items
import Select from "react-select";
// react plugin used to create switch buttons
import Switch from "react-bootstrap-switch";
// plugin that creates slider
import Slider from "nouislider";

// reactstrap components
import {
  Card,
  CardHeader,
  CardBody,
  CardTitle,
  DropdownToggle,
  DropdownMenu,
  DropdownItem,
  UncontrolledDropdown,
  FormGroup,
  Progress,
  Row,
  Col
} from "reactstrap";

// core components
import ImageUpload from "components/CustomUpload/ImageUpload.jsx";

class ExtendedForms extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      singleSelect: null,
      multipleSelect: null,
      tagsinput: ["Amsterdam", "Washington", "Sydney", "Beijing"]
    };
  }
  componentDidMount() {
    var slider1 = this.refs.slider1;
    var slider2 = this.refs.slider2;
    Slider.create(slider1, {
      start: [40],
      connect: [true, false],
      step: 1,
      range: { min: 0, max: 100 }
    });
    Slider.create(slider2, {
      start: [20, 60],
      connect: [false, true, false],
      step: 1,
      range: { min: 0, max: 100 }
    });
  }
  handleTagsinput = tagsinput => {
    this.setState({ tagsinput });
  };
  render() {
    return (
      <>
        <div className="content">
          <Row>
            <Col md="4">
              <Card>
                <CardHeader>
                  <CardTitle>Datetimepicker</CardTitle>
                </CardHeader>
                <CardBody>
                  <FormGroup>
                    <ReactDatetime
                      inputProps={{
                        className: "form-control",
                        placeholder: "Datetime Picker Here"
                      }}
                    />
                  </FormGroup>
                </CardBody>
              </Card>
            </Col>
            <Col md="4">
              <Card>
                <CardHeader>
                  <CardTitle>Date Picker</CardTitle>
                </CardHeader>
                <CardBody>
                  <FormGroup>
                    <ReactDatetime
                      inputProps={{
                        className: "form-control",
                        placeholder: "Date Picker Here"
                      }}
                      timeFormat={false}
                    />
                  </FormGroup>
                </CardBody>
              </Card>
            </Col>
            <Col md="4">
              <Card>
                <CardHeader>
                  <CardTitle>Time Picker</CardTitle>
                </CardHeader>
                <CardBody>
                  <FormGroup>
                    <ReactDatetime
                      dateFormat={false}
                      inputProps={{
                        className: "form-control",
                        placeholder: "Time Picker Here"
                      }}
                    />
                  </FormGroup>
                </CardBody>
              </Card>
            </Col>
          </Row>
          <Row>
            <Col md="12">
              <Card>
                <CardBody>
                  <Row>
                    <Col md="6">
                      <CardTitle tag="h4">Toggle Buttons</CardTitle>
                      <Row>
                        <Col md="4">
                          <p className="category">Default</p>
                          <Switch onColor="default" offColor="default" />{" "}
                          <Switch
                            defaultValue={false}
                            onColor="default"
                            offColor="default"
                          />
                        </Col>
                        <Col md="4">
                          <p className="category">Plain</p>
                          <Switch
                            offColor="primary"
                            offText=""
                            onColor="primary"
                            onText=""
                          />{" "}
                          <Switch
                            defaultValue={false}
                            offColor="primary"
                            offText=""
                            onColor="primary"
                            onText=""
                          />
                        </Col>
                        <Col md="4">
                          <p className="category">With Icons</p>
                          <Switch
                            offColor="success"
                            offText={<i className="nc-icon nc-simple-remove" />}
                            onColor="success"
                            onText={<i className="nc-icon nc-check-2" />}
                          />{" "}
                          <Switch
                            defaultValue={false}
                            offColor="success"
                            offText={<i className="nc-icon nc-simple-remove" />}
                            onColor="success"
                            onText={<i className="nc-icon nc-check-2" />}
                          />
                        </Col>
                      </Row>
                    </Col>
                    <Col md="6">
                      <CardTitle tag="h4">Customisable Select</CardTitle>
                      <Row>
                        <Col lg="5" md="6" sm="3">
                          <Select
                            className="react-select primary"
                            classNamePrefix="react-select"
                            name="singleSelect"
                            value={this.state.singleSelect}
                            onChange={value =>
                              this.setState({ singleSelect: value })
                            }
                            options={[
                              {
                                value: "",
                                label: "Single Option",
                                isDisabled: true
                              },
                              { value: "2", label: "Foobar" },
                              { value: "3", label: "Is great" }
                            ]}
                            placeholder="Single Select"
                          />
                        </Col>
                        <Col lg="5" md="6" sm="3">
                          <Select
                            className="react-select info"
                            classNamePrefix="react-select"
                            placeholder="Choose City"
                            name="multipleSelect"
                            closeMenuOnSelect={false}
                            isMulti
                            value={this.state.multipleSelect}
                            onChange={value =>
                              this.setState({ multipleSelect: value })
                            }
                            options={[
                              {
                                value: "",
                                label: " Multiple Options",
                                isDisabled: true
                              },
                              { value: "2", label: "Paris " },
                              { value: "3", label: "Bucharest" },
                              { value: "4", label: "Rome" },
                              { value: "5", label: "New York" },
                              { value: "6", label: "Miami " },
                              { value: "7", label: "Piatra Neamt" },
                              { value: "8", label: "Paris " },
                              { value: "9", label: "Bucharest" },
                              { value: "10", label: "Rome" },
                              { value: "11", label: "New York" },
                              { value: "12", label: "Miami " },
                              { value: "13", label: "Piatra Neamt" },
                              { value: "14", label: "Paris " },
                              { value: "15", label: "Bucharest" },
                              { value: "16", label: "Rome" },
                              { value: "17", label: "New York" },
                              { value: "18", label: "Miami " },
                              { value: "19", label: "Piatra Neamt" }
                            ]}
                          />
                        </Col>
                      </Row>
                    </Col>
                  </Row>
                  <Row>
                    <Col md="6">
                      <CardTitle tag="h4">Tags</CardTitle>
                      <TagsInput
                        value={this.state.tagsinput}
                        onChange={this.handleTagsinput}
                        tagProps={{ className: "react-tagsinput-tag success" }}
                      />
                    </Col>
                    <Col md="6">
                      <CardTitle tag="h4">Dropdown &amp; Dropup</CardTitle>
                      <Row>
                        <Col lg="6" md="6" sm="3">
                          <UncontrolledDropdown>
                            <DropdownToggle
                              aria-expanded={false}
                              aria-haspopup={true}
                              caret
                              className="btn-round btn-block"
                              color="primary"
                              data-toggle="dropdown"
                              id="dropdownMenuButton"
                              type="button"
                            >
                              Dropdown
                            </DropdownToggle>
                            <DropdownMenu
                              aria-labelledby="dropdownMenuButton"
                              right
                            >
                              <DropdownItem header tag="div">
                                Dropdown header
                              </DropdownItem>
                              <DropdownItem
                                href="#pablo"
                                onClick={e => e.preventDefault()}
                              >
                                Action
                              </DropdownItem>
                              <DropdownItem
                                href="#pablo"
                                onClick={e => e.preventDefault()}
                              >
                                Another action
                              </DropdownItem>
                              <DropdownItem
                                href="#pablo"
                                onClick={e => e.preventDefault()}
                              >
                                Something else
                              </DropdownItem>
                            </DropdownMenu>
                          </UncontrolledDropdown>
                        </Col>
                        <Col lg="6" md="6" sm="3">
                          <UncontrolledDropdown direction="up">
                            <DropdownToggle
                              caret
                              className="btn-round btn-block"
                              color="primary"
                              data-toggle="dropdown"
                              type="button"
                            >
                              Dropup
                            </DropdownToggle>
                            <DropdownMenu>
                              <DropdownItem header tag="div">
                                Dropdown header
                              </DropdownItem>
                              <DropdownItem
                                href="#pablo"
                                onClick={e => e.preventDefault()}
                              >
                                Action
                              </DropdownItem>
                              <DropdownItem
                                href="#pablo"
                                onClick={e => e.preventDefault()}
                              >
                                Another action
                              </DropdownItem>
                              <DropdownItem
                                href="#pablo"
                                onClick={e => e.preventDefault()}
                              >
                                Something else here
                              </DropdownItem>
                            </DropdownMenu>
                          </UncontrolledDropdown>
                        </Col>
                      </Row>
                    </Col>
                  </Row>
                  <Row>
                    <Col md="6">
                      <CardTitle tag="h4">Progress Bars</CardTitle>
                      <Progress max="100" value="25" />
                      <br />
                      <Progress
                        max="100"
                        value="100"
                        barClassName="progress-bar-danger"
                      />
                      <br />
                      <Progress multi>
                        <Progress
                          bar
                          barClassName="progress-bar-success"
                          max="100"
                          value="15"
                        />
                        <Progress
                          bar
                          barClassName="progress-bar-warning"
                          max="100"
                          value="30"
                        />
                        <Progress
                          bar
                          barClassName="progress-bar-info"
                          max="100"
                          value="20"
                        />
                      </Progress>
                    </Col>
                    <Col md="6">
                      <CardTitle tag="h4">Sliders</CardTitle>
                      <div className="slider slider-success" ref="slider1" />
                      <br />
                      <div className="slider slider-primary" ref="slider2" />
                    </Col>
                  </Row>
                  <Row>
                    <Col md="4" sm="4">
                      <CardTitle tag="h4">Regular Image</CardTitle>
                      <ImageUpload />
                    </Col>
                    <Col md="3" sm="4">
                      <CardTitle tag="h4">Avatar</CardTitle>
                      <ImageUpload avatar />
                    </Col>
                  </Row>
                </CardBody>
              </Card>
              {/* end card */}
            </Col>
          </Row>
        </div>
      </>
    );
  }
}

export default ExtendedForms;

// angular-now-ui-dashboard/src/app/pages/forms/extended-forms/extended-forms.component.ts
import { Component, OnInit, Input, TemplateRef } from "@angular/core";
import { NgbCalendar, NgbDateStruct } from "@ng-bootstrap/ng-bootstrap";
import noUiSlider from "nouislider";

@Component({
  selector: "app-extended-forms",
  templateUrl: "./extended-forms.component.html",
  styleUrls: ["./extended-forms.component.css"]
})
export class ExtendedFormsComponent implements OnInit {
  private tagItems = ["Minimal", "Light", "New", "Friends"];

  private simpleSlider = 40;
  private doubleSlider = [20, 60];

  private state: boolean = true;
  private state1: boolean = true;
  private state2: boolean = true;

  private dropdownList = [];
  private selectedItems = [];
  private dropdownSettings = {};

  private dropdownList1 = [];
  private selectedItems1 = [];
  private dropdownSettings1 = {};

  private model: NgbDateStruct;
  private model1: NgbDateStruct;
  private model2: NgbDateStruct;

  private today = this.calendar.getToday();

  // @Input() footerTemplate: TemplateRef<any>;

  constructor(private calendar: NgbCalendar) {}

  ngOnInit() {
    this.dropdownList = [
      { id: 1, itemName: "Roman" },
      { id: 2, itemName: "Paris" },
      { id: 3, itemName: "Bucharest" },
      { id: 4, itemName: "Rome" },
      { id: 5, itemName: "New York" },
      { id: 6, itemName: "Miami" },
      { id: 7, itemName: "Piatra Neamt" },
      { id: 8, itemName: "Paris" },
      { id: 9, itemName: "Bucharest" },
      { id: 10, itemName: "Rome" },
      { id: 11, itemName: "New York" },
      { id: 12, itemName: "Miami" },
      { id: 13, itemName: "Piatra Neamt" }
    ];
    this.selectedItems = [];
    this.dropdownSettings = {
      singleSelection: false,
      text: "Multiple Select",
      selectAllText: "Select All",
      unSelectAllText: "UnSelect All",
      enableSearchFilter: true,
      classes: ""
    };

    this.dropdownList1 = [
      { id: 1, itemName: "Roman" },
      { id: 2, itemName: "Paris" },
      { id: 3, itemName: "Bucharest" },
      { id: 4, itemName: "Rome" },
      { id: 5, itemName: "New York" },
      { id: 6, itemName: "Miami" },
      { id: 7, itemName: "Piatra Neamt" },
      { id: 8, itemName: "Paris" },
      { id: 9, itemName: "Bucharest" },
      { id: 10, itemName: "Rome" },
      { id: 11, itemName: "New York" },
      { id: 12, itemName: "Miami" },
      { id: 13, itemName: "Piatra Neamt" }
    ];
    this.selectedItems1 = [];
    this.dropdownSettings1 = {
      singleSelection: true,
      text: "Single Select",
      selectAllText: "Select All",
      unSelectAllText: "UnSelect All",
      enableSearchFilter: true,
      classes: ""
    };

    var slider = document.getElementById("sliderRegular");

    noUiSlider.create(slider, {
      start: 40,
      connect: [true, false],
      range: {
        min: 0,
        max: 100
      }
    });

    var slider2 = document.getElementById("sliderDouble");

    noUiSlider.create(slider2, {
      start: [20, 60],
      connect: true,
      range: {
        min: 0,
        max: 100
      }
    });
  }
  onItemSelect(item: any) {
    console.log(item);
    console.log(this.selectedItems);
  }
  OnItemDeSelect(item: any) {
    console.log(item);
    console.log(this.selectedItems);
  }
  onSelectAll(items: any) {
    console.log(items);
  }
  onDeSelectAll(items: any) {
    console.log(items);
  }
}

<div class="panel-header panel-header-sm"></div>
<div class="main-content">
  <div class="row">
    <div class="col-md-4">
      <div class="card ">
        <div class="card-header ">
          <h4 class="card-title">Date Picker Primary</h4>
        </div>
        <div class="card-body ">
          <div class="datepicker-container">
            <div class="form-group">
              <input
                class="form-control datetimepicker"
                placeholder="yyyy-mm-dd"
                name="dp"
                [(ngModel)]="model"
                ngbDatepicker
                #d="ngbDatepicker"
                (click)="d.toggle()"
                data-color="orange"
              />
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-md-4">
      <div class="card ">
        <div class="card-header ">
          <h4 class="card-title">Date Picker Default</h4>
        </div>
        <div class="card-body ">
          <div class="datepicker-container">
            <div class="form-group">
              <input
                class="form-control datetimepicker"
                placeholder="yyyy-mm-dd"
                name="dp1"
                [(ngModel)]="model1"
                ngbDatepicker
                #d1="ngbDatepicker"
                (click)="d1.toggle()"
              />
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-md-4">
      <div class="card ">
        <div class="card-header "><h4 class="card-title">With Footer</h4></div>
        <div class="card-body ">
          <div class="datepicker-container">
            <div class="form-group">
              <input
                class="form-control datetimepicker"
                placeholder="yyyy-mm-dd"
                name="dp2"
                [(ngModel)]="model2"
                ngbDatepicker
                [footerTemplate]="footerTemplate"
                #d2="ngbDatepicker"
                (click)="d2.toggle()"
                data-color="white"
              />
            </div>
          </div>
          <ng-template #footerTemplate>
            <hr class="my-0" />
            <button
              class="btn btn-primary btn-sm m-2 float-left"
              (click)="model2 = today; d2.close()"
            >
              Today
            </button>
            <button
              class="btn btn-secondary btn-sm m-2 float-right"
              (click)="d2.close()"
            >
              Close
            </button>
          </ng-template>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <div class="card">
        <div class="card-body">
          <div class="row">
            <div class="col-md-6">
              <h4 class="card-title">Toggle Buttons</h4>
              <div class="row">
                <div class="col-md-4">
                  <p class="category">Default</p>
                  <bSwitch [switch-on-color]="'primary'" [(ngModel)]="state">
                  </bSwitch>
                  <bSwitch [switch-on-color]="'primary'"> </bSwitch>
                </div>
                <div class="col-md-4">
                  <p class="category">Plain</p>
                  <bSwitch
                    [switch-on-color]="'primary'"
                    [(ngModel)]="state1"
                    [switch-off-text]="' '"
                    [switch-on-text]="' '"
                  >
                  </bSwitch>
                  <bSwitch
                    [switch-on-color]="'primary'"
                    [switch-off-text]="' '"
                    [switch-on-text]="' '"
                  >
                  </bSwitch>
                </div>
                <div class="col-md-4">
                  <p class="category">With Icons</p>
                  <bSwitch
                    [switch-on-color]="'primary'"
                    [(ngModel)]="state2"
                    switch-on-text="<i class='now-ui-icons ui-1_check'></i>"
                    switch-off-text="<i class='now-ui-icons ui-1_simple-remove'></i>"
                  >
                  </bSwitch>
                  <bSwitch
                    [switch-on-color]="'primary'"
                    switch-on-text="<i class='now-ui-icons ui-1_check'></i>"
                    switch-off-text="<i class='now-ui-icons ui-1_simple-remove'></i>"
                  >
                  </bSwitch>
                </div>
              </div>
            </div>
            <div class="col-md-6">
              <h4 class="card-title">Customisable Select</h4>
              <div class="row">
                <div class="col-lg-5 col-md-8 col-sm-5 mb-3">
                  <angular2-multiselect
                    [data]="dropdownList1"
                    [(ngModel)]="selectedItems1"
                    [settings]="dropdownSettings1"
                    (onSelect)="onItemSelect($event)"
                    (onDeSelect)="OnItemDeSelect($event)"
                    (onSelectAll)="onSelectAll($event)"
                    (onDeSelectAll)="onDeSelectAll($event)"
                  >
                  </angular2-multiselect>
                </div>
                <div class="col-lg-5 col-md-8 col-sm-5">
                  <angular2-multiselect
                    [data]="dropdownList"
                    [(ngModel)]="selectedItems"
                    [settings]="dropdownSettings"
                    (onSelect)="onItemSelect($event)"
                    (onDeSelect)="OnItemDeSelect($event)"
                    (onSelectAll)="onSelectAll($event)"
                    (onDeSelectAll)="onDeSelectAll($event)"
                  >
                  </angular2-multiselect>
                </div>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-md-6">
              <h4 class="card-title">Tags</h4>
              <tag-input
                [(ngModel)]="tagItems"
                theme="regular-theme"
              ></tag-input>
            </div>
            <div class="col-md-6">
              <h4 class="card-title">Dropdown & Dropup</h4>
              <div class="row">
                <div class="col-lg-4 col-md-6 col-sm-3">
                  <div class="" ngbDropdown>
                    <button
                      class=" btn btn-primary btn-round btn-block"
                      type="button"
                      id="dropdownMenuButton"
                      data-toggle="dropdown"
                      aria-haspopup="true"
                      aria-expanded="false"
                      ngbDropdownToggle
                    >
                      Dropdown
                    </button>
                    <div
                      class=""
                      aria-labelledby="dropdownMenuButton"
                      ngbDropdownMenu
                    >
                      <h6 class="dropdown-header">Dropdown header</h6>
                      <a class="dropdown-item" href="#">Action</a>
                      <a class="dropdown-item" href="#">Another action</a>
                      <a class="dropdown-item" href="#">Something else here</a>
                    </div>
                  </div>
                </div>
                <div class="col-lg-4 col-md-6 col-sm-3">
                  <div class="" placement="top-left" ngbDropdown>
                    <button
                      type="button"
                      class="dropdown-toggle btn btn-primary btn-round btn-block"
                      data-toggle="dropdown"
                      ngbDropdownToggle
                    >
                      Dropup
                    </button>
                    <div class="" ngbDropdownMenu>
                      <h6 class="dropdown-header">Dropdown header</h6>
                      <a class="dropdown-item" href="#">Action</a>
                      <a class="dropdown-item" href="#">Another action</a>
                      <a class="dropdown-item" href="#">Something else here</a>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-md-6">
              <h4 class="card-title">Progress Bars</h4>
              <div class="progress-container">
                <span class="progress-badge">Default</span>
                <div class="progress">
                  <div
                    class="progress-bar"
                    role="progressbar"
                    aria-valuenow="60"
                    aria-valuemin="0"
                    aria-valuemax="100"
                    style="width: 25%;"
                  >
                    <span class="progress-value">25%</span>
                  </div>
                </div>
              </div>
              <div class="progress-container progress-primary">
                <span class="progress-badge">Primary</span>
                <div class="progress">
                  <div
                    class="progress-bar progress-bar-warning"
                    role="progressbar"
                    aria-valuenow="60"
                    aria-valuemin="0"
                    aria-valuemax="100"
                    style="width: 60%;"
                  >
                    <span class="progress-value">60%</span>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-md-6">
              <h4 class="card-title">Sliders</h4>
              <div id="sliderRegular" class="slider"></div>
              <br />
              <div id="sliderDouble" class="slider slider-primary"></div>
            </div>
          </div>
          <div class="row">
            <div class="col-md-6">
              <div class="row">
                <div class="col-md-6">
                  <h4 class="card-title">Regular Image</h4>
                  <app-image-upload></app-image-upload>
                </div>
                <div class="col-md-6">
                  <h4 class="card-title">Avatar</h4>
                  <app-image-upload [isRound]="true"></app-image-upload>
                </div>
              </div>
            </div>
            <div class="col-md-4">
              <h4 class="card-title">Single File</h4>
              <app-file-input></app-file-input>

              <h4 class="card-title">Multiple File</h4>
              <app-file-input [multiple]="true"></app-file-input>
            </div>
          </div>
        </div>
      </div>
      <!-- end card -->
    </div>
  </div>
</div>
