// light-bootstrap-dashboard-pro-angular-v1/src/app/forms/extendedforms/extendedforms.component.ts
import { Component, OnInit } from '@angular/core';

declare var $:any;

@Component({
    moduleId: module.id,
    selector: 'extendedforms-cmp',
    templateUrl: 'extendedforms.component.html'
})

export class ExtendedFormsComponent implements OnInit{
    regularItems = ['Pizza', 'Pasta', 'Parmesan'];
    filledItems = ['Pizza', 'Pasta', 'Parmesan'];
    simpleSlider = 40;
    doubleSlider = [20, 60];
    state_default: boolean = true;
    state_plain: boolean = true;
    state_with_icons: boolean = true;

    ngOnInit() {
        //  Activate the tooltips
        $('[rel="tooltip"]').tooltip();

        //  Init Bootstrap Select Picker
        if($(".selectpicker").length != 0){
            $(".selectpicker").selectpicker({
                iconBase: "fa",
                tickIcon: "fa-check"
            });
        }

        $('.datetimepicker').datetimepicker({
            icons: {
                time: "fa fa-clock-o",
                date: "fa fa-calendar",
                up: "fa fa-chevron-up",
                down: "fa fa-chevron-down",
                previous: 'fa fa-chevron-left',
                next: 'fa fa-chevron-right',
                today: 'fa fa-screenshot',
                clear: 'fa fa-trash',
                close: 'fa fa-remove'
            }
         });

         $('.datepicker').datetimepicker({
            format: 'MM/DD/YYYY',    //use this format if you want the 12hours timpiecker with AM/PM toggle
            icons: {
                time: "fa fa-clock-o",
                date: "fa fa-calendar",
                up: "fa fa-chevron-up",
                down: "fa fa-chevron-down",
                previous: 'fa fa-chevron-left',
                next: 'fa fa-chevron-right',
                today: 'fa fa-screenshot',
                clear: 'fa fa-trash',
                close: 'fa fa-remove'
            }
         });

         $('.timepicker').datetimepicker({
//          format: 'H:mm',    // use this format if you want the 24hours timepicker
            format: 'h:mm A',    //use this format if you want the 12hours timpiecker with AM/PM toggle
            icons: {
                time: "fa fa-clock-o",
                date: "fa fa-calendar",
                up: "fa fa-chevron-up",
                down: "fa fa-chevron-down",
                previous: 'fa fa-chevron-left',
                next: 'fa fa-chevron-right',
                today: 'fa fa-screenshot',
                clear: 'fa fa-trash',
                close: 'fa fa-remove'
            }

         });
     }
}

<div class="main-content">
<div class="container-fluid">

    <div class="card">
        <div class="content">

            <div class="row">
                <div class="col-md-4">
                    <h4 class="title">Datetime Picker</h4>
                    <div class="form-group">
                        <input type="text" class="form-control datetimepicker" placeholder="Datetime Picker Here"/>
                    </div>
                </div>
                <div class="col-md-4">
                    <h4 class="title">Date Picker</h4>
                    <div class="form-group">
                        <input type="text" class="form-control datepicker" placeholder="Date Picker Here"/>
                    </div>
                </div>
                <div class="col-md-4">
                    <h4 class="title">Time Picker</h4>
                    <div class="form-group">
                        <input type="text" class="form-control timepicker" placeholder="Time Picker Here"/>
                    </div>
                </div>
            </div>

            <br /><br />

            <div class="row">
                <div class="col-md-6">
                    <legend>Switches</legend>

                    <div class="col-md-4">
                        <p class="category">Default</p>
                        <bSwitch
                            [switch-on-color]="'primary'">
                        </bSwitch>
                        <bSwitch
                            [switch-on-color]="'primary'"
                            [(ngModel)]="state_default">
                        </bSwitch>
                    </div>

                    <div class="col-md-4">
                        <p class="category">Plain</p>
                        <bSwitch
                            [switch-on-color]="'primary'"
                            [switch-off-text]="' '"
                            [switch-on-text]="' '">
                        </bSwitch>
                        <bSwitch
                            [switch-on-color]="'primary'"
                            [switch-off-text]="' '"
                            [switch-on-text]="' '"
                            [(ngModel)]="state_plain">
                        </bSwitch>
                    </div>


                    <div class="col-md-4">
                        <p class="category">With Icons</p>
                        <bSwitch
                            [switch-on-color]="'primary'"
                            [switch-off-text]="'&#x2718;'"
                            [switch-on-text]="'&#x2714;'">
                        </bSwitch>
                        <bSwitch
                            [switch-on-color]="'primary'"
                            [switch-off-text]="'&#x2718;'"
                            [switch-on-text]="'&#x2714;'"
                            [(ngModel)]="state_with_icons">
                        </bSwitch>
                    </div>
                </div>

            </div>
            <br /><br />

            <div class="row">
                <div class="col-md-6">
                    <legend>Tags</legend>
                    Regular: <tag-input [(ngModel)]='regularItems' class="tags-azure"></tag-input>
                    Filled: <tag-input [(ngModel)]='filledItems' class='tags-azure tags-fill'></tag-input>
                </div>

                <div class="col-md-6">
                    <legend>Customisable Select</legend>
                        <div class="row">
                            <div class="col-md-6">
                                <select name="cities" class="selectpicker" data-title="Single Select" data-style="btn-default btn-block" data-menu-style="dropdown-blue">
                                    <option value="id">Bahasa Indonesia</option>
                                    <option value="ms">Bahasa Melayu</option>
                                    <option value="ca">Català</option>
                                    <option value="da">Dansk</option>
                                    <option value="de">Deutsch</option>
                                    <option value="en">English</option>
                                    <option value="es">Español</option>
                                    <option value="el">Eλληνικά</option>
                                    <option value="fr">Français</option>
                                    <option value="it">Italiano</option>
                                    <option value="hu">Magyar</option>
                                    <option value="nl">Nederlands</option>
                                    <option value="no">Norsk</option>
                                    <option value="pl">Polski</option>
                                    <option value="pt">Português</option>
                                    <option value="fi">Suomi</option>
                                    <option value="sv">Svenska</option>
                                    <option value="tr">Türkçe</option>
                                    <option value="is">Íslenska</option>
                                    <option value="cs">Čeština</option>
                                    <option value="ru">Русский</option>
                                    <option value="th">ภาษาไทย</option>
                                    <option value="zh">中文 (简体)</option>
                                    <option value="zh-TW">中文 (繁體)</option>
                                    <option value="ja">日本語</option>
                                    <option value="ko">한국어</option>
                                </select>
                            </div>
                            <div class="col-md-6">
                                <select multiple data-title="Multiple Select" name="currency" class="selectpicker" data-style="btn-info btn-fill btn-block" data-menu-style="dropdown-blue">
                                    <option value="ARS">ARS</option>
                                    <option value="AUD">AUD</option>
                                    <option value="BRL">BRL</option>
                                    <option value="CAD">CAD</option>
                                    <option value="CHF">CHF</option>
                                    <option value="CNY">CNY</option>
                                    <option value="CZK">CZK</option>
                                    <option value="DKK">DKK</option>
                                    <option value="EUR">EUR</option>
                                    <option value="GBP">GBP</option>
                                    <option value="HKD">HKD</option>
                                    <option value="HUF">HUF</option>
                                    <option value="IDR">IDR</option>
                                    <option value="ILS">ILS</option>
                                    <option value="INR">INR</option>
                                    <option value="JPY">JPY</option>
                                    <option value="KRW">KRW</option>
                                    <option value="MYR">MYR</option>
                                    <option value="MXN">MXN</option>
                                    <option value="NOK">NOK</option>
                                    <option value="NZD">NZD</option>
                                    <option value="PHP">PHP</option>
                                    <option value="PLN">PLN</option>
                                    <option value="RUB">RUB</option>
                                    <option value="SEK">SEK</option>
                                    <option value="SGD">SGD</option>
                                    <option value="TWD">TWD</option>
                                    <option value="USD">USD</option>
                                    <option value="VND">VND</option>
                                    <option value="ZAR">ZAR</option>
                                </select>
                            </div>
                        </div>
                </div>
            </div>

            <br /><br />

            <div class="row">
                <div class="col-md-6">
                    <legend>Progress Bars</legend>

                    <div class="progress">
                        <div class="progress-bar" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 30%;">
                            <span class="sr-only">60% Complete</span>
                        </div>
                    </div>

                    <div class="progress">
                        <div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 60%;">
                            <span class="sr-only">60% Complete</span>
                        </div>
                    </div>

                    <div class="progress">
                        <div class="progress-bar progress-bar-success" style="width: 35%">
                            <span class="sr-only">35% Complete (success)</span>
                        </div>
                        <div class="progress-bar progress-bar-warning" style="width: 20%">
                            <span class="sr-only">20% Complete (warning)</span>
                        </div>
                        <div class="progress-bar progress-bar-danger" style="width: 10%">
                            <span class="sr-only">10% Complete (danger)</span>
                        </div>
                    </div>
                </div>

                <div class="col-md-6">
                    <legend>Sliders</legend>
                    <nouislider [connect]="false" [min]="0" [max]="100" [step]="1" [(ngModel)]="simpleSlider" [tooltips]="true"></nouislider>
                    <br>
                    <nouislider [connect]="true" [min]="0" [max]="100" [step]="1" [(ngModel)]="doubleSlider" [tooltips]="true"></nouislider>
                </div>

            </div>

        </div>
    </div> <!-- end card -->

</div>
</div>

// vue-now-ui-dashboard/src/pages/Dashboard/Forms/ExtendedForms.vue
<template>
  <div class="extended-forms">
    <div class="row">
      <div class="col-md-4">
        <card>
          <h4 slot="header" class="card-title">Datetimepicker</h4>
          <fg-input>
            <el-date-picker
              type="datetime"
              placeholder="Date Time Picker"
              v-model="dateTimePicker">
            </el-date-picker>
          </fg-input>
        </card>
      </div>
      <div class="col-md-4">
        <card>
          <h4 slot="header" class="card-title">Date Picker</h4>
          <fg-input>
            <el-date-picker
              type="date"
              placeholder="Date Picker"
              v-model="datePicker">
            </el-date-picker>
          </fg-input>
        </card>
      </div>
      <div class="col-md-4">
        <card>
          <h4 slot="header" class="card-title">Time Picker</h4>
          <fg-input>
            <el-time-select
              placeholder="Time Picker"
              v-model="timePicker">
            </el-time-select>
          </fg-input>
        </card>
      </div>
    </div>
    <card>
      <div class="col-12">
        <div class="row">
          <div class="col-md-6">
            <h4 class="card-title">Toggle Buttons</h4>
            <div class="row">
              <div class="col-md-4">
                <p class="category">Default</p>
                <n-switch v-model="switches.defaultOn" type="primary" on-text="ON" off-text="OFF"></n-switch>
                <n-switch v-model="switches.defaultOff" type="primary" on-text="ON" off-text="OFF"></n-switch>
              </div>
              <div class="col-md-4">
                <p class="category">Plain</p>
                <n-switch v-model="switches.plainOn"></n-switch>
                <n-switch v-model="switches.plainOff"></n-switch>

              </div>
              <div class="col-md-4">
                <p class="category">With Icons</p>
                <n-switch v-model="switches.withIconsOn">
                  <i class="now-ui-icons ui-1_check" slot="on"></i>
                  <i class="now-ui-icons ui-1_simple-remove" slot="off"></i>
                </n-switch>
                <n-switch v-model="switches.withIconsOff">
                  <i class="now-ui-icons ui-1_check" slot="on"></i>
                  <i class="now-ui-icons ui-1_simple-remove" slot="off"></i>
                </n-switch>
              </div>
            </div>
          </div>
          <div class="col-md-6">
            <h4 class="card-title">Customisable Select</h4>
            <div class="row">
              <div class="col-md-6">
                <el-select class="select-primary"
                           size="large"
                           placeholder="Single Select"
                           v-model="selects.simple">
                  <el-option v-for="option in selects.countries"
                             class="select-primary"
                             :value="option.value"
                             :label="option.label"
                             :key="option.label">
                  </el-option>
                </el-select>
              </div>
              <div class="col-md-6">
                <el-select multiple class="select-info"
                           size="large"
                           v-model="selects.multiple"
                           collapse-tags
                           placeholder="Multiple Select">
                  <el-option v-for="option in selects.countries"
                             class="select-info"
                             :value="option.value"
                             :label="option.label"
                             :key="option.label">
                  </el-option>
                </el-select>
              </div>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-6">
            <h4 class="card-title">Tags</h4>

            <el-tag
              :key="tag"
              v-for="tag in tags.dynamicTags"
              size="small"
              type="danger"
              :closable="true"
              :close-transition="false"
              @close="handleClose(tag)"
            >
              {{tag}}
            </el-tag>

            <input type="text" placeholder="New Tag"
                   class="form-control input-new-tag"
                   v-model="tags.inputValue"
                   ref="saveTagInput"
                   size="mini"
                   @keyup.enter="handleInputConfirm"
                   @blur="handleInputConfirm"/>
          </div>
          <div class="col-md-6">
            <h4 class="card-title">Dropdown &amp; Dropup</h4>

            <div class="row">
              <div class="col-xl-4 col-md-6">
                <drop-down>
                  <n-button slot="title"
                            class="dropdown-toggle"
                            data-toggle="dropdown"
                            aria-haspopup="true"
                            aria-expanded="false"
                            type="primary"
                            block
                            round>
                    Dropdown
                  </n-button>
                  <h6 class="dropdown-header">Dropdown header</h6>
                  <a class="dropdown-item" href="#">Action</a>
                  <a class="dropdown-item" href="#">Another action</a>
                  <a class="dropdown-item" href="#">Something else here</a>
                </drop-down>
              </div>

              <div class="col-xl-4 col-md-6">
                <drop-down direction="up">
                  <n-button slot="title"
                            class="dropdown-toggle"
                            data-toggle="dropdown"
                            aria-haspopup="true"
                            aria-expanded="false"
                            type="primary"
                            block
                            round>
                    Dropup
                  </n-button>
                  <h6 class="dropdown-header">Dropdown header</h6>
                  <a class="dropdown-item" href="#">Action</a>
                  <a class="dropdown-item" href="#">Another action</a>
                  <a class="dropdown-item" href="#">Something else here</a>
                </drop-down>
              </div>
            </div>

          </div>

        </div>
        <div class="row">
          <div class="col-md-6">
            <h4 class="card-title">Progress Bars</h4>
            <n-progress label="Default" :value="25" show-value></n-progress>
            <n-progress label="Primary" :value="60" type="primary" show-value></n-progress>
          </div>
          <div class="col-md-6">
            <h4 class="card-title">Sliders</h4>
            <slider v-model="sliders.simple">
            </slider>
            <br>
            <slider v-model="sliders.rangeSlider"
                    type="primary"
                    :connect="true">
            </slider>
            <br>
          </div>
        </div>
      </div>
    </card> <!-- end card -->
  </div>
</template>
<script>
import {
  TimeSelect,
  DatePicker,
  Tag,
  Input,
  Button,
  Select,
  Option
} from 'element-ui';
import {
  Progress,
  Switch,
  FormGroupInput as FgInput,
  Slider
} from 'src/components/index';

export default {
  components: {
    FgInput,
    [DatePicker.name]: DatePicker,
    [TimeSelect.name]: TimeSelect,
    [Tag.name]: Tag,
    [Input.name]: Input,
    [Button.name]: Button,
    [Option.name]: Option,
    [Select.name]: Select,
    [Switch.name]: Switch,
    [Progress.name]: Progress,
    Slider
  },
  data() {
    return {
      enabledRadio: '2',
      disabledRadio: '2',
      switches: {
        defaultOn: true,
        defaultOff: false,
        plainOn: true,
        plainOff: false,
        withIconsOn: true,
        withIconsOff: false
      },
      sliders: {
        simple: 30,
        rangeSlider: [20, 60]
      },
      selects: {
        simple: '',
        countries: [
          { value: 'Bahasa Indonesia', label: 'Bahasa Indonesia' },
          { value: 'Bahasa Melayu', label: 'Bahasa Melayu' },
          { value: 'Català', label: 'Català' },
          { value: 'Dansk', label: 'Dansk' },
          { value: 'Deutsch', label: 'Deutsch' },
          { value: 'English', label: 'English' },
          { value: 'Español', label: 'Español' },
          { value: 'Eλληνικά', label: 'Eλληνικά' },
          { value: 'Français', label: 'Français' },
          { value: 'Italiano', label: 'Italiano' },
          { value: 'Magyar', label: 'Magyar' },
          { value: 'Nederlands', label: 'Nederlands' },
          { value: 'Norsk', label: 'Norsk' },
          { value: 'Polski', label: 'Polski' },
          { value: 'Português', label: 'Português' },
          { value: 'Suomi', label: 'Suomi' },
          { value: 'Svenska', label: 'Svenska' },
          { value: 'Türkçe', label: 'Türkçe' },
          { value: 'Íslenska', label: 'Íslenska' },
          { value: 'Čeština', label: 'Čeština' },
          { value: 'Русский', label: 'Русский' },
          { value: 'ภาษาไทย', label: 'ภาษาไทย' },
          { value: '中文 (简体)', label: '中文 (简体)' },
          { value: 'W">中文 (繁體)', label: 'W">中文 (繁體)' },
          { value: '日本語', label: '日本語' },
          { value: '한국어', label: '한국어' }
        ],
        multiple: 'ARS'
      },
      tags: {
        dynamicTags: ['Tag 1', 'Tag 2', 'Tag 3'],
        inputVisible: false,
        inputValue: ''
      },
      datePicker: '',
      dateTimePicker: '',
      timePicker: ''
    };
  },
  methods: {
    handleClose(tag) {
      this.tags.dynamicTags.splice(this.tags.dynamicTags.indexOf(tag), 1);
    },

    showInput() {
      this.tags.inputVisible = true;
      this.$nextTick(() => {
        this.$refs.saveTagInput.$refs.input.focus();
      });
    },

    handleInputConfirm() {
      let inputValue = this.tags.inputValue;
      if (inputValue) {
        this.tags.dynamicTags.push(inputValue);
      }
      this.tags.inputVisible = false;
      this.tags.inputValue = '';
    }
  }
};
</script>
<style>
.extended-forms .el-select {
  width: 100%;
  margin-bottom: 30px;
}

.extended-forms .progress {
  margin-bottom: 30px;
}
</style>
