// angular-now-ui-dashboard/src/app/pages/forms/validation-forms/validation-forms.component.ts
import { Component, OnInit } from "@angular/core";
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { MustMatch } from "./password-validator.component";

@Component({
  selector: "app-validation-forms",
  templateUrl: "./validation-forms.component.html",
  styleUrls: ["./validation-forms.component.css"]
})
export class ValidationFormsComponent implements OnInit {
  private registerForm: FormGroup;
  private register = false;

  private loginForm: FormGroup;
  private login = false;

  private typeForm: FormGroup;
  private type = false;

  private rangeForm: FormGroup;
  private range = false;

  private focusTouched;
  private focusTouched1;
  private focusTouched2;
  private focusTouched3;
  private focusTouched4;
  private focusTouched5;
  private focusTouched6;
  private focusTouched7;
  private focusTouched8;
  private focusTouched9;
  private focusTouched10;
  private focusTouched11;
  private focusTouched12;
  private focusTouched13;
  private focusTouched14;
  private focusTouched15;
  private focusTouched16;
    constructor(private formBuilder: FormBuilder) { }

    ngOnInit() {
        this.registerForm = this.formBuilder.group({
            email: ['', [Validators.required, Validators.email]],
            password: ['', [Validators.required, Validators.minLength(6)]],
            confirmPassword: ['', Validators.required]
        }, {
            validator: MustMatch('password', 'confirmPassword')
        });
        this.loginForm = this.formBuilder.group({
          fullName: ['', Validators.required],
          email: ['', [Validators.required, Validators.email]],
          password: ['', [Validators.required, Validators.minLength(6)]],
        });
        this.typeForm = this.formBuilder.group({
          requiredText: ['', [Validators.required, Validators.minLength(2)]],
          email: ['', [Validators.required, Validators.email]],
          number: ['', [Validators.required, Validators.pattern("^-?[0-9]+$")]],
          url: ['', [Validators.required, Validators.pattern(/^(?:(?:(?:https?|ftp):)?\/\/)(?:\S+(?::\S*)?@)?(?:(?!(?:10|127)(?:\.\d{1,3}){3})(?!(?:169\.254|192\.168)(?:\.\d{1,3}){2})(?!172\.(?:1[6-9]|2\d|3[0-1])(?:\.\d{1,3}){2})(?:[1-9]\d?|1\d\d|2[01]\d|22[0-3])(?:\.(?:1?\d{1,2}|2[0-4]\d|25[0-5])){2}(?:\.(?:[1-9]\d?|1\d\d|2[0-4]\d|25[0-4]))|(?:(?:[a-z\u00a1-\uffff0-9]-*)*[a-z\u00a1-\uffff0-9]+)(?:\.(?:[a-z\u00a1-\uffff0-9]-*)*[a-z\u00a1-\uffff0-9]+)*(?:\.(?:[a-z\u00a1-\uffff]{2,})).?)(?::\d{2,5})?(?:[\/?#]\S*)?$/i)]],
          idSource: ['', [Validators.required, Validators.minLength(2)]],
          idDestination: ['', Validators.required]
          }, {
              validator: MustMatch('idSource', 'idDestination')
            });
          this.rangeForm = this.formBuilder.group({
            minLength: ['', [Validators.required, Validators.minLength(5)]],
            maxLength: ['', [Validators.required, Validators.maxLength(5)]],
            rangeD: ['', [Validators.required, Validators.min(6), Validators.max(10), Validators.pattern("^-?[0-9]+$")]],
            minValue: ['', [Validators.required, Validators.min(6), Validators.pattern("^-?[0-9]+$")]],
            maxValue: ['', [Validators.required, Validators.max(6), Validators.pattern("^-?[0-9]+$")]]
          })
    }

    // convenience getter for easy access to form fields
    // Register form functions
    get registerF() {
      return this.registerForm.controls;
    }

    onRegister() {
        this.register = true;

        // stop here if form is invalid
        if (this.registerForm.invalid) {
            return;
        }

        alert('SUCCESS!! :-)\n\n' + JSON.stringify(this.registerForm.value))
    }
    // Login form functions
    get loginF() {
      return this.loginForm.controls;
    }

    onLogin() {
        this.login = true;

        // stop here if form is invalid
        if (this.loginForm.invalid) {
            return;
        }

        alert('SUCCESS!! :-)\n\n' + JSON.stringify(this.loginForm.value))
    }

    // Type form functions
    get typeF() {
      return this.typeForm.controls;
    }

    onType() {
        this.type = true;

        // stop here if form is invalid
        if (this.typeForm.invalid) {
            return;
        }

        alert('SUCCESS!! :-)\n\n' + JSON.stringify(this.typeForm.value))
    }

    // Range form functions
    get rangeF() {
      return this.rangeForm.controls;
    }

    onRange() {
        this.range = true;

        // stop here if form is invalid
        if (this.rangeForm.invalid) {
            return;
        }

        alert('SUCCESS!! :-)\n\n' + JSON.stringify(this.rangeForm.value))
    }
}

<div class="panel-header panel-header-sm"></div>
<div class="main-content">
  <div class="row">
    <div class="col-md-6">
      <form [formGroup]="registerForm" (ngSubmit)="onRegister()">
        <div class="card ">
          <div class="card-header ">
            <h4 class="card-title">Register Form</h4>
          </div>
          <div class="card-body ">
            <div class="form-group has-label" [ngClass]="{ 'has-danger': ((focusTouched || register) && registerF.email.errors) || (registerF.email.value != '' && registerF.email.errors), 'has-success': !registerF.email.errors }" >
              <label> Email Address * </label>
                <input type="text" formControlName="email" (focus)="focusTouched = true" class="form-control" />
            </div>
            <div class="form-group has-label" [ngClass]="{ 'has-danger': ((focusTouched1 || register) && registerF.password.errors) || (registerF.password.value != '' && registerF.password.errors), 'has-success': !(registerF.password.errors) }">
              <label> Password * </label>
                <input type="password" formControlName="password" (focus)="focusTouched1 = true" class="form-control"  />
            </div>
            <div class="form-group has-label"  [ngClass]="{ 'has-danger': ((focusTouched2 || register) && registerF.confirmPassword.errors) || (registerF.confirmPassword.value != '' && registerF.confirmPassword.errors), 'has-success': !registerF.confirmPassword.errors }">
                <label>Confirm Password *</label>
                <input type="password" formControlName="confirmPassword" (focus)="focusTouched2 = true" class="form-control" />
            </div>
            <div class="category form-category">* Required fields</div>
          </div>
          <div class="card-footer text-right">
            <div class="form-check pull-left">
              <label class="form-check-label">
                <input
                  class="form-check-input"
                  type="checkbox"
                  name="optionCheckboxes"
                  required
                />
                <span class="form-check-sign"></span> Subscribe to newsletter
              </label>
            </div>
            <button
              type="submit"
              class="btn btn-primary">
              Register
            </button>
          </div>
        </div>
      </form>
    </div>
    <div class="col-md-6">
      <form [formGroup]="loginForm" (ngSubmit)="onLogin()">
        <div class="card ">
          <div class="card-header "><h4 class="card-title">Login Form</h4></div>
          <div class="card-body ">
            <div class="form-group has-label" [ngClass]="{ 'has-danger': ((focusTouched3 || login) && loginF.fullName.errors) || (loginF.fullName.value != '' && loginF.fullName.errors), 'has-success': !(loginF.fullName.errors) }">
              <label>Full Name *</label>
              <input type="text" formControlName="fullName" (focus)="focusTouched3 = true" class="form-control" />
          </div>
          <div class="form-group has-label" [ngClass]="{ 'has-danger': ((focusTouched4 || login) && loginF.email.errors) || (loginF.email.value != '' && loginF.email.errors), 'has-success': !loginF.email.errors }" >
              <label> Email Address * </label>
              <input type="text" formControlName="email" (focus)="focusTouched4 = true" class="form-control" />
          </div>
          <div class="form-group has-label" [ngClass]="{ 'has-danger': ((focusTouched5 || login) && loginF.password.errors) || (loginF.password.value != '' && loginF.password.errors), 'has-success': !(loginF.password.errors) }">
              <label> Password * </label>
              <input type="password" formControlName="password" (focus)="focusTouched5 = true" class="form-control"  />
          </div>
          <div class="category form-category">* Required fields</div>
        </div>
        <div class="card-footer text-center">
          <button type="submit" class="btn btn-primary">Register</button>
        </div>
      </div>
      </form>
    </div>
    <div class="col-md-12">
      <form [formGroup]="typeForm" (ngSubmit)="onType()" class="form-horizontal" >
        <div class="card ">
          <div class="card-header ">
            <h4 class="card-title">Type Validation</h4>
          </div>
          <div class="card-body ">
            <div class="row">
              <label class="col-sm-2 col-form-label">Required Text</label>
              <div class="col-sm-7">
                <div class="form-group" [ngClass]="{ 'has-danger': ((focusTouched6 || type) && typeF.requiredText.errors) || (typeF.requiredText.value != '' && typeF.requiredText.errors), 'has-success': !(typeF.requiredText.errors) }">
                  <input type="text" formControlName="requiredText" (focus)="focusTouched6 = true" class="form-control" />
                </div>
              </div>
              <label class="col-sm-3 label-on-right">
                <code>required</code>
              </label>
            </div>
            <div class="row">
              <label class="col-sm-2 col-form-label">Email</label>
              <div class="col-sm-7">
                <div class="form-group" [ngClass]="{ 'has-danger': ((focusTouched7 || type) && typeF.email.errors) || (typeF.email.value != '' && typeF.email.errors), 'has-success': !typeF.email.errors }">
                  <input type="text" formControlName="email" (focus)="focusTouched7 = true" class="form-control" />
                </div>
              </div>
              <label class="col-sm-3 label-on-right">
                <code>email="true"</code>
              </label>
            </div>
            <div class="row">
              <label class="col-sm-2 col-form-label">Number</label>
              <div class="col-sm-7">
                <div class="form-group" [ngClass]="{ 'has-danger': ((focusTouched8 || type) && typeF.number.errors) || (typeF.number.value != '' && typeF.number.errors), 'has-success': !typeF.number.errors }">
                  <input
                    class="form-control"
                    type="text"
                    name="number"
                     (focus)="focusTouched8 = true"
                    formControlName="number"
                    number="true"
                  />
                </div>
              </div>
              <label class="col-sm-3 label-on-right">
                <code>number="true"</code>
              </label>
            </div>
            <div class="row">
              <label class="col-sm-2 col-form-label">Url</label>
              <div class="col-sm-7">
                <div class="form-group" [ngClass]="{ 'has-danger': ((focusTouched9 || type) && typeF.url.errors) || (typeF.url.value != '' && typeF.url.errors), 'has-success': !typeF.url.errors }">
                  <input
                    class="form-control"
                    type="text"
                    name="url"
                     (focus)="focusTouched9 = true"
                    formControlName="url"
                    url="true"
                  />
                </div>
              </div>
              <label class="col-sm-3 label-on-right">
                <code>url="true"</code>
              </label>
            </div>
            <div class="row">
              <label class="col-sm-2 col-form-label">Equal to</label>
              <div class="col-sm-3">
                <div class="form-group" [ngClass]="{ 'has-danger': ((focusTouched10 || type) && typeF.idSource.errors) || (typeF.idSource.value != '' && typeF.idSource.errors), 'has-success': !(typeF.idSource.errors) }">
                  <input
                    class="form-control"
                    id="idSource"
                     (focus)="focusTouched10 = true"
                    formControlName="idSource"
                    type="text"
                    placeholder="#idSource"
                  />
                </div>
              </div>
              <div class="col-sm-3">
                <div class="form-group" [ngClass]="{ 'has-danger': ((focusTouched11 || type) && typeF.idDestination.errors) || (typeF.idDestination.value != '' && typeF.idDestination.errors), 'has-success': !typeF.idDestination.errors }">
                  <input
                    class="form-control"
                    id="idDestination"
                    formControlName="idDestination"
                    type="text"
                     (focus)="focusTouched11 = true"
                    placeholder="#idDestination"
                    equalTo="#idSource"
                  />
                </div>
              </div>
              <label class="col-sm-4 label-on-right">
                <code>equalTo="#idSource"</code>
              </label>
            </div>
          </div>
          <div class="card-footer text-center">
            <button type="submit" class="btn btn-primary">
              Validate Inputs
            </button>
          </div>
        </div>
      </form>
    </div>
    <div class="col-md-12">
      <form [formGroup]="rangeForm" (ngSubmit)="onRange()" class="form-horizontal">
        <div class="card ">
          <div class="card-header ">
            <h4 class="card-title">Range Validation</h4>
          </div>
          <div class="card-body ">
            <div class="row">
              <label class="col-sm-2 col-form-label">Min Length</label>
              <div class="col-sm-7">
                <div class="form-group" [ngClass]="{ 'has-danger': ((focusTouched12 || range) && rangeF.minLength.errors) || (rangeF.minLength.value != '' && rangeF.minLength.errors), 'has-success': !rangeF.minLength.errors }">
                  <input
                    class="form-control"
                    type="text"
                     (focus)="focusTouched12 = true"
                    formControlName="minLength"
                    name="min_length"
                    minLength="5"
                  />
                </div>
              </div>
              <label class="col-sm-3 label-on-right">
                <code>minLength="5"</code>
              </label>
            </div>
            <div class="row">
              <label class="col-sm-2 col-form-label">Max Length</label>
              <div class="col-sm-7">
                <div class="form-group" [ngClass]="{ 'has-danger': ((focusTouched13 || range) && rangeF.maxLength.errors) || (rangeF.maxLength.value != '' && rangeF.maxLength.errors), 'has-success': !rangeF.maxLength.errors }">
                  <input
                    class="form-control"
                     (focus)="focusTouched13 = true"
                    formControlName="maxLength"
                    type="text"
                    name="max_length"
                  />
                </div>
              </div>
              <label class="col-sm-3 label-on-right">
                <code>maxLength="5"</code>
              </label>
            </div>
            <div class="row">
              <label class="col-sm-2 col-form-label">Range</label>
              <div class="col-sm-7">
                <div class="form-group" [ngClass]="{ 'has-danger': ((focusTouched14 || range) && rangeF.rangeD.errors) || (rangeF.rangeD.value != '' && rangeF.rangeD.errors), 'has-success': !rangeF.rangeD.errors }">
                  <input
                    class="form-control"
                    formControlName="rangeD"
                    type="text"
                     (focus)="focusTouched14 = true"
                    name="rangeD"
                    range="[6,10]"
                  />
                </div>
              </div>
              <label class="col-sm-3 label-on-right">
                <code>range="[6,10]"</code>
              </label>
            </div>
            <div class="row">
              <label class="col-sm-2 col-form-label">Min Value</label>
              <div class="col-sm-7">
                <div class="form-group" [ngClass]="{ 'has-danger': ((focusTouched15 || range) && rangeF.minValue.errors) || (rangeF.minValue.value != '' && rangeF.minValue.errors), 'has-success': !rangeF.minValue.errors }">
                  <input class="form-control" type="text" (focus)="focusTouched15 = true" name="min" min="6" formControlName="minValue" />
                </div>
              </div>
              <label class="col-sm-3 label-on-right">
                <code>min="6"</code>
              </label>
            </div>
            <div class="row">
              <label class="col-sm-2 col-form-label">Max Value</label>
              <div class="col-sm-7">
                <div class="form-group" [ngClass]="{ 'has-danger': ((focusTouched16 || range) && rangeF.maxValue.errors) || (rangeF.maxValue.value != '' && rangeF.maxValue.errors), 'has-success': !rangeF.maxValue.errors }">
                  <input class="form-control" type="text" (focus)="focusTouched16 = true" name="max" max="6" formControlName="maxValue" />
                </div>
              </div>
              <label class="col-sm-3 label-on-right">
                <code>max="6"</code>
              </label>
            </div>
          </div>
          <div class="card-footer text-center">
            <button type="submit" class="btn btn-primary">
              Validate Inputs
            </button>
          </div>
        </div>
      </form>
    </div>
  </div>
</div>

// react-now-ui-dashboard/src/views/Forms/ValidationForms.jsx
/*!

=========================================================
* Now UI Dashboard PRO React - v1.3.0
=========================================================

* Product Page: https://www.creative-tim.com/product/now-ui-dashboard-pro-react
* Copyright 2019 Creative Tim (https://www.creative-tim.com)

* Coded by Creative Tim

=========================================================

* The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

*/
import React from "react";

// reactstrap components
import {
  Form,
  FormGroup,
  Input,
  Label,
  Card,
  CardBody,
  CardHeader,
  CardTitle,
  CardFooter,
  Row,
  Col,
  Button
} from "reactstrap";

// core components
import PanelHeader from "components/PanelHeader/PanelHeader.jsx";

class ValidationForms extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      register: {
        emailState: "",
        passwordState: "",
        confirmState: "",
        fullNameState: "",
        email: "",
        password: "",
        confirm: "",
        fullName: ""
      },
      login: {
        email: "",
        confirm: "",
        emailState: "",
        confirmState: ""
      },
      type: {
        required: "",
        email: "",
        number: "",
        url: "",
        source: "",
        destionation: "",
        requiredState: "",
        emailState: "",
        numberState: "",
        urlState: "",
        equalState: ""
      },
      range: {
        minLength: "",
        maxLength: "",
        range: "",
        min: "",
        max: "",
        minLengthState: "",
        maxLengthState: "",
        rangeState: "",
        minState: "",
        maxState: ""
      }
    };
  }
  registerEmail(e) {
    var register = this.state.register;
    register["email"] = e.target.value;
    var emailRex = /^(([^<>()[\]\\.,;:\s@"]+(\.[^<>()[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
    if (emailRex.test(e.target.value)) {
      register["emailState"] = "has-success";
    } else {
      register["emailState"] = "has-danger";
    }
    this.setState({ register });
  }
  registerPassword(e) {
    var register = this.state.register;
    register["password"] = e.target.value;
    if (e.target.value.length > 0) {
      register["passwordState"] = "has-success";
    } else {
      register["passwordState"] = "has-danger";
    }
    if (register["password"] === register["confirm"]) {
      register["confirmState"] = "has-success";
    } else {
      register["confirmState"] = "has-danger";
    }
    this.setState({ register });
  }
  registerConfirm(e) {
    var register = this.state.register;
    register["confirm"] = e.target.value;
    if (register["password"] === register["confirm"]) {
      register["confirmState"] = "has-success";
    } else {
      register["confirmState"] = "has-danger";
    }
    this.setState({ register });
  }
  registerSubmit(e) {
    var register = this.state.register;
    if (register["emailState"] !== "has-success")
      register["emailState"] = "has-danger";
    if (register["passwordState"] !== "has-success")
      register["passwordState"] = "has-danger";
    if (register["confirmState"] !== "has-success")
      register["confirmState"] = "has-danger";
    this.setState({ register });
  }
  loginEmail(e) {
    var login = this.state.login;
    login["email"] = e.target.value;
    var emailRex = /^(([^<>()[\]\\.,;:\s@"]+(\.[^<>()[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
    if (emailRex.test(e.target.value)) {
      login["emailState"] = "has-success";
    } else {
      login["emailState"] = "has-danger";
    }
    this.setState({ login });
  }
  loginFullName(e) {
    var login = this.state.login;
    login["fullName"] = e.target.value;
    if (/[a-z]/.test(e.target.value) && /[A-Z]/.test(e.target.value)) {
      login["fullNameState"] = "has-success";
    } else {
      login["fullNameState"] = "has-danger";
    }
    this.setState({ login });
  }
  loginPassword(e) {
    var login = this.state.login;
    login["password"] = e.target.value;
    if (e.target.value.length > 0) {
      login["passwordState"] = "has-success";
    } else {
      login["passwordState"] = "has-danger";
    }
    this.setState({ login });
  }
  loginSubmit(e) {
    var login = this.state.login;
    if (login["emailState"] !== "has-success")
      login["emailState"] = "has-danger";
    if (login["passwordState"] !== "has-success")
      login["passwordState"] = "has-danger";
    if (login["fullNameState"] !== "has-success")
      login["fullNameState"] = "has-danger";
    this.setState({ login });
  }
  typeRequired(e) {
    var type = this.state.type;
    type["required"] = e.target.value;
    if (type["required"].length > 0) {
      type["requiredState"] = "has-success";
    } else {
      type["requiredState"] = "has-danger";
    }
    this.setState({ type });
  }
  typeEmail(e) {
    var emailRex = /^(([^<>()[\]\\.,;:\s@"]+(\.[^<>()[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
    var type = this.state.type;
    type["email"] = e.target.value;
    if (emailRex.test(type["email"])) {
      type["emailState"] = "has-success";
    } else {
      type["emailState"] = "has-danger";
    }
    this.setState({ type });
  }
  typeNumber(e) {
    var numberRex = new RegExp("^[0-9]+$");
    var type = this.state.type;
    type["number"] = e.target.value;
    if (numberRex.test(type["number"])) {
      type["numberState"] = "has-success";
    } else {
      type["numberState"] = "has-danger";
    }
    this.setState({ type });
  }
  typeUrl(e) {
    var type = this.state.type;
    type["url"] = e.target.value;
    try {
      new URL(type["url"]);
      type["urlState"] = "has-success";
    } catch (_) {
      type["urlState"] = "has-danger";
    }
    this.setState({ type });
  }
  typeSource(e) {
    var type = this.state.type;
    type["source"] = e.target.value;
    if (type["source"] === type["destionation"]) {
      type["equalState"] = "has-success";
    } else {
      type["equalState"] = "has-danger";
    }
    this.setState({ type });
  }
  typeDestionation(e) {
    var type = this.state.type;
    type["destionation"] = e.target.value;
    if (type["source"] === type["destionation"]) {
      type["equalState"] = "has-success";
    } else {
      type["equalState"] = "has-danger";
    }
    this.setState({ type });
  }
  typeValidate(e) {
    var type = this.state.type;
    if (type["requiredState"] !== "has-success")
      type["requiredState"] = "has-danger";
    if (type["emailState"] !== "has-success") type["emailState"] = "has-danger";
    if (type["numberState"] !== "has-success")
      type["numberState"] = "has-danger";
    if (type["urlState"] !== "has-success") type["urlState"] = "has-danger";
    if (type["equalState"] !== "has-success") type["equalState"] = "has-danger";
    this.setState({ type });
  }
  rangeMinL(e) {
    var range = this.state.range;
    range["minLength"] = e.target.value;
    if (range["minLength"].length > 4) {
      range["minLengthState"] = "has-success";
    } else {
      range["minLengthState"] = "has-danger";
    }
    this.setState({ range });
  }
  rangeMaxL(e) {
    var range = this.state.range;
    range["maxLength"] = e.target.value;
    if (range["maxLength"].length < 6) {
      range["maxLengthState"] = "has-success";
    } else {
      range["maxLengthState"] = "has-danger";
    }
    this.setState({ range });
  }
  rangeRange(e) {
    var numberRex = new RegExp("^[0-9]+$");
    var range = this.state.range;
    range["range"] = e.target.value;
    if (!numberRex.test(range["range"])) {
      range["rangeState"] = "has-danger";
    } else {
      if (range["range"] < 11 && range["range"] > 5) {
        range["rangeState"] = "has-success";
      } else {
        range["rangeState"] = "has-danger";
      }
    }
    this.setState({ range });
  }
  rangeMin(e) {
    var numberRex = new RegExp("^[0-9]+$");
    var range = this.state.range;
    range["min"] = e.target.value;
    if (!numberRex.test(range["min"])) {
      range["minState"] = "has-danger";
    } else {
      if (range["min"] > 5) {
        range["minState"] = "has-success";
      } else {
        range["minState"] = "has-danger";
      }
    }
    this.setState({ range });
  }
  rangeMax(e) {
    var numberRex = new RegExp("^[0-9]+$");
    var range = this.state.range;
    range["max"] = e.target.value;
    if (!numberRex.test(range["max"])) {
      range["maxState"] = "has-danger";
    } else {
      if (range["max"] < 7) {
        range["maxState"] = "has-success";
      } else {
        range["maxState"] = "has-danger";
      }
    }
    this.setState({ range });
  }
  rangeValidate(e) {
    var range = this.state.range;
    if (range["minLengthState"] !== "has-success")
      range["minLengthState"] = "has-danger";
    if (range["maxLengthState"] !== "has-success")
      range["maxLengthState"] = "has-danger";
    if (range["rangeState"] !== "has-success")
      range["rangeState"] = "has-danger";
    if (range["minState"] !== "has-success") range["minState"] = "has-danger";
    if (range["maxState"] !== "has-success") range["maxState"] = "has-danger";
    this.setState({ range });
  }
  render() {
    return (
      <>
        <PanelHeader size="sm" />
        <div className="content">
          <Row>
            <Col xs={12} md={6}>
              <Form>
                <Card>
                  <CardHeader>
                    <CardTitle tag="h4">Register Form</CardTitle>
                  </CardHeader>
                  <CardBody>
                    <FormGroup
                      className={"has-label " + this.state.register.emailState}
                    >
                      <Label>Email Address *</Label>
                      <Input
                        type="email"
                        onChange={e => this.registerEmail(e)}
                      />
                    </FormGroup>
                    <FormGroup
                      className={
                        "has-label " + this.state.register.passwordState
                      }
                    >
                      <Label>Password *</Label>
                      <Input
                        type="password"
                        autoComplete="password"
                        onChange={e => this.registerPassword(e)}
                      />
                    </FormGroup>
                    <FormGroup
                      className={
                        "has-label " + this.state.register.confirmState
                      }
                    >
                      <Label>Confirm Password *</Label>
                      <Input
                        type="password"
                        autoComplete="password"
                        onChange={e => this.registerConfirm(e)}
                      />
                    </FormGroup>
                    <div className="category form-category">
                      * Required fields
                    </div>
                  </CardBody>
                  <CardFooter className="text-right">
                    <FormGroup check className="pull-left">
                      <Label check>
                        <Input type="checkbox" />
                        <span className="form-check-sign" />
                        Subscribe to newsletter
                      </Label>
                    </FormGroup>
                    <Button
                      color="primary"
                      onClick={e => this.registerSubmit(e)}
                    >
                      Register
                    </Button>
                  </CardFooter>
                </Card>
              </Form>
            </Col>
            <Col xs={12} md={6}>
              <Form>
                <Card>
                  <CardHeader>
                    <CardTitle tag="h4">Login Form</CardTitle>
                  </CardHeader>
                  <CardBody>
                    <FormGroup
                      className={"has-label " + this.state.login.fullNameState}
                    >
                      <Label>Full Name *</Label>
                      <Input
                        type="text"
                        onChange={e => this.loginFullName(e)}
                      />
                    </FormGroup>
                    <FormGroup
                      className={"has-label " + this.state.login.emailState}
                    >
                      <Label>Email Address *</Label>
                      <Input type="email" onChange={e => this.loginEmail(e)} />
                    </FormGroup>
                    <FormGroup
                      className={"has-label " + this.state.login.passwordState}
                    >
                      <Label>Password *</Label>
                      <Input
                        type="password"
                        autoComplete="password"
                        onChange={e => this.loginPassword(e)}
                      />
                    </FormGroup>
                    <div className="category form-category">
                      * Required fields
                    </div>
                  </CardBody>
                  <CardFooter className="text-center">
                    <Button color="primary" onClick={e => this.loginSubmit(e)}>
                      Login
                    </Button>
                  </CardFooter>
                </Card>
              </Form>
            </Col>
            <Col xs={12}>
              <Form className="form-horizontal">
                <Card>
                  <CardHeader>
                    <CardTitle tag="h4">Type Validation</CardTitle>
                  </CardHeader>
                  <CardBody>
                    <Row>
                      <Label sm={2}>Required Text</Label>
                      <Col xs={12} sm={7}>
                        <FormGroup className={this.state.type.requiredState}>
                          <Input
                            type="text"
                            onChange={e => this.typeRequired(e)}
                          />
                        </FormGroup>
                      </Col>
                      <Label sm={3} className="label-on-right">
                        <code>required</code>
                      </Label>
                    </Row>
                    <Row>
                      <Label sm={2}>Email</Label>
                      <Col xs={12} sm={7}>
                        <FormGroup className={this.state.type.emailState}>
                          <Input
                            type="email"
                            onChange={e => this.typeEmail(e)}
                          />
                        </FormGroup>
                      </Col>
                      <Label sm={3} className="label-on-right">
                        <code>email</code>
                      </Label>
                    </Row>
                    <Row>
                      <Label sm={2}>Number</Label>
                      <Col xs={12} sm={7}>
                        <FormGroup className={this.state.type.numberState}>
                          <Input
                            type="text"
                            onChange={e => this.typeNumber(e)}
                          />
                        </FormGroup>
                      </Col>
                      <Label sm={3} className="label-on-right">
                        <code>number</code>
                      </Label>
                    </Row>
                    <Row>
                      <Label sm={2}>Url</Label>
                      <Col xs={12} sm={7}>
                        <FormGroup className={this.state.type.urlState}>
                          <Input type="text" onChange={e => this.typeUrl(e)} />
                        </FormGroup>
                      </Col>
                      <Label sm={3} className="label-on-right">
                        <code>url</code>
                      </Label>
                    </Row>
                    <Row>
                      <Label sm={2}>Equal to</Label>
                      <Col xs={12} sm={3}>
                        <FormGroup className={this.state.type.equalState}>
                          <Input
                            type="text"
                            onChange={e => this.typeSource(e)}
                            placeholder="#idSource"
                          />
                        </FormGroup>
                      </Col>
                      <Col xs={12} sm={3}>
                        <FormGroup className={this.state.type.equalState}>
                          <Input
                            type="text"
                            onChange={e => this.typeDestionation(e)}
                            placeholder="#idDestination"
                          />
                        </FormGroup>
                      </Col>
                      <Label sm={3} className="label-on-right">
                        <code>equalTo</code>
                      </Label>
                    </Row>
                  </CardBody>
                  <CardFooter className="text-center">
                    <Button color="primary" onClick={e => this.typeValidate(e)}>
                      Validate Inputs
                    </Button>
                  </CardFooter>
                </Card>
              </Form>
            </Col>
            <Col xs={12}>
              <Form className="form-horizontal">
                <Card>
                  <CardHeader>
                    <CardTitle tag="h4">Range Validation</CardTitle>
                  </CardHeader>
                  <CardBody>
                    <Row>
                      <Label sm={2}>Min length</Label>
                      <Col xs={12} sm={7}>
                        <FormGroup className={this.state.range.minLengthState}>
                          <Input
                            type="text"
                            onChange={e => this.rangeMinL(e)}
                          />
                        </FormGroup>
                      </Col>
                      <Label sm={3} className="label-on-right">
                        <code>minLength="5"</code>
                      </Label>
                    </Row>
                    <Row>
                      <Label sm={2}>Max length</Label>
                      <Col xs={12} sm={7}>
                        <FormGroup className={this.state.range.maxLengthState}>
                          <Input
                            type="text"
                            onChange={e => this.rangeMaxL(e)}
                          />
                        </FormGroup>
                      </Col>
                      <Label sm={3} className="label-on-right">
                        <code>maxLength="5"</code>
                      </Label>
                    </Row>
                    <Row>
                      <Label sm={2}>Range</Label>
                      <Col xs={12} sm={7}>
                        <FormGroup className={this.state.range.rangeState}>
                          <Input
                            type="text"
                            onChange={e => this.rangeRange(e)}
                          />
                        </FormGroup>
                      </Col>
                      <Label sm={3} className="label-on-right">
                        <code>range="[6,10]"</code>
                      </Label>
                    </Row>
                    <Row>
                      <Label sm={2}>Min Value</Label>
                      <Col xs={12} sm={7}>
                        <FormGroup className={this.state.range.minState}>
                          <Input type="text" onChange={e => this.rangeMin(e)} />
                        </FormGroup>
                      </Col>
                      <Label sm={3} className="label-on-right">
                        <code>min="6"</code>
                      </Label>
                    </Row>
                    <Row>
                      <Label sm={2}>Max Value</Label>
                      <Col xs={12} sm={7}>
                        <FormGroup className={this.state.range.maxState}>
                          <Input type="text" onChange={e => this.rangeMax(e)} />
                        </FormGroup>
                      </Col>
                      <Label sm={3} className="label-on-right">
                        <code>max="6"</code>
                      </Label>
                    </Row>
                  </CardBody>
                  <CardFooter className="text-center">
                    <Button
                      color="primary"
                      onClick={e => this.rangeValidate(e)}
                    >
                      Validate Inputs
                    </Button>
                  </CardFooter>
                </Card>
              </Form>
            </Col>
          </Row>
        </div>
      </>
    );
  }
}

export default ValidationForms;
