// light-bootstrap-dashboard-pro-react-v1/src/views/Components/Notifications.jsx
/*!

=========================================================
* Light Bootstrap Dashboard PRO React - v1.2.0
=========================================================

* Product Page: https://www.creative-tim.com/product/light-bootstrap-dashboard-pro-react
* Copyright 2019 Creative Tim (https://www.creative-tim.com)

* Coded by Creative Tim

=========================================================

* The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

*/
/*eslint-disable*/
import React, { Component } from "react";
import { Modal, Alert, Grid, Row, Col } from "react-bootstrap";

import Card from "components/Card/Card.jsx";

import Button from "components/CustomButton/CustomButton.jsx";

class Notifications extends Component {
  constructor(props) {
    super(props);
    this.state = {
      showModal: false
    };
  }
  render() {
    return (
      <div className="main-content">
        <Grid fluid>
          <Card
            title="Notifications"
            category={
              <span>
                Handcrafted by{" "}
                <a
                  target="_blank"
                  href="https://github.com/igorprado"
                >
                  Igor Prado
                </a>
                . Please checkout the{" "}
                <a
                  href="https://github.com/igorprado/react-notification-system"
                  target="_blank"
                >
                  full documentation.
                </a>
              </span>
            }
            content={
              <div>
                <Row>
                  <Col md={6}>
                    <h5>Notifications Style</h5>
                    <Alert bsStyle="info">
                      <span>This is a plain notification</span>
                    </Alert>
                    <Alert bsStyle="info">
                      <button
                        type="button"
                        aria-hidden="true"
                        className="close"
                      >
                        ×
                      </button>
                      <span>This is a notification with close button.</span>
                    </Alert>
                    <Alert bsStyle="info" className="alert-with-icon">
                      <button
                        type="button"
                        aria-hidden="true"
                        className="close"
                      >
                        ×
                      </button>
                      <span data-notify="icon" className="pe-7s-bell" />
                      <span data-notify="message">
                        This is a notification with close button and icon.
                      </span>
                    </Alert>
                    <Alert bsStyle="info" className="alert-with-icon">
                      <button
                        type="button"
                        aria-hidden="true"
                        className="close"
                      >
                        ×
                      </button>
                      <span data-notify="icon" className="pe-7s-bell" />
                      <span data-notify="message">
                        This is a notification with close button and icon and
                        have many lines. You can see that the icon and the close
                        button are always vertically aligned. This is a
                        beautiful notification. So you don't have to worry about
                        the style.
                      </span>
                    </Alert>
                  </Col>
                  <Col md={6}>
                    <h5>Notification states</h5>
                    <Alert bsStyle="info">
                      <button
                        type="button"
                        aria-hidden="true"
                        className="close"
                      >
                        ×
                      </button>
                      <span>
                        <b> Info - </b> This is a regular notification made with
                        bsStyle="info"
                      </span>
                    </Alert>
                    <Alert bsStyle="success">
                      <button
                        type="button"
                        aria-hidden="true"
                        className="close"
                      >
                        ×
                      </button>
                      <span>
                        <b> Success - </b> This is a regular notification made
                        with bsStyle="success"
                      </span>
                    </Alert>
                    <Alert bsStyle="warning">
                      <button
                        type="button"
                        aria-hidden="true"
                        className="close"
                      >
                        ×
                      </button>
                      <span>
                        <b> Warning - </b> This is a regular notification made
                        with bsStyle="warning"
                      </span>
                    </Alert>
                    <Alert bsStyle="danger">
                      <button
                        type="button"
                        aria-hidden="true"
                        className="close"
                      >
                        ×
                      </button>
                      <span>
                        <b> Danger - </b> This is a regular notification made
                        with bsStyle="danger"
                      </span>
                    </Alert>
                  </Col>
                </Row>
                <br />
                <br />
                <div className="places-buttons">
                  <Row>
                    <Col md={6} mdOffset={3} className="text-center">
                      <h5>
                        Notifications Places
                        <p className="category">Click to view notifications</p>
                      </h5>
                    </Col>
                  </Row>
                  <Row>
                    <Col md={2} mdOffset={3}>
                      <Button
                        block
                        onClick={() => this.props.handleClick("tl")}
                      >
                        Top Left
                      </Button>
                    </Col>
                    <Col md={2}>
                      <Button
                        block
                        onClick={() => this.props.handleClick("tc")}
                      >
                        Top Center
                      </Button>
                    </Col>
                    <Col md={2}>
                      <Button
                        block
                        onClick={() => this.props.handleClick("tr")}
                      >
                        Top Right
                      </Button>
                    </Col>
                  </Row>
                  <Row>
                    <Col md={2} mdOffset={3}>
                      <Button
                        block
                        onClick={() => this.props.handleClick("bl")}
                      >
                        Bottom Left
                      </Button>
                    </Col>
                    <Col md={2}>
                      <Button
                        block
                        onClick={() => this.props.handleClick("bc")}
                      >
                        Bottom Center
                      </Button>
                    </Col>
                    <Col md={2}>
                      <Button
                        block
                        onClick={() => this.props.handleClick("br")}
                      >
                        Bottom Right
                      </Button>
                    </Col>
                  </Row>
                </div>
                <h4 className="title">Modals</h4>
                <p className="category">
                  We've restyled the default modals from Bootstrap. Please
                  checkout the{" "}
                  <a href="https://react-bootstrap.github.io/components.html#modals" target="_blank">
                    full documentation
                  </a>
                  .
                </p>
                <br />
                <Row>
                  <Col md={6}>
                    <Button
                      bsStyle="info"
                      fill
                      onClick={() => this.setState({ showModal: true })}
                    >
                      Launch demo modal
                    </Button>
                    <Modal
                      show={this.state.showModal}
                      onHide={() => this.setState({ showModal: false })}
                    >
                      <Modal.Header closeButton>
                        <Modal.Title>Modal title</Modal.Title>
                      </Modal.Header>
                      <Modal.Body>...</Modal.Body>
                      <Modal.Footer>
                        <Button
                          simple
                          onClick={() => this.setState({ showModal: false })}
                        >
                          Close
                        </Button>
                        <Button
                          bsStyle="success"
                          fill
                          onClick={() => this.setState({ showModal: false })}
                        >
                          Save changes
                        </Button>
                      </Modal.Footer>
                    </Modal>
                  </Col>
                </Row>
              </div>
            }
          />
        </Grid>
      </div>
    );
  }
}

export default Notifications;

// angular-light-bootstrap-dashboard/src/app/components/notifications/notifications.component.ts
import { Component } from '@angular/core';

declare var $:any;

@Component({
    moduleId: module.id,
    selector: 'notifications-cmp',
    templateUrl: 'notifications.component.html'
})

export class NotificationsComponent{

    showNotification(from, align){
        var type = ['','info','success','warning','danger'];

        var color = Math.floor((Math.random() * 4) + 1);

    	$.notify({
        	icon: "pe-7s-gift",
        	message: "<b>Light Bootstrap Dashboard PRO</b> - forget about boring dashboards."

        },{
            type: type[color],
            timer: 4000,
            placement: {
                from: from,
                align: align
            }
        });
	}
}

<div class="main-content" >
    <div class="container-fluid">
      <!-- Modal -->
      <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              <h4 class="modal-title" id="myModalLabel">Modal title</h4>
            </div>
            <div class="modal-body">
              ...
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-default btn-simple" data-dismiss="modal">Close</button>
              <button type="button" class="btn btn-success btn-fill">Save changes</button>
            </div>
          </div>
        </div>
      </div>
        <div class="card">
            <div class="header">
                <h4 class="title">Notifications</h4>
                <p class="category">Handcrafted by our friend <a target="_blank" href="https://github.com/mouse0270">Robert McIntosh</a>. Please checkout the <a href="http://bootstrap-notify.remabledesigns.com/" target="_blank">full documentation.</a></p>

            </div>
            <div class="content">
                <div class="row">
                    <div class="col-md-6">
                        <h5>Notifications Style</h5>
                        <div class="alert alert-info">
                            <span>This is a plain notification</span>
                        </div>
                        <div class="alert alert-info">
                            <button type="button" aria-hidden="true" class="close">×</button>
                            <span>This is a notification with close button.</span>
                        </div>
                        <div class="alert alert-info alert-with-icon" data-notify="container">
                            <button type="button" aria-hidden="true" class="close">×</button>
                            <span data-notify="icon" class="pe-7s-bell"></span>
                            <span data-notify="message">This is a notification with close button and icon.</span>
                        </div>
                        <div class="alert alert-info alert-with-icon" data-notify="container">
                            <button type="button" aria-hidden="true" class="close">×</button>
                            <span data-notify="icon" class="pe-7s-bell"></span>
                            <span data-notify="message">This is a notification with close button and icon and have many lines. You can see that the icon and the close button are always vertically aligned. This is a beautiful notification. So you don't have to worry about the style.</span>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <h5>Notification States</h5>
                        <div class="alert alert-info">
                            <button type="button" aria-hidden="true" class="close">×</button>
                            <span><b> Info - </b> This is a regular notification made with ".alert-info"</span>
                        </div>
                        <div class="alert alert-success">
                            <button type="button" aria-hidden="true" class="close">×</button>
                            <span><b> Success - </b> This is a regular notification made with ".alert-success"</span>
                        </div>
                        <div class="alert alert-warning">
                            <button type="button" aria-hidden="true" class="close">×</button>
                            <span><b> Warning - </b> This is a regular notification made with ".alert-warning"</span>
                        </div>
                        <div class="alert alert-danger">
                            <button type="button" aria-hidden="true" class="close">×</button>
                            <span><b> Danger - </b> This is a regular notification made with ".alert-danger"</span>
                        </div>
                    </div>
                </div>
                <br>
                <br>
                <div class="places-buttons">
                    <div class="row">
                        <div class="col-md-6 col-md-offset-3 text-center">
                            <h5>Notifications Places
                                <p class="category">Click to view notifications</p>
                            </h5>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-3 col-md-offset-2">
                            <button class="btn btn-default btn-block" (click)="showNotification('top','left')">Top Left</button>
                        </div>
                        <div class="col-md-3">
                            <button class="btn btn-default btn-block" (click)="showNotification('top','center')">Top Center</button>
                        </div>
                        <div class="col-md-3">
                            <button class="btn btn-default btn-block" (click)="showNotification('top','right')">Top Right</button>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-3 col-md-offset-2">
                            <button class="btn btn-default btn-block" (click)="showNotification('bottom','left')">Bottom Left</button>
                        </div>
                        <div class="col-md-3">
                            <button class="btn btn-default btn-block" (click)="showNotification('bottom','center')">Bottom Center</button>
                        </div>
                        <div class="col-md-3">
                            <button class="btn btn-default btn-block" (click)="showNotification('bottom','right')">Bottom Right</button>
                        </div>
                    </div>
                </div>

                <h4 class="title">Modals</h4>
                <p class="category">We've restyled the default modals from Bootstrap. Please checkout the <a href="http://getbootstrap.com/javascript/#modals" target="_blank">full documentation</a>.
                </p><br />
                <div class="row">
                    <div class="col-md-6">
                        <!-- Button trigger modal -->
                        <button type="button" class="btn btn-info btn-fill" data-toggle="modal" data-target="#myModal">
                          Launch demo modal
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
