// now-ui-kit-pro-angular-v1/src/app/examples/contactus/contactus.component.ts
import { Component, OnInit } from '@angular/core';
import * as Rellax from 'rellax';

@Component({
  selector: 'app-contactus',
  templateUrl: './contactus.component.html',
  styleUrls: ['./contactus.component.scss']
})
export class ContactusComponent implements OnInit {
    zoom: number = 14;
    lat: number = 44.445248;
    lng: number = 26.099672;
    styles: any[] = [{"featureType":"water","elementType":"geometry","stylers":[{"color":"#e9e9e9"},{"lightness":17}]},{"featureType":"landscape","elementType":"geometry","stylers":[{"color":"#f5f5f5"},{"lightness":20}]},{"featureType":"road.highway","elementType":"geometry.fill","stylers":[{"color":"#ffffff"},{"lightness":17}]},{"featureType":"road.highway","elementType":"geometry.stroke","stylers":[{"color":"#ffffff"},{"lightness":29},{"weight":0.2}]},{"featureType":"road.arterial","elementType":"geometry","stylers":[{"color":"#ffffff"},{"lightness":18}]},{"featureType":"road.local","elementType":"geometry","stylers":[{"color":"#ffffff"},{"lightness":16}]},{"featureType":"poi","elementType":"geometry","stylers":[{"color":"#f5f5f5"},{"lightness":21}]},{"featureType":"poi.park","elementType":"geometry","stylers":[{"color":"#dedede"},{"lightness":21}]},{"elementType":"labels.text.stroke","stylers":[{"visibility":"on"},{"color":"#ffffff"},{"lightness":16}]},{"elementType":"labels.text.fill","stylers":[{"saturation":36},{"color":"#333333"},{"lightness":40}]},{"elementType":"labels.icon","stylers":[{"visibility":"off"}]},{"featureType":"transit","elementType":"geometry","stylers":[{"color":"#f2f2f2"},{"lightness":19}]},{"featureType":"administrative","elementType":"geometry.fill","stylers":[{"color":"#fefefe"},{"lightness":20}]},{"featureType":"administrative","elementType":"geometry.stroke","stylers":[{"color":"#fefefe"},{"lightness":17},{"weight":1.2}]}];
    data : Date = new Date();
    focus;
    focus1;
    focus2;
    focus3;
    focus4;

  constructor() { }

  ngOnInit() {
    var rellaxHeader = new Rellax('.rellax-header');

      var body = document.getElementsByTagName('body')[0];
      body.classList.add('contact-page');
      var navbar = document.getElementsByTagName('nav')[0];
      navbar.classList.add('navbar-transparent');
  }
  ngOnDestroy(){
      var body = document.getElementsByTagName('body')[0];
      body.classList.remove('contact-page');
      var navbar = document.getElementsByTagName('nav')[0];
      navbar.classList.remove('navbar-transparent');

  }

}

<div class="wrapper">
    <div class="page-header page-header-small">
        <div class="page-header-image rellax-header" data-rellax-speed="-8" style="background-image:  url('assets/img/bg45.jpg');">
        </div>
    </div>
    <div class="main">
        <div class="contact-content">
            <div class="container">
                <div class="row">
                    <div class="col-md-5 ml-auto mr-auto">
                        <h2 class="title">Send us a message</h2>
                        <p class="description">You can contact us with anything related to our Products. We'll get in touch with you as soon as possible.
                            <br>
                            <br>
                        </p>
                        <form role="form" id="contact-form" method="post">
                            <label>Your name</label>
                            <div class="input-group" [ngClass]="{'input-group-focus':focus===true}">
                              <div class="input-group-prepend">
                                  <span class="input-group-text"><i class="now-ui-icons users_circle-08"></i></span>
                              </div>
                                <input type="text" class="form-control" placeholder="Your Name..."   (focus)="focus=true" (blur)="focus=false">
                            </div>
                            <label>Email address</label>
                            <div class="input-group" [ngClass]="{'input-group-focus':focus1===true}">
                              <div class="input-group-prepend">
                                  <span class="input-group-text"><i class="now-ui-icons ui-1_email-85"></i></span>
                              </div>
                                <input type="email" class="form-control" placeholder="Email Here..."   (focus)="focus1=true" (blur)="focus1=false">
                            </div>
                            <label>Phone</label>
                            <div class="input-group" [ngClass]="{'input-group-focus':focus2===true}">
                              <div class="input-group-prepend">
                                  <span class="input-group-text">  <i class="now-ui-icons tech_mobile"></i></span>
                              </div>
                                <input type="text" placeholder="Number Here..." class="form-control"   (focus)="focus2=true" (blur)="focus2=false">
                            </div>
                            <div class="form-group">
                                <label>Your message</label>
                                <textarea name="message" class="form-control" id="message" rows="6"></textarea>
                            </div>
                            <div class="submit text-center">
                                <input type="submit" class="btn btn-primary btn-raised btn-round" value="Contact Us" />
                            </div>
                        </form>
                    </div>
                    <div class="col-md-5 ml-auto mr-auto">
                        <div class="info info-horizontal mt-5">
                            <div class="icon icon-primary">
                                <i class="now-ui-icons location_pin"></i>
                            </div>
                            <div class="description">
                                <h4 class="info-title">Find us at the office</h4>
                                <p> Bld Mihail Kogalniceanu, nr. 8,
                                    <br> 7652 Bucharest,
                                    <br> Romania
                                </p>
                            </div>
                        </div>
                        <div class="info info-horizontal">
                            <div class="icon icon-primary">
                                <i class="now-ui-icons tech_mobile"></i>
                            </div>
                            <div class="description">
                                <h4 class="info-title">Give us a ring</h4>
                                <p> Michael Jordan
                                    <br> +40 762 321 762
                                    <br> Mon - Fri, 8:00-22:00
                                </p>
                            </div>
                        </div>
                        <div class="info info-horizontal">
                            <div class="icon icon-primary">
                                <i class="business_briefcase-24 now-ui-icons"></i>
                            </div>
                            <div class="description">
                                <h4 class="info-title">Legal Information</h4>
                                <p> Creative Tim Ltd.
                                    <br> VAT &middot; EN2341241
                                    <br> IBAN &middot; EN8732ENGB2300099123
                                    <br> Bank &middot; Great Britain Bank
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="big-map">
        <agm-map [latitude]="lat" [longitude]="lng" [zoom]="zoom" [styles]="styles">
            <agm-marker [latitude]="lat" [longitude]="lng"></agm-marker>
        </agm-map>
    </div>

    <footer class="footer footer-default ">
        <div class="container">
            <nav>
                <ul>
                    <li>
                        <a href="https://www.creative-tim.com">
                            Creative Tim
                        </a>
                    </li>
                    <li>
                        <a href="https://www.creative-tim.com/about-us">
                            About Us
                        </a>
                    </li>
                    <li>
                        <a href="http://blog.creative-tim.com">
                            Blog
                        </a>
                    </li>
                    <li>
                        <a href="https://www.creative-tim.com/license">
                            License
                        </a>
                    </li>
                </ul>
            </nav>
            <div class="copyright">
                © {{data | date: 'yyyy'}}, Designed by
                <a href="https://www.invisionapp.com" target="_blank">Invision</a>. Coded by
                <a href="https://www.creative-tim.com" target="_blank">Creative Tim</a>.
            </div>
        </div>
    </footer>
</div>

// nuxt-material-kit/src/views/examples/ContactUs.vue
<template>
  <div class="wrapper">
    <div
      id="contactUs2Map"
      class="map"
    />
    <div class="main main-raised">
      <div class="section section-contact">
        <div class="container">
          <div class="md-layout">
            <div class="md-layout-item md-size-50 md-small-size-100 ml-auto">
              <h2 class="title mt-0">
                Send us a message
              </h2>
              <p class="description">
                You can contact us with anything related to our Products. We'll
                get in touch with you as soon as possible.
                <br>
                <br>
              </p>
              <form>
                <md-field>
                  <label>Your Name</label>
                  <md-input
                    v-model="name"
                    type="text"
                  />
                </md-field>
                <md-field>
                  <label>Email Adress</label>
                  <md-input
                    v-model="email"
                    type="email"
                  />
                </md-field>
                <md-field>
                  <label>Phone</label>
                  <md-input
                    v-model="phone"
                    type="number"
                  />
                </md-field>
                <md-field>
                  <label>Your message</label>
                  <md-textarea v-model="textarea" />
                </md-field>
                <div class="submit text-center mt-3">
                  <md-button class="md-primary md-round">
                    Contact Us
                  </md-button>
                </div>
              </form>
            </div>
            <div class="md-layout-item md-size-33 md-small-size-100 ml-auto">
              <info-areas
                class="pt-0"
                info-horizontal
                icon-color="primary"
                icon="pin_drop"
              >
                <h4
                  slot="title"
                  class="info-title"
                >
                  Find us at the office
                </h4>
                <div
                  slot="content"
                  class="description"
                >
                  <p>
                    Bld Mihail Kogalniceanu, nr. 8, <br>
                    7652 Bucharest, <br>
                    Romania
                  </p>
                </div>
              </info-areas>
              <info-areas
                class="pt-0"
                info-horizontal
                icon-color="primary"
                icon="phone"
              >
                <h4
                  slot="title"
                  class="info-title"
                >
                  Give us a ring
                </h4>
                <div
                  slot="content"
                  class="description"
                >
                  <p>
                    Michael Jordan <br>
                    +40 762 321 762 <br>
                    Mon - Fri, 8:00-22:00
                  </p>
                </div>
              </info-areas>
              <info-areas
                class="pt-0"
                info-horizontal
                icon-color="primary"
                icon="business_center"
              >
                <h4
                  slot="title"
                  class="info-title"
                >
                  Legal Information
                </h4>
                <div
                  slot="content"
                  class="description"
                >
                  <p>
                    Creative Tim Ltd. <br>
                    VAT · EN2341241 <br>
                    IBAN · EN8732ENGB2300099123 <br>
                    Bank · Great Britain Bank
                  </p>
                </div>
              </info-areas>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import Mixins from "@/plugins/basicMixins";
import { InfoAreas } from "@/components";
export default {
  components: {
    InfoAreas
  },
  bodyClass: "contact-us",
  mixins: [Mixins.InitMap],
  data() {
    return {
      name: null,
      email: null,
      phone: null,
      textarea: null
    };
  }
};
</script>

<style lang="scss" scoped>
.mt-3 {
  margin-top: 1.5rem;
}
</style>
